### ISSUE TITLE
Home: TypeError: Cannot read property 'filter' of null

### ISSUE THREAD

**Issue by chappy1978** [platformio/platformio-core#1059]
Trying to Import an Arduino Project. I have to say I am not a fan off the new homepage setup. The old version was much more useable.
TypeError: Cannot read property 'filter' of null
    at t.value (http://127.0.0.1:8011/b7b2e59db5b772f69810.min.js:31:86699)
    at http://127.0.0.1:8011/b7b2e59db5b772f69810.min.js:31:86920
    at Array.map (native)
    at t.value (http://127.0.0.1:8011/b7b2e59db5b772f69810.min.js:31:86749)
    at http://127.0.0.1:8011/b7b2e59db5b772f69810.min.js:31:86920
    at Array.map (native)
    at t.value (http://127.0.0.1:8011/b7b2e59db5b772f69810.min.js:31:86749)
    at http://127.0.0.1:8011/b7b2e59db5b772f69810.min.js:31:86920
    at Array.map (native)
    at t.value (http://127.0.0.1:8011/b7b2e59db5b772f69810.min.js:31:86749)

**Comment by ivankravets** [comment]
> Trying to Import an Arduino Project. I have to say I am not a fan off the new homepage setup. The old version was much more useable.

Could you explain in details what is wrong with new PIO Home? We will improve that as soon as possible.

**Comment by ivankravets** [comment]
Could you open PIO IDE Terminal and type
```
pio upgrade
pio update
```
Restart IDE.

Does it work now?

**Comment by ivankravets** [comment]
Please reopen if you still need help
