### ISSUE TITLE
Home: Internal Store Exception

### ISSUE THREAD

**Issue by jagdeepnaik** [platformio/platformio-core#1092]
TypeError: Cannot read property 'replace' of null
Please report this to https://github.com/chjj/marked.
    at t.lex (http://127.0.0.1:8010/993c9d594c3963b6a512.min.js:31:1893263)
    at Function.t.lex (http://127.0.0.1:8010/993c9d594c3963b6a512.min.js:31:1893217)
    at u (http://127.0.0.1:8010/993c9d594c3963b6a512.min.js:31:1891218)
    at http://127.0.0.1:8010/993c9d594c3963b6a512.min.js:31:394737
    at Array.map (native)
    at t.value (http://127.0.0.1:8010/993c9d594c3963b6a512.min.js:31:394318)
    at d._renderValidatedComponentWithoutOwnerOrContext (http://127.0.0.1:8010/993c9d594c3963b6a512.min.js:31:519352)
    at d._renderValidatedComponent (http://127.0.0.1:8010/993c9d594c3963b6a512.min.js:31:519479)
    at d.performInitialMount (http://127.0.0.1:8010/993c9d594c3963b6a512.min.js:31:515320)
    at d.mountComponent (http://127.0.0.1:8010/993c9d594c3963b6a512.min.js:31:514366)

**Comment by ivankravets** [comment]
Could you explain how to reproduce this issue?

**Comment by ivankravets** [comment]
Please reopen if you still need help
