### ISSUE TITLE
Home: Internal Store Exception

### ISSUE THREAD

**Issue by FusedShadowX** [platformio/platformio-core#1115]
Operating system: Windows 8.1 Home
PlatformIO Version: latest (based on pio upgrade)

#### Description of problem

I have already seen the other posts that refered to this issue and followed the instructions. However the problem still exists. As I say below, it is not even possible to add an exising project. Is it a temporary bug that is going to be fixed or a %PATH% variable error/system error/OS error? Is it manually fixable and how? I do not intent to reproduce this issue, but to have some answers furthermore.

Thank you in advance.
 
> TypeError: Cannot read property 'indexOf' of null
    at Object.o [as basename] (http://127.0.0.1:8012/993c9d594c3963b6a512.min.js:11:40221)
    at t.value (http://127.0.0.1:8012/993c9d594c3963b6a512.min.js:31:86316)
    at t.value (http://127.0.0.1:8012/993c9d594c3963b6a512.min.js:31:85138)
    at d._renderValidatedComponentWithoutOwnerOrContext (http://127.0.0.1:8012/993c9d594c3963b6a512.min.js:31:519352)
    at d._renderValidatedComponent (http://127.0.0.1:8012/993c9d594c3963b6a512.min.js:31:519479)
    at d._updateRenderedComponent (http://127.0.0.1:8012/993c9d594c3963b6a512.min.js:31:518783)
    at d._performComponentUpdate (http://127.0.0.1:8012/993c9d594c3963b6a512.min.js:31:518584)
    at d.updateComponent (http://127.0.0.1:8012/993c9d594c3963b6a512.min.js:31:517862)
    at d.receiveComponent (http://127.0.0.1:8012/993c9d594c3963b6a512.min.js:31:516979)
    at Object.receiveComponent (http://127.0.0.1:8012/993c9d594c3963b6a512.min.js:17:27043)

#### Steps to Reproduce

1. Open Visual Studio Code.
2. Wait for PlatformIO Core to verify installation.
3. On PIO Home press New Project
4. On Project Wizard unclick Location: Use default location
5. Error throws.
(It can also be reproduced when pressing Add Existing Project)

**Comment by FusedShadowX** [comment]
#UPDATE
Indeed the user path had ascii characters which I had not checked. If anyone has ascii characters on user's path (e.g. C:/Users/Τασος (Greek ascii characters)) the path cannot be configured for a project. Either make a new user or search on Google how to rename a USER on your OS. 
CAUTION! (for windows users) renaming a user makes a new user path on the same user domain. This means that the folders that contain the previous user's files are not read by the OS. Transfer the old files to your new user in order to keep your files. However, you may need to rename the user's path in many programs so I insist to make a new user.  Also do not transfer the platformIO files on the new user because many internal files are configured with the old path and it won't run.
