### ISSUE TITLE
Home: Error occured while requesting content from http://dl.platformio.org/libraries/examples/2/294/ChangeSensorI2CAddress.ino

### ISSUE THREAD

**Issue by FungkiPandu** [platformio/platformio-core#1147]
Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
    at u.crossDomainError (http://127.0.0.1:8011/8a915bf8c2b0eb535301.min.js:25:158429)
    at XMLHttpRequest.u._end.t.onreadystatechange (http://127.0.0.1:8011/8a915bf8c2b0eb535301.min.js:25:159636)

**Comment by ivankravets** [comment]
Could you close IDE and restart again. Do you see this error?

**Comment by ivankravets** [comment]
Please reopen if you still need help
