### ISSUE TITLE
Home: Libraries: Stats

### ISSUE THREAD

**Issue by jeanga** [platformio/platformio-core#1200]
PlatformIO seems to be broken on Windows 10:
- pio lib install cannot install libs (see https://community.platformio.org/t/packagemanager-is-unable-to-install-tool/2662/13).

and now, this:
Server error:
PIOCoreRPC.spawn ['update', '--core-packages']
PIOCoreRPC.spawn ['platform', 'update', '--only-check', '--json-output'Unhandled Error
Traceback (most recent call last):
  File "C:\Users\jeang\.platformio\packages\pysite-pioplus\txjason\service.py", line 472, in _handle_request
    d = self._call_method(request)
  File "C:\Users\jeang\.platformio\packages\pysite-pioplus\twisted\internet\defer.py", line 1445, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "C:\Users\jeang\.platformio\packages\pysite-pioplus\twisted\internet\defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "C:\Users\jeang\.platformio\packages\pysite-pioplus\txjason\service.py", line 438, in _call_method
    result = yield defer.maybeDeferred(method, *params)
--- <exception caught here> ---
  File "C:\Users\jeang\.platformio\packages\pysite-pioplus\twisted\internet\defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "cmd_home.py", line 431, in cmd_home.PIOCoreRPC.call

  File "cmd_home.py", line 387, in cmd_home.PIOCoreRPC.spawn

exceptions.IOError: [Errno 0] Error

 PIOCoreRPC.spawn ['lib'Unhandled Error
Traceback (most recent call last):
  File "C:\Users\jeang\.platformio\packages\pysite-pioplus\txjason\service.py", line 472, in _handle_request
    d = self._call_method(request)
  File "C:\Users\jeang\.platformio\packages\pysite-pioplus\twisted\internet\defer.py", line 1445, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "C:\Users\jeang\.platformio\packages\pysite-pioplus\twisted\internet\defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "C:\Users\jeang\.platformio\packages\pysite-pioplus\txjason\service.py", line 438, in _call_method
    result = yield defer.maybeDeferred(method, *params)
--- <exception caught here> ---
  File "C:\Users\jeang\.platformio\packages\pysite-pioplus\twisted\internet\defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "cmd_home.py", line 431, in cmd_home.PIOCoreRPC.call

  File "cmd_home.py", line 387, in cmd_home.PIOCoreRPC.spawn

exceptions.IOError: [Errno 0] Error

 PIOCoreRPC.spawn ['lib', 'stats', '--json-output'Unhandled Error
Traceback (most recent call last):
  File "C:\Users\jeang\.platformio\packages\pysite-pioplus\txjason\service.py", line 472, in _handle_request
    d = self._call_method(request)
  File "C:\Users\jeang\.platformio\packages\pysite-pioplus\twisted\internet\defer.py", line 1445, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "C:\Users\jeang\.platformio\packages\pysite-pioplus\twisted\internet\defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "C:\Users\jeang\.platformio\packages\pysite-pioplus\txjason\service.py", line 438, in _call_method
    result = yield defer.maybeDeferred(method, *params)
--- <exception caught here> ---
  File "C:\Users\jeang\.platformio\packages\pysite-pioplus\twisted\internet\defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "cmd_home.py", line 431, in cmd_home.PIOCoreRPC.call

  File "cmd_home.py", line 387, in cmd_home.PIOCoreRPC.spawn

exceptions.IOError: [Errno 0] Error

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
