### ISSUE TITLE
Home: Internal Store Exception

### ISSUE THREAD

**Issue by AKEB** [platformio/platformio-core#1249]
TypeError: Cannot read property 'name' of null
    at http://127.0.0.1:8010/f00d19876293fb32c015.min.js:11:33449
    at Array.map (native)
    at _ (http://127.0.0.1:8010/f00d19876293fb32c015.min.js:11:33320)
    at http://127.0.0.1:8010/f00d19876293fb32c015.min.js:11:33839
    at Array.map (native)
    at y (http://127.0.0.1:8010/f00d19876293fb32c015.min.js:11:33779)
    at Function.a [as mapToProps] (http://127.0.0.1:8010/f00d19876293fb32c015.min.js:25:403989)
    at r (http://127.0.0.1:8010/f00d19876293fb32c015.min.js:6:10578)
    at l (http://127.0.0.1:8010/f00d19876293fb32c015.min.js:6:11948)
    at c (http://127.0.0.1:8010/f00d19876293fb32c015.min.js:6:12066)

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-core/issues/1225
