### ISSUE TITLE
Home: Could not load installed platforms

### ISSUE THREAD

**Issue by LazosNalp** [platformio/platformio-core#1335]
PIO Core Call Error: Upon execvpe /home/lazos/.platformio/penv/bin/platformio ['/home/lazos/.platformio/penv/bin/platformio', 'platform', 'list', '--json-output'] in environment id 140079493572880
:Traceback (most recent call last):
  File "/home/lazos/.platformio/packages/contrib-pysite/twisted/internet/process.py", line 445, in _fork
    environment)
  File "/home/lazos/.platformio/packages/contrib-pysite/twisted/internet/process.py", line 523, in _execChild
    os.execvpe(executable, args, environment)
  File "/usr/lib/python2.7/os.py", line 355, in execvpe
    _execvpe(file, args, env)
  File "/usr/lib/python2.7/os.py", line 370, in _execvpe
    func(file, *argrest)
OSError: [Errno 2] No such file or directory

**Comment by ivankravets** [comment]
Have you modified Python installation? try to remove `/home/lazos/.platformio` folder and repeat.

**Comment by LazosNalp** [comment]
Thank you for reply. I've already fix it removing  /home/lazos/.platformio.
