### ISSUE TITLE
Home: Internal Store Exception

### ISSUE THREAD

**Issue by cpo** [platformio/platformio-core#1355]
TypeError: Cannot read property 'name' of null
    at http://127.0.0.1:8010/18cd4320383b16562325.min.js:11:33449
    at Array.map (native)
    at _ (http://127.0.0.1:8010/18cd4320383b16562325.min.js:11:33320)
    at http://127.0.0.1:8010/18cd4320383b16562325.min.js:11:33839
    at Array.map (native)
    at y (http://127.0.0.1:8010/18cd4320383b16562325.min.js:11:33779)
    at Function.a [as mapToProps] (http://127.0.0.1:8010/18cd4320383b16562325.min.js:25:401696)
    at r (http://127.0.0.1:8010/18cd4320383b16562325.min.js:6:10660)
    at l (http://127.0.0.1:8010/18cd4320383b16562325.min.js:6:12030)
    at c (http://127.0.0.1:8010/18cd4320383b16562325.min.js:6:12148)

**Comment by cpo** [comment]
OSX: 10.13.3
Code insiders: 1.20.0-insider
PlatformIO plugin: 0.12.1

This appears when opening the "new project" wizard.
