### ISSUE TITLE
Home: Internal Store Exception

### ISSUE THREAD

**Issue by frank3141** [platformio/platformio-core#1424]
Had to do a reformat, Win10 update issues, and reinstall everything.  This looks like an install issue.  Was trying to get an example program to test new install. Got this instead.
Using vscode 64 bit

TypeError: Cannot read property 'map' of undefined
    at http://127.0.0.1:8010/0237bd675d712281a0ee.min.js:39:332943
    at Array.map (native)
    at t.value (http://127.0.0.1:8010/0237bd675d712281a0ee.min.js:39:332640)
    at t.value (http://127.0.0.1:8010/0237bd675d712281a0ee.min.js:39:331547)
    at l (http://127.0.0.1:8010/0237bd675d712281a0ee.min.js:25:37163)
    at beginWork (http://127.0.0.1:8010/0237bd675d712281a0ee.min.js:25:38881)
    at a (http://127.0.0.1:8010/0237bd675d712281a0ee.min.js:25:51002)
    at o (http://127.0.0.1:8010/0237bd675d712281a0ee.min.js:25:51323)
    at s (http://127.0.0.1:8010/0237bd675d712281a0ee.min.js:25:51561)
    at E (http://127.0.0.1:8010/0237bd675d712281a0ee.min.js:25:55104)
    at _ (http://127.0.0.1:8010/0237bd675d712281a0ee.min.js:25:54841)
    at m (http://127.0.0.1:8010/0237bd675d712281a0ee.min.js:25:53969)

**Comment by frank3141** [comment]
Install issue, platform wasn't installed the first time i tried.  Didi a new project that did install the platform and then could import example code.
