### ISSUE TITLE
Home: Origin is not allowed by Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by DerFreie** [platformio/platformio-core#1426]
Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
    at c.crossDomainError (http://127.0.0.1:8010/0fe71ff5b710e32b7725.min.js:11:275801)
    at XMLHttpRequest.t.onreadystatechange (http://127.0.0.1:8010/0fe71ff5b710e32b7725.min.js:11:277008)

**Comment by ivankravets** [comment]
Could you reopen PIO  Home/ IDE?

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by ivankravets** [comment]
@ronyef Could you reproduce this issue again?
