### ISSUE TITLE
Home: Internal Store Exception

### ISSUE THREAD

**Issue by ilyary** [platformio/platformio-core#1427]
TypeError: Cannot read property 'name' of null
    at http://127.0.0.1:8010/0237bd675d712281a0ee.min.js:6:44845
    at Array.map (native)
    at b (http://127.0.0.1:8010/0237bd675d712281a0ee.min.js:6:44716)
    at http://127.0.0.1:8010/0237bd675d712281a0ee.min.js:6:45235
    at Array.map (native)
    at _ (http://127.0.0.1:8010/0237bd675d712281a0ee.min.js:6:45175)
    at Function.a [as mapToProps] (http://127.0.0.1:8010/0237bd675d712281a0ee.min.js:17:243549)
    at r (http://127.0.0.1:8010/0237bd675d712281a0ee.min.js:6:10153)
    at l (http://127.0.0.1:8010/0237bd675d712281a0ee.min.js:6:11523)
    at u (http://127.0.0.1:8010/0237bd675d712281a0ee.min.js:6:11641)

**Comment by ivankravets** [comment]
Could you reproduce this issue again?

**Comment by ilyary** [comment]
I've just installed atom and pio-ide.
The issue took place when I intended to create first project (NodeMCU,
Arduino). I pressed Create and got invite to send an issue. The project was
created anyway, and the ide went on working.

Another project was created without an issue. But I was prompted to update
the ide and accepted. So maybe I got a fix

Love platformio

Cheers,
Ilya


9 мар. 2018 г. 0:45 пользователь "Ivan Kravets" <notifications@github.com>
написал:

Could you reproduce this issue again?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/platformio/platformio-core/issues/1427#issuecomment-371635206>,
or mute the thread

**Comment by ivankravets** [comment]
Thanks! Don’t hesitate to reopen if you will catch this issue again.
