### ISSUE TITLE
no build possible for esp32 after update

### ISSUE THREAD

**Issue by trifeon** [platformio/platformio-core#1434]
What kind of issue is this?

- [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
      something, or to understand why something isn't working the way you expect it to, use
      our Community Forums https://community.platformio.org

- [ ] PlatformIO IDE. All issues related to PlatformIO IDE should be reported to appropriate repository
      https://github.com/platformio/platformio-atom-ide/issues

- [ ] Development Platform or Board. All issues related to Development Platforms or Embedded Boards
      should be reported to appropriate repository. 
      See full list with repositories and search for "platform-xxx" repository related to your hardware
      https://github.com/platformio?query=platform-

- [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [x ] PlatformIO Core. If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:
windows 10
**PlatformIO Version** (`platformio --version`):
3.5.2rc4
### Description of problem
after update platformio no build is possible, receive error message in pio 
rror: Traceback (most recent call last):
  File "c:\users\andreas\.platformio\penv\lib\site-packages\platformio\__main__.py", line 120, in main

    cli(None, None, None)
  File "c:\users\andreas\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\andreas\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\andreas\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\andreas\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\andreas\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\andreas\.platformio\penv\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\andreas\.platformio\penv\lib\site-packages\platformio\commands\run.py", line 121, in cli
    raise exception.ReturnErrorCode(1)
ReturnErrorCode: 1
 
#### Steps to Reproduce

1.restart pio after update with "restart" button
2.try to debug / build option
3.get the error message

### Actual Results
no build is possible

### Expected Results
build and upload is possible

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_f_cpu = 20000000L
build_flags = -fexceptions

```

**Source file to reproduce issue:**
```cpp
Insert here...
```

**Comment by trifeon** [comment]
Fixed, its a prob with lib.
