### ISSUE TITLE
Home: Error occurred while requesting content from http://dl.platformio.org/libraries/examples/0/75/blink2.ino

### ISSUE THREAD

**Issue by ronyef** [platformio/platformio-core#1545]
Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
    at c.crossDomainError (http://127.0.0.1:8010/1036863981806a753653.min.js:17:198456)
    at XMLHttpRequest.t.onreadystatechange (http://127.0.0.1:8010/1036863981806a753653.min.js:17:199663)

**Comment by ivankravets** [comment]
Please restart PIO IDE. All should work now.
