### ISSUE TITLE
Home: Libraries: Stats

### ISSUE THREAD

**Issue by bionaught** [platformio/platformio-core#1574]
PIO Core Call Error: Traceback (most recent call last):
  File "c:\users\grri0002\.platformio\penv\lib\site.py", line 703, in <module>
    main()
  File "c:\users\grri0002\.platformio\penv\lib\site.py", line 692, in main
    aliasmbcs()
  File "c:\users\grri0002\.platformio\penv\lib\site.py", line 515, in aliasmbcs
    import locale, codecs
  File "c:\users\grri0002\.platformio\penv\lib\locale.py", line 17, in <module>
    import functools
ImportError: No module named functools

**Comment by ivankravets** [comment]
Try to remove `c:\users\grri0002.platformio\penv` folder and restart IDE. Does it work?
