### ISSUE TITLE
Home: Error occurred while requesting content from http://dl.platformio.org/libraries/examples/5/576/CustomChars.pde

### ISSUE THREAD

**Issue by kkanedaa** [platformio/platformio-core#1576]
Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
    at c.crossDomainError (http://127.0.0.1:8010/8c486a994ab65f53b53c.min.js:17:182254)
    at XMLHttpRequest.t.onreadystatechange (http://127.0.0.1:8010/8c486a994ab65f53b53c.min.js:17:183461)

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1426
