### ISSUE TITLE
Uncaught Error: Could not start PIO Home server: Error: 

### ISSUE THREAD

**Issue by wegunterjr** [platformio/platformio-core#1601]
[Enter steps to reproduce:]

1. ...
2. ...opened platformIO arduino folder

**Atom**: 1.26.1 ia32
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.1.4

### Stack Trace

Uncaught Error: Could not start PIO Home server: Error: Traceback (most recent call last):
  File "main.py", line 128, in main.main
  File "C:\Users\gunterwe\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\gunterwe\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "C:\Users\gunterwe\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\gunterwe\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\gunterwe\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "cmd_home.py", line 822, in cmd_home.cli
  File "C:\Users\gunterwe\.platformio\packages\contrib-pysite\twisted\internet\posixbase.py", line 495, in listenTCP
    p.startListening()
  File "C:\Users\gunterwe\.platformio\packages\contrib-pysite\twisted\internet\tcp.py", line 980, in startListening
    raise CannotListenError(self.interface, self.port, le)
CannotListenError: Couldn't listen on 127.0.0.1:8010: [Errno 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted.

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to support@pioplus.com

============================================================

```
At C:\Users\gunterwe\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1617

Error: Could not start PIO Home server: Error: Traceback (most recent call last):
  File "main.py", line 128, in main.main
  File "C:\Users\gunterwe\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\gunterwe\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "C:\Users\gunterwe\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\gunterwe\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\gunterwe\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "cmd_home.py", line 822, in cmd_home.cli
  File "C:\Users\gunterwe\.platformio\packages\contrib-pysite\twisted\internet\posixbase.py", line 495, in listenTCP
    p.startListening()
  File "C:\Users\gunterwe\.platformio\packages\contrib-pysite\twisted\internet\tcp.py", line 980, in startListening
    raise CannotListenError(self.interface, self.port, le)
CannotListenError: Couldn't listen on 127.0.0.1:8010: [Errno 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted.

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to support@pioplus.com

============================================================


    at /packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1617:23
    at ChildProcess.onExit (/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:538:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at ChildProcess.cp.emit (/packages/platformio-ide/node_modules/cross-spawn/lib/enoent.js:34:29)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-clock 0.1.16 
atom-typescript 12.4.1 
autocomplete-clang 0.11.4 
build 0.70.0 
busy 0.7.0 
busy-signal 1.4.3 
file-icons 2.1.19 
gpp-compiler 3.0.7 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
platformio-ide 2.1.4 
platformio-ide-debugger 1.2.5 
platformio-ide-terminal 2.8.1 
sync-settings 0.8.6 
tablr 1.8.3 
tool-bar 1.1.7 
```

**Comment by ivankravets** [comment]
Could you reproduce this issue when restart IDE?

**Comment by ivankravets** [comment]
Please reopen if you still need help
