### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by mhelgers** [platformio/platformio-core#1607]
Error: Traceback (most recent call last):
  File "/Users/marc/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py", line 120, in main
    cli(None, None, None)
  File "/Users/marc/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/marc/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/marc/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/marc/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/marc/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/marc/.platformio/penv/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/marc/.platformio/penv/lib/python2.7/site-packages/platformio/commands/init.py", line 102, in cli
    pg = ProjectGenerator(project_dir, ide, env_name)
  File "/Users/marc/.platformio/penv/lib/python2.7/site-packages/platformio/ide/projectgenerator.py", line 35, in __init__
    self._gather_tplvars()
  File "/Users/marc/.platformio/penv/lib/python2.7/site-packages/platformio/ide/projectgenerator.py", line 150, in _gather_tplvars
    self._tplvars.update(self.get_project_env())
  File "/Users/marc/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 126, in wrapper
    self.cache[key] = (time.time(), func(*args, **kwargs))
  File "/Users/marc/.platformio/penv/lib/python2.7/site-packages/platformio/ide/projectgenerator.py", line 53, in get_project_env
    for k, v in config.items(section):
  File "/Users/marc/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 51, in items
    items.append((option, self.get(section, option)))
  File "/Users/marc/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 58, in get
    return self.VARTPL_RE.sub(self._re_sub_handler, value)
  File "/Users/marc/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 64, in _re_sub_handler
    return self.get(section, option)
  File "/Users/marc/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 55, in get
    value = ConfigParser.get(self, section, option, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'upload_port' in section: 'common'
============================================================
An unexpected error occurred. Further steps:
* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command
* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html
* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues
============================================================

**Comment by ivankravets** [comment]
NoOptionError: No option 'upload_port' in section: 'common'

Please fix `platformio.ini`
