### ISSUE TITLE
Running PIO on Centos: No encoding declared;

### ISSUE THREAD

**Issue by vsock** [platformio/platformio-core#1679]
### Configuration

**Operating system**:
   Static hostname: xyz
         Icon name: computer-desktop
           Chassis: desktop
        Machine ID: xxxx
           Boot ID: xxxx
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-862.3.2.el7.x86_64
      Architecture: x86-64

**PlatformIO Version** (`platformio --version`):
pio --version
PlatformIO, version 3.5.3

### Description of problem
Installed pio using 
was trying to initialize pio using "pio init" command failed.

How did i install:
python -m pip install platformio on centos
executed pio command with all aruguments throwing an error message execept for --version and platform command

[tester@xyz ~]$ pio platforms
Usage: pio platforms [OPTIONS] COMMAND [ARGS]...

Options:
  -h, --help  Show this message and exit.

Commands:
  frameworks  List supported frameworks, SDKs
  install     Install new development platform
  list        List installed development platforms
  search      Search for development platform
  show        Show details about development platform
  uninstall   Uninstall development platform
  update      Update installed development platforms

#### Steps to Reproduce

Install on Centos 
run pio --help or pio 

### Actual Results
pio init
Error: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/platformio/__main__.py", line 120, in main
    cli(None, None, None)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 679, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/python2.7/site-packages/click/core.py", line 594, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 989, in parse_args
    return Command.parse_args(self, ctx, args)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 858, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1362, in handle_parse_result
    self.callback, ctx, self, value)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 56, in invoke_param_callback
    return callback(ctx, param, value)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 787, in show_help
    echo(ctx.get_help(), color=ctx.color)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 469, in get_help
    return self.command.get_help(self)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 808, in get_help
    self.format_help(ctx, formatter)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 823, in format_help
    self.format_options(ctx, formatter)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 928, in format_options
    self.format_commands(ctx, formatter)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 973, in format_commands
    cmd = self.get_command(ctx, subcommand)
  File "/usr/lib/python2.7/site-packages/platformio/__main__.py", line 43, in get_command
    ["cli"])
  File "/usr/lib/python2.7/site-packages/platformio/commands/ci.py", line 24, in <module>
    from platformio.commands.init import cli as cmd_init
  File "/usr/lib/python2.7/site-packages/platformio/commands/init.py", line 26, in <module>
    from platformio.ide.projectgenerator import ProjectGenerator
  File "/usr/lib/python2.7/site-packages/platformio/ide/projectgenerator.py", line 24, in <module>
    from platformio.commands.run import cli as cmd_run
  File "/usr/lib/python2.7/site-packages/platformio/commands/run.py", line 24, in <module>
    from platformio.commands.device import device_monitor as cmd_device_monitor
  File "/usr/lib/python2.7/site-packages/platformio/commands/device.py", line 20, in <module>
    from serial.tools import miniterm
  File "/usr/lib/python2.7/site-packages/serial/__init__.py", line 17, in <module>
    from serial import errors, utilities, properties, meta, hooks, test, model, request
  File "/usr/lib/python2.7/site-packages/serial/hooks.py", line 15, in <module>
    from serial import model
  File "/usr/lib/python2.7/site-packages/serial/model.py", line 221
SyntaxError: Non-ASCII character '\xe2' in file /usr/lib/python2.7/site-packages/serial/model.py on line 221, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

### Expected Results

Run pio commands successfully

**Comment by ivankravets** [comment]
Please move this issue to https://github.com/pyserial/pyserial/issues

P.S: Also, please try installing PIO in `virtualenv`.
