### ISSUE TITLE
Home: Error occurred while requesting content from http://dl.platformio.org/libraries/examples/1/135/ssd1306_128x32_i2c.ino

### ISSUE THREAD

**Issue by pankaj151** [platformio/platformio-core#1730]
Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
    at c.crossDomainError (http://127.0.0.1:8010/d7e69906dadeacfea693.min.js:17:185763)
    at XMLHttpRequest.c._end.t.onreadystatechange (http://127.0.0.1:8010/d7e69906dadeacfea693.min.js:17:186970)

**Comment by ivankravets** [comment]
Fixed in the upcoming PIO Home 0.9.7
