### ISSUE TITLE
Home: Platforms: Frameworks

### ISSUE THREAD

**Issue by 1330154737** [platformio/platformio-core#1745]
PIO Core Call Error: Error: Traceback (most recent call last):
  File "c:\cadence\cadence\spb_data\.platformio\penv\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\cadence\cadence\spb_data\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\cadence\cadence\spb_data\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\cadence\cadence\spb_data\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\cadence\cadence\spb_data\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\cadence\cadence\spb_data\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\cadence\cadence\spb_data\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\cadence\cadence\spb_data\.platformio\penv\lib\site-packages\platformio\commands\platform.py", line 192, in platform_frameworks
    for framework in util.get_api_result("/frameworks", cache_valid="7d"):
  File "c:\cadence\cadence\spb_data\.platformio\penv\lib\site-packages\platformio\util.py", line 650, in get_api_result
    cc.set(cache_key, result, cache_valid)
  File "c:\cadence\cadence\spb_data\.platformio\penv\lib\site-packages\platformio\app.py", line 203, in set
    os.makedirs(self.cache_dir)
  File "c:\cadence\cadence\spb_data\.platformio\penv\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 183] : 'C:\\Cadence\\Cadence\\SPB_Data\\.platformio\\.cache'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
Please remove this folder `'C:\Cadence\Cadence\SPB_Data\.platformio\.cache` manually. Something went wrong with permissions.
