### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by Sobollion** [platformio/platformio-core#1759]
PIO Core Call Error: The next files/directories have been created in C:\Users\user\Documents\PlatformIO\Projects\Interactive_stuff
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: Unknown board ID 'nanoatmega328'

**Comment by Sobollion** [comment]
PIO Core Call Error: PlatformManager: Installing atmelavr
 Downloading...
 Unpacking...
 atmelavr @ 1.9.0 has been successfully installed!
 PackageManager: Installing toolchain-atmelavr @ ~1.40902.0

 toolchain-atmelavr @ 1.40902.1 is already installed
 Uninstalling framework-arduinoavr @ 1.10620.2: Please manually remove file `C:\Users\user\.platformio\packages\framework-arduinoavr\libraries\WiFi\extras\wifiHD\src\SOFTWARE_FRAMEWORK\DRIVERS\CPU`
 Error: Traceback (most recent call last):
 File "c:\users\user\.platformio\penv\lib\site-packages\platformio\__main__.py", line 120, in main
 cli(None, None, None)
 File "c:\users\user\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
 return self.main(*args, **kwargs)
 File "c:\users\user\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
 rv = self.invoke(ctx)
 File "c:\users\user\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
 return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "c:\users\user\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
 return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "c:\users\user\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
 return ctx.invoke(self.callback, **ctx.params)
 File "c:\users\user\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
 return callback(*args, **kwargs)
 File "c:\users\user\.platformio\penv\lib\site-packages\platformio\commands\platform.py", line 313, in platform_install
 force=force):
 File "c:\users\user\.platformio\penv\lib\site-packages\platformio\managers\platform.py", line 84, in install
 return self.cleanup_packages(p.packages.keys())
 File "c:\users\user\.platformio\penv\lib\site-packages\platformio\managers\platform.py", line 157, in cleanup_packages
 pm.uninstall(manifest['__pkg_dir'], after_update=True)
 File "c:\users\user\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 768, in uninstall
 util.rmtree_(pkg_dir)
 File "c:\users\user\.platformio\penv\lib\site-packages\platformio\util.py", line 793, in rmtree_
 return rmtree(path, onerror=_onerror)
 File "C:\Python27\Lib\shutil.py", line 247, in rmtree
 rmtree(fullname, ignore_errors, onerror)
 File "C:\Python27\Lib\shutil.py", line 247, in rmtree
 rmtree(fullname, ignore_errors, onerror)
 File "C:\Python27\Lib\shutil.py", line 247, in rmtree
 rmtree(fullname, ignore_errors, onerror)
 File "C:\Python27\Lib\shutil.py", line 247, in rmtree
 rmtree(fullname, ignore_errors, onerror)
 File "C:\Python27\Lib\shutil.py", line 247, in rmtree
 rmtree(fullname, ignore_errors, onerror)
 File "C:\Python27\Lib\shutil.py", line 247, in rmtree
 rmtree(fullname, ignore_errors, onerror)
 File "C:\Python27\Lib\shutil.py", line 247, in rmtree
 rmtree(fullname, ignore_errors, onerror)
 File "C:\Python27\Lib\shutil.py", line 247, in rmtree
 rmtree(fullname, ignore_errors, onerror)
 File "C:\Python27\Lib\shutil.py", line 256, in rmtree
 onerror(os.rmdir, path, sys.exc_info())
 File "c:\users\user\.platformio\penv\lib\site-packages\platformio\util.py", line 791, in _onerror
 raise e
 WindowsError: [Error 5] : 'C:\\Users\\user\\.platformio\\packages\\framework-arduinoavr\\libraries\\WiFi\\extras\\wifiHD\\src\\SOFTWARE_FRAMEWORK\\DRIVERS\\CPU'
 
 ============================================================
 
 An unexpected error occurred. Further steps:
 
 * Verify that you have the latest version of PlatformIO using
 `pip install -U platformio` command
 
 * Try to find answer in FAQ Troubleshooting section
 http://docs.platformio.org/page/faq.html
 
 * Report this problem to the developers
 https://github.com/platformio/platformio-core/issues
 
 ============================================================
Report a problem
