### ISSUE TITLE
Issue when trying to use master branch of esp-idf 

### ISSUE THREAD

**Issue by wegunterjr** [platformio/platformio-core#1808]
`You're up-to-date!
PlatformIO 3.6.0 is currently the newest version available.`

I was using the version of esp-idf available in platformio, but ran into an issue with this:

`error: implicit declaration of function 'esp_err_to_name'`

This was not an issue with esp-idf and was able to be built and run on the WROVER32.  I tried it here, but gave me the above error.    

Platform Manager
================
Platform esp-idf
--------
```
Error: Traceback (most recent call last):
  File "c:\users\newman\.platformio\penv\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\users\newman\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\newman\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\newman\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\newman\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\newman\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\newman\.platformio\penv\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\newman\.platformio\penv\lib\site-packages\platformio\commands\update.py", line 46, in cli
    ctx.invoke(cmd_platform_update, only_check=only_check)
  File "c:\users\newman\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\newman\.platformio\penv\lib\site-packages\platformio\commands\platform.py", line 385, in platform_update
    platform, only_packages=only_packages, only_check=only_check)
  File "c:\users\newman\.platformio\penv\lib\site-packages\platformio\managers\platform.py", line 121, in update
    p = PlatformFactory.newPlatform(pkg_dir)
  File "c:\users\newman\.platformio\penv\lib\site-packages\platformio\managers\platform.py", line 250, in newPlatform
    _instance = platform_cls(join(platform_dir, "platform.json"))
  File "c:\users\newman\.platformio\penv\lib\site-packages\platformio\managers\platform.py", line 460, in __init__
    self._manifest = util.load_json(manifest_path)
  File "c:\users\newman\.platformio\penv\lib\site-packages\platformio\util.py", line 180, in load_json
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\newman\\.platformio\\platforms\\esp-idf\\platform.json'
```

**Comment by ivankravets** [comment]
We don't support non-released software.

**Comment by wegunterjr** [comment]
Is the latest 3.0 or 3.1?

**Comment by ivankravets** [comment]
The latest stable is 3.0.3, see https://github.com/espressif/esp-idf/tags

**Comment by wegunterjr** [comment]
So, there are 
Platforms, Frameworks, and Boards
Platforms - is this where I get the stable 3.0.3 when I install the Espressif32?
I see ESP IDf listed in packages, but can't see any information about it.

![image](https://user-images.githubusercontent.com/624637/44746971-29b9f000-aac9-11e8-8d42-1f72aa296b7b.png)

**Comment by wegunterjr** [comment]
I am using the current available in PlatformIO and getting strange errors:
```
Compiling .pioenvs\esp-wrover16\aws_iot\aws-iot-device-sdk-embedded-C\src\aws_iot_shadow_json.o
C:\Users\newman\.platformio\packages\framework-espidf\components\aws_iot\aws-iot-device-sdk-embedded-C\src\aws_iot_mqtt_client_common_internal.c: In function 'aws_iot_mqtt_internal_write_len_to_buffer':
C:\Users\newman\.platformio\packages\framework-espidf\components\aws_iot\aws-iot-device-sdk-embedded-C\src\aws_iot_mqtt_client_common_internal.c:60:2: error: 'FUNC_ENTRY' undeclared (first use in this function)
FUNC_ENTRY;

```
![image](https://user-images.githubusercontent.com/624637/44747186-cc726e80-aac9-11e8-9f53-ae69da1cbf34.png)
