### ISSUE TITLE
Wont compile

### ISSUE THREAD

**Issue by charliewindsor007** [platformio/platformio-core#1829]
What kind of issue is this?
Processing megaatmega2560 (platform: atmelavr; board: megaatmega2560; framework: arduino)

LibraryManager: Installing 30aa480

Downloading  [------------------------------------]    0%
Downloading  [------------------------------------]    0%
Downloading  [##----------------------------------]    6%
Downloading  [####--------------------------------]   12%
Downloading  [######------------------------------]   18%
Downloading  [#########---------------------------]   25%
Downloading  [###########-------------------------]   31%
Downloading  [#############-----------------------]   37%
Downloading  [###############---------------------]   43%
Downloading  [##################------------------]   50%
Downloading  [####################----------------]   56%
Downloading  [######################--------------]   62%
Downloading  [########################------------]   68%
Downloading  [###########################---------]   75%
Downloading  [#############################-------]   81%
Downloading  [###############################-----]   87%
Downloading  [#################################---]   93%
Downloading  [####################################]  100%
Downloading  [####################################]  100%

Unpacking  [------------------------------------]    0%
Unpacking  [------------------------------------]    0%
Unpacking  [##----------------------------------]    7%
Unpacking  [#####-------------------------------]   15%
Unpacking  [########----------------------------]   23%
Unpacking  [###########-------------------------]   30%
Unpacking  [#############-----------------------]   38%
Unpacking  [################--------------------]   46%
Unpacking  [###################-----------------]   53%
Unpacking  [######################--------------]   61%
Unpacking...
Error: Traceback (most recent call last):
  File "c:\users\charle's laptop\.platformio\python27\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\users\charle's laptop\.platformio\python27\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\charle's laptop\.platformio\python27\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\charle's laptop\.platformio\python27\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\charle's laptop\.platformio\python27\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\charle's laptop\.platformio\python27\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\charle's laptop\.platformio\python27\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\charle's laptop\.platformio\python27\lib\site-packages\platformio\commands\run.py", line 107, in cli
    result = (envname, ep.process())
  File "c:\users\charle's laptop\.platformio\python27\lib\site-packages\platformio\commands\run.py", line 205, in process
    result = self._run()
  File "c:\users\charle's laptop\.platformio\python27\lib\site-packages\platformio\commands\run.py", line 300, in _run
    self.verbose)
  File "c:\users\charle's laptop\.platformio\python27\lib\site-packages\platformio\commands\run.py", line 323, in _autoinstall_libdeps
    ctx.invoke(cmd_lib_install, libraries=[lib], silent=not verbose)
  File "c:\users\charle's laptop\.platformio\python27\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\charle's laptop\.platformio\python27\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "c:\users\charle's laptop\.platformio\python27\lib\site-packages\platformio\commands\lib.py", line 103, in lib_install
    library, silent=silent, interactive=interactive, force=force)
  File "c:\users\charle's laptop\.platformio\python27\lib\site-packages\platformio\managers\lib.py", line 354, in install
    force=force)
  File "c:\users\charle's laptop\.platformio\python27\lib\site-packages\platformio\managers\package.py", line 718, in install
    name, url, requirements, track=True)
  File "c:\users\charle's laptop\.platformio\python27\lib\site-packages\platformio\managers\package.py", line 444, in _install_from_url
    self.unpack(dlpath, tmp_dir)
  File "c:\users\charle's laptop\.platformio\python27\lib\site-packages\platformio\managers\package.py", line 224, in unpack
    return fu.unpack(dest_dir, with_progress=False)
  File "c:\users\charle's laptop\.platformio\python27\lib\site-packages\platformio\unpacker.py", line 112, in unpack
    self._unpacker.extract_item(item, dest_dir)
  File "c:\users\charle's laptop\.platformio\python27\lib\site-packages\platformio\unpacker.py", line 38, in extract_item
    self._afo.extract(item, dest_dir)
  File "c:\users\charle's laptop\.platformio\python27\lib\zipfile.py", line 1028, in extract
    return self._extract_member(member, path, pwd)
  File "c:\users\charle's laptop\.platformio\python27\lib\zipfile.py", line 1083, in _extract_member
    file(targetpath, "wb") as target:
IOError: [Errno 2] No such file or directory: "C:\\Users\\Charle's Laptop\\Downloads\\Marlin-1.1.x\\Marlin-1.1.x\\Marlin\\example_configurations\\Geeetech\\I3_Pro_X-GT2560\\Marlin\\.piolibdeps\\_tmp_installing-lsneav-package\\LiquidTWI2-30aa480782053c7ffd301031e8809a98a2eb063f\\examples\\HelloWorld_i2c\\HelloWorld_i2c.ino"

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [ ] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:

**PlatformIO Version** (`platformio --version`):

#### Steps to Reproduce

1.
2.
3.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
Insert here...
```

**Source file to reproduce issue:**
```cpp
Insert here...
```

**Comment by ivankravets** [comment]
Please provide content of `platformio.ini`.

**Comment by ivankravets** [comment]
Please reopen if you still need help
