### ISSUE TITLE
Home: Could not load installed platforms

### ISSUE THREAD

**Issue by kolergy** [platformio/platformio-core#1919]
PIO Core Call Error: Upon execvpe /home/jmi/.platformio/penv/bin/platformio ['/home/jmi/.platformio/penv/bin/platformio', 'platform', 'list', '--json-output'] in environment id 139948322097144
:Traceback (most recent call last):
  File "/home/jmi/.platformio/packages/contrib-pysite/twisted/internet/process.py", line 445, in _fork
    environment)
  File "/home/jmi/.platformio/packages/contrib-pysite/twisted/internet/process.py", line 523, in _execChild
    os.execvpe(executable, args, environment)
  File "/usr/lib/python2.7/os.py", line 355, in execvpe
    _execvpe(file, args, env)
  File "/usr/lib/python2.7/os.py", line 370, in _execvpe
    func(file, *argrest)
OSError: [Errno 2] No such file or directory

**Comment by ivankravets** [comment]
Please remove `/home/jmi/.platformio/penv` folder and restart IDE.
