### ISSUE TITLE
many errors on command pip --help

### ISSUE THREAD

**Issue by Rothammel** [platformio/platformio-core#1996]
What kind of issue is this?

- [*] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

### Configuration

**Operating system**:
windows xp home edition 2002 sp3

**PlatformIO Version** (`platformio --version`):
PlatformIO, version 3.6.3

### Description of problem
on command pio --help i have many errors:

Error: Traceback (most recent call last):
  File "c:\python27\lib\site-packages\platformio\__main__.py", line 120, in main cli(None, None, None)
  File "c:\python27\lib\site-packages\click\core.py", line 700, in __call__    return self.main(*args, *kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 679, in main with self.make_context(prog_name, args, **extra) as ctx:
  File "c:\python27\lib\site-packages\click\core.py", line 594, in make_context self.parse_args(ctx, args)
  File "c:\python27\lib\site-packages\click\core.py", line 989, in parse_args return Command.parse_args(self, ctx, args)
  File "c:\python27\lib\site-packages\click\core.py", line 858, in parse_args value, args = param.handle_parse_result(ctx, opts, args)
  File "c:\python27\lib\site-packages\click\core.py", line 1362, in handle_parse_result
    self.callback, ctx, self, value)
  File "c:\python27\lib\site-packages\click\core.py", line 56, in invoke_param_callback
    return callback(ctx, param, value)
  File "c:\python27\lib\site-packages\click\core.py", line 787, in show_help echo(ctx.get_help(), color=ctx.color)
  File "c:\python27\lib\site-packages\click\core.py", line 469, in get_help return self.command.get_help(self)
  File "c:\python27\lib\site-packages\click\core.py", line 808, in get_help self.format_help(ctx, formatter)
  File "c:\python27\lib\site-packages\click\core.py", line 823, in format_help self.format_options(ctx, formatter)
  File "c:\python27\lib\site-packages\click\core.py", line 928, in format_options
    self.format_commands(ctx, formatter)
  File "c:\python27\lib\site-packages\click\core.py", line 973, in format_commands
    cmd = self.get_command(ctx, subcommand)
  File "c:\python27\lib\site-packages\platformio\__main__.py", line 43, in get_command
    ["cli"])
  File "c:\python27\lib\site-packages\platformio\commands\ci.py", line 24, in <module>
    from platformio.commands.init import cli as cmd_init
  File "c:\python27\lib\site-packages\platformio\commands\init.py", line 26, in<module>
    from platformio.ide.projectgenerator import ProjectGenerator
  File "c:\python27\lib\site-packages\platformio\ide\projectgenerator.py", line 24, in <module>
    from platformio.commands.run import cli as cmd_run
  File "c:\python27\lib\site-packages\platformio\commands\run.py", line 23, in <module>
    from platformio.commands.device import device_monitor as cmd_device_monitor
  File "c:\python27\lib\site-packages\platformio\commands\device.py", line 20, in <module>
    from serial.tools import miniterm
  File "c:\python27\lib\site-packages\serial\__init__.py", line 27, in <module> from serial.serialwin32 import Serial
  File "c:\python27\lib\site-packages\serial\serialwin32.py", line 15, in <module>
    from serial import win32
  File "c:\python27\lib\site-packages\serial\win32.py", line 182, in <module> CancelIoEx = _stdcall_libraries['kernel32'].CancelIoEx
  File "c:\python27\lib\ctypes\__init__.py", line 379, in __getattr__ func = self.__getitem__(name)
  File "c:\python27\lib\ctypes\__init__.py", line 384, in __getitem__ func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'CancelIoEx' not found
============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
Could you provide an output from `c:\python27 --version`?

**Comment by Rothammel** [comment]
No, sorry but I have install lubunto on this old machine and it works. Windows XP is slow and old.Am 09.01.2019 13:46 schrieb Ivan Kravets <notifications@github.com>:Could you provide an output from c:\python27 --version?

**Comment by ivankravets** [comment]
Thanks!
