### ISSUE TITLE
Error when using AutoDetectUploadPort feature on 4.0.0a1 using Python 3

### ISSUE THREAD

**Issue by meltdown03** [platformio/platformio-core#2000]
**PlatformIO Core** - Develop Branch
Using Python 3.7, Git file: **_platformio-core/platformio/util.py_**
Error line 825 util.py: startswith must begin with bytes or tuple, not str

**Recreate Issue:** Do Not set upload_port in platformio.ini file

**My fix:** open file as "r" instead of "rb" on line 822 like this:
`with open(rules_path, "r") as fp:`

**_Alternatively_**, change line 825: 
`if not line or line.startswith("#"):`
to
` if not line or line.startswith(bytes("#", "utf8")):`

**Full Error when uploading:**
Looking for upload port...
*** [upload] TypeError : startswith first arg must be bytes or a tuple of bytes, not str
Traceback (most recent call last):
File "/home/neal/.platformio/packages/tool-scons/script/../engine/SCons/Action.py", line 1203, in execute
result = self.execfunction(target=target, source=rsources, env=env)
File "/home/neal/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py", line 224, in __call__
return self.method(*nargs, **kwargs)
File "/home/neal/platformio-core/platformio/builder/tools/pioupload.py", line 158, in AutodetectUploadPort
util.ensure_udev_rules()
File "/home/neal/platformio-core/platformio/util.py", line 844, in ensure_udev_rules
origin_rules = _rules_to_set(origin_path)
File "/home/neal/platformio-core/platformio/util.py", line 825, in _rules_to_set
if not line or line.startswith("#"):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

**Comment by ivankravets** [comment]
Please re-run `pio upgrade --dev` and retest.

Thanks!
