### ISSUE TITLE
Home: Internal Store Exception

### ISSUE THREAD

**Issue by michkrom** [platformio/platformio-core#2033]
TypeError: Cannot read property 'toUpperCase' of undefined
    at Object.t.title (http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:12:21892)
    at http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:12:65718
    at Array.map (<anonymous>)
    at w (http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:12:65694)
    at http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:12:61851
    at Array.map (<anonymous>)
    at t.selectNormalizedBoards (http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:12:61745)
    at Function.t.default.e.osOpenUrl [as mapToProps] (http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:63:90515)
    at r (http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:12:17716)
    at m (http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:12:18977)

**Comment by ivankravets** [comment]
Could you provide more details on how to reproduce this issue?

**Comment by ivankravets** [comment]
Please reopen if you still need help
