### ISSUE TITLE
Home: Internal Store Exception

### ISSUE THREAD

**Issue by Wooopz** [platformio/platformio-core#2041]
Error: marked(): input parameter is undefined or null
    at E (http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:63:1002440)
    at http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:24:219612
    at Array.map (<anonymous>)
    at t.value (http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:24:219193)
    at li (http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:40:59752)
    at si (http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:40:59547)
    at pi (http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:40:63224)
    at qi (http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:40:78336)
    at Wi (http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:40:78713)
    at Ao (http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:40:85136)

**Comment by ivankravets** [comment]
Could you provide more details on how to reproduce this issue?

**Comment by ivankravets** [comment]
Please reopen if you still need help
