### ISSUE TITLE
CI: SameFileError

### ISSUE THREAD

**Issue by gepd** [platformio/platformio-core#2227]
### Configuration

**Operating system**: Windows 10

**PlatformIO Version** (`platformio --version`): 4.0.0a5

### Description of problem

When you run a command like this:

`pio ci -b uno --build-dir C:\Users\ll\Desktop\test --keep-build-dir C:\Users\ll\Desktop\test\src\test.ino` you get `SameFileError`

#### Steps to Reproduce

1. Set a file from inside of the `build-dir` as `SRC`
2. Run the command

### Actual Results

```
Error: Traceback (most recent call last):
  File "c:\users\ll\appdata\local\programs\python\python37-32\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\users\ll\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\ll\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\ll\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\ll\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\ll\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\ll\appdata\local\programs\python\python37-32\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\ll\appdata\local\programs\python\python37-32\lib\site-packages\platformio\commands\ci.py", line 98, in cli
    _copy_contents(join(build_dir, dir_name), contents)
  File "c:\users\ll\appdata\local\programs\python\python37-32\lib\site-packages\platformio\commands\ci.py", line 148, in _copy_contents
    copyfile(f, join(dst_dir, basename(f)))
  File "c:\users\ll\appdata\local\programs\python\python37-32\lib\shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: 'C:\\Users\\ll\\Desktop\\test\\src\\test.ino' and 'C:\\Users\\ll\\Desktop\\test\\src\\test.ino' are the same file

```

### Expected Results

Would be good if PlatformIO doesn't try copy the file and just runs the command or just display a friendly error.

But I would expect the first solution. It's good to use `platformio ci` to compile a project already initialized without touch the `platformio.ini` (using `--project-option`)

**Comment by ivankravets** [comment]
Thanks! Please re-test with `pio upgrade --dev`.
