### ISSUE TITLE
CLI failed to start

### ISSUE THREAD

**Issue by denxhun** [platformio/platformio-core#2472]
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: Microsoft Windows [Version 10.0.17763.437]
**PlatformIO Version** (`platformio --version`): PlatformIO, version 4.0.0a11

### Description of problem
In the IDE (Atom) the terminal drops error on startup.

#### Steps to Reproduce

1. Open the Atom
2. Click the "Terminal" button

### Actual Results
`Error: Traceback (most recent call last):
  File "c:\users\user_name\.platformio\penv\lib\site-packages\platformio\__main__.py", line 84, in main
    cli(None, None, None)
  File "c:\users\user_name\.platformio\penv\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\user_name\.platformio\penv\lib\site-packages\click\core.py", line 716, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "c:\users\user_name\.platformio\penv\lib\site-packages\click\core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "c:\users\user_name\.platformio\penv\lib\site-packages\click\core.py", line 1089, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "c:\users\user_name\.platformio\penv\lib\site-packages\click\core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "c:\users\user_name\.platformio\penv\lib\site-packages\click\core.py", line 1477, in handle_parse_result
    self.callback, ctx, self, value)
  File "c:\users\user_name\.platformio\penv\lib\site-packages\click\core.py", line 96, in invoke_param_callback
    return callback(ctx, param, value)
  File "c:\users\user_name\.platformio\penv\lib\site-packages\click\core.py", line 860, in show_help
    echo(ctx.get_help(), color=ctx.color)
  File "c:\users\user_name\.platformio\penv\lib\site-packages\click\core.py", line 516, in get_help
    return self.command.get_help(self)
  File "c:\users\user_name\.platformio\penv\lib\site-packages\click\core.py", line 879, in get_help
    self.format_help(ctx, formatter)
  File "c:\users\user_name\.platformio\penv\lib\site-packages\click\core.py", line 898, in format_help
    self.format_options(ctx, formatter)
  File "c:\users\user_name\.platformio\penv\lib\site-packages\click\core.py", line 1017, in format_options
    self.format_commands(ctx, formatter)
  File "c:\users\user_name\.platformio\penv\lib\site-packages\click\core.py", line 1061, in format_commands
    for subcommand in self.list_commands(ctx):
  File "c:\users\user_name\.platformio\penv\lib\site-packages\platformio\commands\__init__.py", line 33, in list_commands
    for filename in os.listdir(join(dirname(__file__), "commands")):
WindowsError: [Error 3] The system cannot find the path specified: 'c:\\users\\user_name\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\commands/*.*'`

### Expected Results
Shows the "pio --help" command's output properly.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
Insert here...
```

**Source file to reproduce issue:**
```cpp
Insert here...
```

### Additional info
I've placed a comment where I suspect the issue:
[commit](https://github.com/platformio/platformio-core/commit/62b80c396bc2eb669430acb41b55f9fecb8a4283)

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-core/commit/32d317d3cb9d6ab3a07f65ed4e0e6bd75f2a14f9

Please re-run `pio upgrade --dev`.
