### ISSUE TITLE
Cannot use a specific git commit

### ISSUE THREAD

**Issue by szmolnar** [platformio/platformio-core#2808]
### Configuration

**Operating system**:macOS High Sierra

**PlatformIO Version** (`PlatformIO, version 4.0.0`):

### Description of problem
Cannot use a specific git commit

#### Steps to Reproduce

try using a specific git commit 

### Actual Results
Processing specific_git_commit (framework: arduino; board: lolin32; platform: https://github.com/espressif/arduino-esp32.git#a38ffe58fe1d73a56295edb0c6051a46932e0175)
-------------------------------------------------------------------------------------------------------------------------------------------------
Error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/platformio/__main__.py", line 88, in main
    cli(None, None, None)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/platformio/commands/__init__.py", line 37, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/platformio/commands/run/command.py", line 112, in cli
    result = (envname, ep.process())
  File "/usr/local/lib/python2.7/site-packages/platformio/commands/run/processor.py", line 62, in process
    result = self._run_platform()
  File "/usr/local/lib/python2.7/site-packages/platformio/commands/run/processor.py", line 109, in _run_platform
    p = PlatformFactory.newPlatform(self.options['platform'])
  File "/usr/local/lib/python2.7/site-packages/platformio/managers/platform.py", line 260, in newPlatform
    _instance = platform_cls(join(platform_dir, "platform.json"))
  File "/usr/local/lib/python2.7/site-packages/platformio/managers/platform.py", line 497, in __init__
    self._manifest = util.load_json(manifest_path)
  File "/usr/local/lib/python2.7/site-packages/platformio/util.py", line 124, in load_json
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: '/Users/szmolnar/.platformio/platforms/arduino-esp32/platform.json'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.

### Expected Results
should compile

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:specific_git_commit]
;platform = espressif32
board = lolin32
framework = arduino
platform= https://github.com/espressif/arduino-esp32.git#a38ffe58fe1d73a56295edb0c6051a46932e0175

monitor_speed = 115200

lib_deps=
    PubSubClient@2.7
```

**Comment by ivankravets** [comment]
http://docs.platformio.org/en/latest/platforms/espressif32.html#using-arduino-framework-with-staging-version
