### ISSUE TITLE
Home: Internal Store Exception

### ISSUE THREAD

**Issue by antoniomolram** [platformio/platformio-core#2939]
TypeError: Cannot read property 'length' of null
    at w (http://127.0.0.1:8010/16b7c663df4028997b59.min.js:12:62996)
    at http://127.0.0.1:8010/16b7c663df4028997b59.min.js:12:60465
    at Array.map (<anonymous>)
    at t.selectPlatformData (http://127.0.0.1:8010/16b7c663df4028997b59.min.js:12:60385)
    at Function.t.default.osOpenUrl [as mapToProps] (http://127.0.0.1:8010/16b7c663df4028997b59.min.js:64:1095312)
    at r (http://127.0.0.1:8010/16b7c663df4028997b59.min.js:12:17335)
    at m (http://127.0.0.1:8010/16b7c663df4028997b59.min.js:12:18606)
    at http://127.0.0.1:8010/16b7c663df4028997b59.min.js:12:18678
    at Object.run (http://127.0.0.1:8010/16b7c663df4028997b59.min.js:12:15280)
    at s.l.onStateChange (http://127.0.0.1:8010/16b7c663df4028997b59.min.js:12:15756)

**Comment by ivankravets** [comment]
Could you reproduce this issue when restarting VSCode?

**Comment by ivankravets** [comment]
Please reopen if you still need help
