### ISSUE TITLE
Home: Libraries: Could not uninstall library

### ISSUE THREAD

**Issue by gurues** [platformio/platformio-core#3039]
TypeError: v.entities[T].find is not a function
    at http://127.0.0.1:8010/ade70d3ca408ebd72179.min.js:49:52554
    at y (http://127.0.0.1:8010/ade70d3ca408ebd72179.min.js:42:514026)
    at Generator._invoke (http://127.0.0.1:8010/ade70d3ca408ebd72179.min.js:42:513814)
    at Generator.e.(anonymous function) [as next] (http://127.0.0.1:8010/ade70d3ca408ebd72179.min.js:42:514205)
    at D (http://127.0.0.1:8010/ade70d3ca408ebd72179.min.js:57:1251652)
    at b (http://127.0.0.1:8010/ade70d3ca408ebd72179.min.js:57:1252489)
    at http://127.0.0.1:8010/ade70d3ca408ebd72179.min.js:57:1254436
    at k (http://127.0.0.1:8010/ade70d3ca408ebd72179.min.js:57:1254459)
    at D (http://127.0.0.1:8010/ade70d3ca408ebd72179.min.js:57:1251712)
    at Object.b [as cont] (http://127.0.0.1:8010/ade70d3ca408ebd72179.min.js:57:1252489)

**Comment by gurues** [comment]
The library is not compatible with framework. My mistake
