### ISSUE TITLE
build stopped working after upgrade to latest PlatformIO under VSCode

### ISSUE THREAD

**Issue by fmuntean** [platformio/platformio-core#3172]
Platform IO Extension 1.9.2 Core 4.0.3

Processing mfd_NodeMCU_09 (platform: None; framework: arduino; board: nodemcu)
-----------------------------------------------------------------------------------------------------------------------------------------
Error: Traceback (most recent call last):
  File "c:\users\fmunt\.platformio\penv\lib\site-packages\platformio\__main__.py", line 90, in main
    cli(None, None, None)
  File "c:\users\fmunt\.platformio\penv\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\fmunt\.platformio\penv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\fmunt\.platformio\penv\lib\site-packages\platformio\commands\__init__.py", line 37, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "c:\users\fmunt\.platformio\penv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\fmunt\.platformio\penv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\fmunt\.platformio\penv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\fmunt\.platformio\penv\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\fmunt\.platformio\penv\lib\site-packages\platformio\commands\run\command.py", line 115, in cli
    silent, verbose, jobs, is_test_running))
  File "c:\users\fmunt\.platformio\penv\lib\site-packages\platformio\commands\run\command.py", line 135, in process_env
    result = {"env": name, "duration": time(), "succeeded": ep.process()}
  File "c:\users\fmunt\.platformio\penv\lib\site-packages\platformio\commands\run\processor.py", line 70, in process
    p = PlatformFactory.newPlatform(self.options['platform'])
  File "c:\users\fmunt\.platformio\penv\lib\site-packages\platformio\managers\platform.py", line 235, in newPlatform
    if isdir(name):
TypeError: _isdir: path should be string, bytes or os.PathLike, not NoneType

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

The terminal process terminated with exit code: 1

**Comment by ivankravets** [comment]
>  (platform: None;

Please fix your `platformio.ini`.
