### ISSUE TITLE
Build Error after the Win10 updated with ESP32

### ISSUE THREAD

**Issue by evanwu02** [platformio/platformio-core#3278]
### Configuration

**Operating system**: Win10

**PlatformIO Version** (`platformio --version`): PlatformIO, version 4.1.0

**PlatformIO IDE Version**: 1.9.3 (2019-10-29)

### Description of problem
I used the ESP32-PICO32-D4 with VSCODE IDE in the ESP-IDF platform and build host is Win10. After the Win10 updated yesterday, VSCODE have the build error as Additional info:

### Additional info
Processing pico32 (platform: espressif32; board: pico32; framework: espidf)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Error: Traceback (most recent call last):
  File "c:\users\evan\.platformio\penv\lib\site-packages\platformio\__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "c:\users\evan\.platformio\penv\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\evan\.platformio\penv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\evan\.platformio\penv\lib\site-packages\platformio\commands\__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "c:\users\evan\.platformio\penv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\evan\.platformio\penv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\evan\.platformio\penv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\evan\.platformio\penv\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\evan\.platformio\penv\lib\site-packages\platformio\commands\run\command.py", line 138, in cli
    is_test_running,
  File "c:\users\evan\.platformio\penv\lib\site-packages\platformio\commands\run\command.py", line 170, in process_env
    result = {"env": name, "duration": time(), "succeeded": ep.process()}
  File "c:\users\evan\.platformio\penv\lib\site-packages\platformio\commands\run\processor.py", line 71, in process
    p = PlatformFactory.newPlatform(self.options["platform"])
  File "c:\users\evan\.platformio\penv\lib\site-packages\platformio\managers\platform.py", line 234, in newPlatform
    name = pm.load_manifest(platform_dir)["name"]
TypeError: 'NoneType' object has no attribute '__getitem__'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.

**Comment by evanwu02** [comment]
I found the Build Error that caused by the folder name "espressif32" in my project. After I removed this folder, the project can be built correctly.
