### ISSUE TITLE
pio lib hangs

### ISSUE THREAD

**Issue by 424778940z** [platformio/platformio-core#3290]
It just hangs, both install and search are not working.
It shows nothing until I press ctrl+c, for install it will abort, for search it will start showing first page of result.

Windows 10 1903 x64
VS code 1.40.2
fresh installed pio
esp32 devkit v1 board

I do have py3.8 installed but I think pio using it's own penv.

```
>>pio lib install 1513
Library Storage: D:\works\Arduino\platformio\esp32_test\.pio\libdeps\esp32doit-devkit-v1
LibraryManager: Installing id=1513
(stuck here, I wait for 5min, nothing, pressed ctrl+c)
Aborted!
PS D:\works\Arduino\platformio\esp32_test> ^C
PS D:\works\Arduino\platformio\esp32_test> ^C
PS D:\works\Arduino\platformio\esp32_test> ^C
PS D:\works\Arduino\platformio\esp32_test> ^C
PS D:\works\Arduino\platformio\esp32_test> ^C
```

```
>>pio lib search a    
(stuck here, I wait for 5min, nothing, pressed ctrl+c)
Nothing has been found by your request
Try a less-specific search or use truncation (or wildcard) operator *
For example: DS*, PCA*, DHT* and etc.

For more examples and advanced search syntax, please use documentation:
https://docs.platformio.org/page/userguide/lib/cmd_search.html
```

Did some research, use `pio lib show 1513` as example, it stuck  at:
`lib = util.get_api_result("/lib/info/%d" % lib_id, cache_valid="1d")` in lib.py

More tracking
got to `util.py` --> `get_api_result` --> `353: cc.set(cache_key, result, cache_valid)` 
~~Found work around, just disable cache...~~
Nope, `show` will work but `install` will get following error

```
Error: Traceback (most recent call last):
  File "c:\users\username\.platformio\penv\lib\site-packages\platformio\__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "c:\users\username\.platformio\penv\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\username\.platformio\penv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\username\.platformio\penv\lib\site-packages\platformio\commands\__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "c:\users\username\.platformio\penv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\username\.platformio\penv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\username\.platformio\penv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\username\.platformio\penv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\username\.platformio\penv\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\username\.platformio\penv\lib\site-packages\platformio\commands\lib.py", line 150, in lib_install
    pkg_dir = lm.install(
  File "c:\users\username\.platformio\penv\lib\site-packages\platformio\managers\lib.py", line 295, in install
    pkg_dir = BasePkgManager.install(
  File "c:\users\username\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 698, in install
    pkg_dir = self._install_from_piorepo(name, requirements)
  File "c:\users\username\.platformio\penv\lib\site-packages\platformio\managers\lib.py", line 146, in _install_from_piorepo
    return self._install_from_url(
  File "c:\users\username\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 478, in _install_from_url
    dlpath = self.download(url, tmp_dir, sha1)
  File "c:\users\username\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 211, in download
    shutil.copy(dst_path, cc.get_cache_path(cache_key_data))
  File "C:\Program Files (x86)\Python38-32\lib\shutil.py", line 409, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files (x86)\Python38-32\lib\shutil.py", line 259, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\username\\.platformio\\.cache\\5b\\2d6196b5f4394bea25f2da9de582725b'
```

`site-package\platformio\app.py` --> `set` --> `236: self._lock_dbindex` --> `190: self._lockfile.acquire` --> `188: self._lockfile = lockfile.LockFile(self.cache_dir)` --> `twisted.python.lockfile`
An upstream bug or something wrong with my pc??
I already fully wiped out cache folder, still have the same issue.

**Comment by ivankravets** [comment]
Do you use antivirus tools?

**Comment by ivankravets** [comment]
Also, could you try to kill all `python.exe` processes and try again?

**Comment by 424778940z** [comment]
> Also, could you try to kill all `python.exe` processes and try again?

did try that, but didin't help

How ever the issue disappeared after I play with those files.
Seems like a file locking issue cause the hang
you may close this issue.
