### ISSUE TITLE
Problem debugging arduino nano ble sense

### ISSUE THREAD

**Issue by dasbacete97** [platformio/platformio-core#3394]
I'm trying to debug  arduino nano 33 ble but i get this error, i have no idea about what it is, pls help.

undefinedError: Traceback (most recent call last):
  File "c:\users\dasba\.platformio\penv\lib\site-packages\platformio\__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "c:\users\dasba\.platformio\penv\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\dasba\.platformio\penv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\dasba\.platformio\penv\lib\site-packages\platformio\commands\__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "c:\users\dasba\.platformio\penv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\dasba\.platformio\penv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\dasba\.platformio\penv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\dasba\.platformio\penv\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\dasba\.platformio\penv\lib\site-packages\platformio\commands\debug\command.py", line 151, in cli
    from platformio.commands.debug.client import GDBClient, reactor
  File "c:\users\dasba\.platformio\penv\lib\site-packages\platformio\commands\debug\client.py", line 25, in <module>
    from twisted.internet import stdio  # pylint: disable=import-error
  File "C:\Users\dasba\.platformio\packages\contrib-pysite\twisted\internet\stdio.py", line 30, in <module>
    from twisted.internet import _win32stdio
  File "C:\Users\dasba\.platformio\packages\contrib-pysite\twisted\internet\_win32stdio.py", line 9, in <module>
    import win32api
ImportError: DLL load failed: No se puede encontrar el m�dulo especificado

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please try this solution https://github.com/platformio/platformio-vscode-ide/issues/1570#issuecomment-593128668
