### ISSUE TITLE
cannot open serial monitor when using nodemcu

### ISSUE THREAD

**Issue by emrizkis** [platformio/platformio-core#3431]
Error: Traceback (most recent call last):
  File "/home/emrizkis/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/emrizkis/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/emrizkis/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/emrizkis/.platformio/penv/lib/python2.7/site-packages/platformio/commands/__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "/home/emrizkis/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/emrizkis/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/emrizkis/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/emrizkis/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/emrizkis/.platformio/penv/lib/python2.7/site-packages/platformio/commands/device/command.py", line 197, in device_monitor
    platform, kwargs["project_dir"], kwargs["environment"]
  File "/home/emrizkis/.platformio/penv/lib/python2.7/site-packages/platformio/commands/device/helpers.py", line 106, in register_platform_filters
    load_monitor_filter(path, project_dir, environment)
  File "/home/emrizkis/.platformio/penv/lib/python2.7/site-packages/platformio/commands/device/helpers.py", line 90, in load_monitor_filter
    obj = cls(project_dir, environment)
  File "/home/emrizkis/.platformio/penv/lib/python2.7/site-packages/platformio/commands/device/filters/base.py", line 23, in __init__
    super(DeviceMonitorFilter, self).__init__()
TypeError: super(type, obj): obj must be an instance or subtype of type

**Comment by ru-nekit-android** [comment]
I setup Python 3.8 and use virtual-environment (https://docs.platformio.org/en/latest/core/installation.html#virtual-environment) for solve this problem.

**Comment by ivankravets** [comment]
We have fixed this issue. Please re-test with `pio upgrade --dev`.

**Comment by ivankravets** [comment]
PlatformIO Core 4.3.1 is out! Please upgrade via `pio upgrade --dev`.
