### ISSUE TITLE
pio lib install googletest: indefinite hang or connection reset

### ISSUE THREAD

**Issue by twslankard** [platformio/platformio-core#3469]
### Configuration

**Operating system**:
Ubuntu 18.04.4 LTS \n \l

**PlatformIO Version** (`platformio --version`):
 pio --version
PlatformIO, version 4.3.1

### Description of problem

Running `pio lib install googletest` hangs indefinitely or results in a connection reset. Example:

```
$ pio lib install googletest
Library Storage: <redacted>/.pio/libdeps/uno
Looking for googletest library in registry
Found: https://platformio.org/lib/show/5976/googletest
LibraryManager: Installing id=5976
Downloading  [####################----------------]   55%  00:00:04
Downloading...
Error: Please read http://bit.ly/package-manager-ioerror
Error: Traceback (most recent call last):
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/urllib3/response.py", line 437, in _error_catcher
    yield
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/lib/python3.6/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/usr/lib/python3.6/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/requests/models.py", line 751, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/urllib3/response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/platformio/__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/platformio/commands/__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/platformio/commands/lib.py", line 154, in lib_install
    library, silent=silent, interactive=interactive, force=force
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/platformio/managers/lib.py", line 280, in install
    force=force,
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/platformio/managers/package.py", line 700, in install
    pkg_dir = self._install_from_piorepo(name, requirements)
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/platformio/managers/lib.py", line 130, in _install_from_piorepo
    requirements,
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/platformio/managers/package.py", line 480, in _install_from_url
    dlpath = self.download(url, tmp_dir, sha1)
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/platformio/managers/package.py", line 195, in download
    raise e
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/platformio/managers/package.py", line 180, in download
    fd.start(with_progress=with_progress)
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/platformio/downloader.py", line 90, in start
    f.write(next(itercontent))
  File "/home/<redacted>/.platformio/penv/lib/python3.6/site-packages/requests/models.py", line 754, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================
```

#### Steps to Reproduce

1. `pip3 install -U platformio`
2. `pio lib install googletest`

### Actual Results

See above.

### Expected Results

Successful install of `googletest`

### Additional info

Development platform: Linux 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by valeros** [comment]
Cannot reproduce, looks like there was an issue with github infrastructure https://www.githubstatus.com/

**Comment by twslankard** [comment]
Thanks for looking into it. Sorry for the spurious report.
