### ISSUE TITLE
Can't start GDB debug session

### ISSUE THREAD

**Issue by easyvolts** [platformio/platformio-core#3595]
### Configuration

**Operating system**: Win10 Home 1909 with Python 3.7

**PlatformIO Version** (`platformio --version`): PlatformIO, version 4.3.4

### Description of problem
When trying starting the GDB debug session I'll get the following error: 

#### Steps to Reproduce

1. create genericSTM32F103C8 project with BlackMagicProbe debugger
2. build it
3. try launching of the debugging with command "platformio debug --interface=gdb -x .pioinit"

### Actual Results
Error: Traceback (most recent call last):
  File "c:\users\ahha7\.platformio\penv\lib\site-packages\platformio\__main__.py", line 109, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "c:\users\ahha7\.platformio\penv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\ahha7\.platformio\penv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\ahha7\.platformio\penv\lib\site-packages\platformio\commands\__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "c:\users\ahha7\.platformio\penv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\ahha7\.platformio\penv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\ahha7\.platformio\penv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\ahha7\.platformio\penv\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\ahha7\.platformio\penv\lib\site-packages\platformio\commands\debug\command.py", line 151, in cli
    from platformio.commands.debug.process.client import GDBClient, reactor
  File "c:\users\ahha7\.platformio\penv\lib\site-packages\platformio\commands\debug\process\client.py", line 26, in <module>
    from twisted.internet import stdio  # pylint: disable=import-error
  File "C:\Users\ahha7\.platformio\packages\contrib-pysite\twisted\internet\stdio.py", line 30, in <module>
    from twisted.internet import _win32stdio
  File "C:\Users\ahha7\.platformio\packages\contrib-pysite\twisted\internet\_win32stdio.py", line 9, in <module>
    import win32api
ImportError: DLL load failed: The specified module could not be found.

### Expected Results
GdbClient is started and tries to connect the remote target

### Additional info
I have a fresh installation of PlatformioIDE on VS Code. Created a test project with remote debugging :
CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/genericSTM32F103C8.html
PLATFORM: ST STM32 7.1.1 > STM32F103C8 (20k RAM. 64k Flash)
HARDWARE: STM32F103C8T6 72MHz, 20KB RAM, 64KB Flash
DEBUG: Current (blackmagic) External (blackmagic, jlink, stlink)

Platformio.ini:
[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = arduino

debug_tool = blackmagic
debug_port = 192.168.0.226:2022
upload_protocol = blackmagic

**Comment by dzid26** [comment]
I had 20 pywintypes37.dll in my system and python was confused.  This worked for me:
https://github.com/mhammond/pywin32/issues/1406#issuecomment-549222835
In console I typed:
`python "C:\Program Files\Python37\Scripts\pywin32_postinstall.py" -install`
