### ISSUE TITLE
exception KeyError: 'versions' in install_from_registry when a package referred in a platform manifest cant be found

### ISSUE THREAD

**Issue by haarer** [platformio/platformio-core#3705]
What kind of issue is this?

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

### Configuration

**Operating system**:
debian
```
uname -a
Linux gore 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
```

**PlatformIO Version** (`platformio --version`):
version 5.0.1

#### Description

I am working on adapting my fork of the atmelavr platform to the core 5 changes.
The change in the fork is, to provide toolchain packages with a fresh gcc.
I encountered a case where instead of an error message not finding the toolchain package referred to by the platform manifest, an exception is thrown.

This would not probably never happen to normal users, but i feel it should be a regular error message.

**_registry.py**
```
class PackageManageRegistryMixin(object):
    def install_from_registry(self, spec, search_filters=None, silent=False):
        if spec.owner and spec.name and not search_filters:
            package = self.fetch_registry_package(spec)
            if not package:
                raise UnknownPackageError(spec.humanize())
            
            version = self.pick_best_registry_version(package["versions"], spec)
```
**problem**
the fetch_registry_package() can return in case of an error the following
`{'message': 'Package not found', 'errors': [{'status': 404, 'title': 'Package not found'}]}`
then the  
`if not package:`
 does not catch it and pick_best_registry_version() bombs out:

```

Tool Manager: Installing haarer/toolchain-avr-current @ >=8.2.0
install_from_registry.. PackageSpec <owner=haarer id=None name=toolchain-avr-current requirements=>=8.2.0 url=None>
fetch_registry_package..PackageSpec <owner=haarer id=None name=toolchain-avr-current requirements=>=8.2.0 url=None>
{'message': 'Package not found', 'errors': [{'status': 404, 'title': 'Package not found'}]}
Error: Traceback (most recent call last):
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/platformio/__main__.py", line 109, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/platformio/commands/__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/platformio/commands/run/command.py", line 143, in cli
    is_test_running,
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/platformio/commands/run/command.py", line 175, in process_env
    result = {"env": name, "duration": time(), "succeeded": ep.process()}
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/platformio/commands/run/processor.py", line 79, in process
    result = p.run(build_vars, build_targets, self.silent, self.verbose, self.jobs)
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/platformio/platform/_run.py", line 60, in run
    self.autoinstall_runtime_packages()
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/platformio/platform/_packages.py", line 69, in autoinstall_runtime_packages
    self.pm.install(self.get_package_spec(name))
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/platformio/package/manager/_install.py", line 49, in install
    spec, silent=silent, skip_dependencies=skip_dependencies, force=force
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/platformio/package/manager/_install.py", line 99, in _install
    pkg = self.install_from_registry(spec, search_filters, silent=silent)
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/platformio/package/manager/_registry.py", line 89, in install_from_registry
    version = self.pick_best_registry_version(package["versions"], spec)
KeyError: 'versions'
```

Looking into the code, it seems that only cached error responses trigger the behavior:
In order to see this, i instrumented the code to print the function calls, the parameters and in fetch_json_data() wether it has cached data or not. 

**First run: it throws an error as expected.  cache has been cleaned by pio update before.**
```
mac@gore:~/test/platform-atmelavr/examples/native-blink$ pio run
Processing uno (platform: https://github.com/haarer/platform-atmelavr.git)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Tool Manager: Installing haarer/toolchain-avr-current @ >=8.2.0
install_from_registry() PackageSpec <owner=haarer id=None name=toolchain-avr-current requirements=>=8.2.0 url=None>
fetch_registry_package() PackageSpec <owner=haarer id=None name=toolchain-avr-current requirements=>=8.2.0 url=None>
get_package() tool haarer toolchain-avr-current
fetch_json_data() get /v3/packages/haarer/tool/toolchain-avr-current
  non cached ! <Response [404]>
Error: Could not find the package with 'haarer/toolchain-avr-current @ >=8.2.0' requirements for your system 'linux_x86_64'
```
**Second run: it bombs with an exception (note the cached responses)**
```
mac@gore:~/test/platform-atmelavr/examples/native-blink$ pio run
Processing uno (platform: https://github.com/haarer/platform-atmelavr.git)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Tool Manager: Installing haarer/toolchain-avr-current @ >=8.2.0
install_from_registry() PackageSpec <owner=haarer id=None name=toolchain-avr-current requirements=>=8.2.0 url=None>
fetch_registry_package() PackageSpec <owner=haarer id=None name=toolchain-avr-current requirements=>=8.2.0 url=None>
get_package() tool haarer toolchain-avr-current
fetch_json_data() get /v3/packages/haarer/tool/toolchain-avr-current
  cached ! {'message': 'Package not found', 'errors': [{'status': 404, 'title': 'Package not found'}]}
{'message': 'Package not found', 'errors': [{'status': 404, 'title': 'Package not found'}]}
Error: Traceback (most recent call last):
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/platformio/__main__.py", line 109, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/platformio/commands/__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/platformio/commands/run/command.py", line 143, in cli
    is_test_running,
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/platformio/commands/run/command.py", line 175, in process_env
    result = {"env": name, "duration": time(), "succeeded": ep.process()}
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/platformio/commands/run/processor.py", line 79, in process
    result = p.run(build_vars, build_targets, self.silent, self.verbose, self.jobs)
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/platformio/platform/_run.py", line 60, in run
    self.autoinstall_runtime_packages()
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/platformio/platform/_packages.py", line 69, in autoinstall_runtime_packages
    self.pm.install(self.get_package_spec(name))
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/platformio/package/manager/_install.py", line 49, in install
    spec, silent=silent, skip_dependencies=skip_dependencies, force=force
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/platformio/package/manager/_install.py", line 99, in _install
    pkg = self.install_from_registry(spec, search_filters, silent=silent)
  File "/home/mac/.platformio/penv/lib/python3.7/site-packages/platformio/package/manager/_registry.py", line 89, in install_from_registry
    version = self.pick_best_registry_version(package["versions"], spec)
KeyError: 'versions'
```

**Comment by ivankravets** [comment]
It should be fixed in the latest dev version. Please re-test with `pio upgrade --dev`.
