### ISSUE TITLE
Error in updating pio frameworks

### ISSUE THREAD

**Issue by pvonmoradi** [platformio/platformio-core#3791]
What kind of issue is this?
**PlatformIO Core**.

### Configuration

**Operating system**: Xubuntu 18.04

**PlatformIO Version**
```
platformio --version
PlatformIO Core, version 5.0.4
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```
### Description of problem
Trying to update my pio deps. 

#### Steps to Reproduce

1. Install PIO with pipx (isolated python 3.8 venv)
2. pio upgrade (works)
3. pio update

### Actual Results
```
pio update
Error: Traceback (most recent call last):
  File "/home/pooya/.local/pipx/venvs/platformio/lib/python3.8/site-packages/platformio/__main__.py", line 109, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/pooya/.local/pipx/venvs/platformio/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pooya/.local/pipx/venvs/platformio/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pooya/.local/pipx/venvs/platformio/lib/python3.8/site-packages/platformio/commands/__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "/home/pooya/.local/pipx/venvs/platformio/lib/python3.8/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/home/pooya/.local/pipx/venvs/platformio/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pooya/.local/pipx/venvs/platformio/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pooya/.local/pipx/venvs/platformio/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pooya/.local/pipx/venvs/platformio/lib/python3.8/site-packages/platformio/__main__.py", line 63, in cli
    maintenance.on_platformio_start(ctx, force, caller)
  File "/home/pooya/.local/pipx/venvs/platformio/lib/python3.8/site-packages/platformio/maintenance.py", line 45, in on_platformio_start
    telemetry.on_command()
  File "/home/pooya/.local/pipx/venvs/platformio/lib/python3.8/site-packages/platformio/telemetry.py", line 292, in on_command
    resend_backuped_reports()
  File "/home/pooya/.local/pipx/venvs/platformio/lib/python3.8/site-packages/platformio/telemetry.py", line 443, in resend_backuped_reports
    tm = app.get_state_item("telemetry", {})
  File "/home/pooya/.local/pipx/venvs/platformio/lib/python3.8/site-packages/platformio/app.py", line 187, in get_state_item
    with State() as state:
  File "/home/pooya/.local/pipx/venvs/platformio/lib/python3.8/site-packages/platformio/app.py", line 90, in __init__
    self.path = join(get_project_core_dir(), "appstate.json")
  File "/home/pooya/.local/pipx/venvs/platformio/lib/python3.8/site-packages/platformio/project/helpers.py", line 51, in get_project_core_dir
    join(get_project_dir(), "platformio.ini")
  File "/home/pooya/.local/pipx/venvs/platformio/lib/python3.8/site-packages/platformio/project/helpers.py", line 29, in get_project_dir
    return os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```

### Expected Results
To exist successfully. I didn't have this problem for previous versions.

**Comment by ivankravets** [comment]
You are located in the folder that was removed from the system. Try to restart your VSCode and check the project location.
