### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 207: illegal multibyte sequence

### ISSUE THREAD

**Issue by lizhenyang123** [platformio/platformio-core#3815]
# System environment
Windows	20H2 

PlatformIO Core, version 5.0.4

# platformio.ini
```
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
lib_deps = 
	tzapu/WiFiManager@^2.0.4-beta
	bblanchon/ArduinoJson@^6.17.2
	arduino-libraries/NTPClient@^3.1.0
```

# Problem

PlatformIO:Build

Stop at **Archiving .pio\build\nodemcuv2\libFrameworkArduino.a**

Always building....

I think it's the problem here
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\23663\.platformio\python3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\23663\.platformio\python3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\23663\.platformio\penv\lib\site-packages\platformio\proc.py", line 47, in run
    self.do_reading()
  File "c:\users\23663\.platformio\penv\lib\site-packages\platformio\proc.py", line 70, in do_reading
    for byte in iter(lambda: self._pipe_reader.read(1), ""):
  File "c:\users\23663\.platformio\penv\lib\site-packages\platformio\proc.py", line 70, in <lambda>
    for byte in iter(lambda: self._pipe_reader.read(1), ""):
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 207: illegal multibyte sequence
```

**complete output**
```
Processing nodemcuv2 (platform: espressif8266; board: nodemcuv2; framework: arduino)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/nodemcuv2.html
PLATFORM: Espressif 8266 (2.6.2) > NodeMCU 1.0 (ESP-12E Module)
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES:
 - framework-arduinoespressif8266 3.20704.0 (2.7.4)
 - tool-esptool 1.413.0 (4.13)
 - tool-esptoolpy 1.20800.0 (2.8.0)
 - toolchain-xtensa 2.40802.200502 (4.8.2)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 32 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <WiFiManager> 2.0.4-beta 
|   |-- <DNSServer> 1.1.1    
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266mDNS> 1.2    
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WebServer> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ArduinoJson> 6.17.2
|-- <NTPClient> 3.1.0
|-- <ESP8266HTTPClient> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
Building in release mode
Compiling .pio\build\nodemcuv2\src\main.cpp.o
Generating LD script .pio\build\nodemcuv2\ld\local.eagle.app.v6.common.ld
Compiling .pio\build\nodemcuv2\lib28d\ESP8266WiFi\BearSSLHelpers.cpp.o
Compiling .pio\build\nodemcuv2\lib28d\ESP8266WiFi\CertStoreBearSSL.cpp.o
Compiling .pio\build\nodemcuv2\lib28d\ESP8266WiFi\ESP8266WiFi.cpp.o
Compiling .pio\build\nodemcuv2\lib28d\ESP8266WiFi\ESP8266WiFiAP.cpp.o
Compiling .pio\build\nodemcuv2\lib28d\ESP8266WiFi\ESP8266WiFiGeneric.cpp.o
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\23663\.platformio\python3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\23663\.platformio\python3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\23663\.platformio\penv\lib\site-packages\platformio\proc.py", line 47, in run
    self.do_reading()
  File "c:\users\23663\.platformio\penv\lib\site-packages\platformio\proc.py", line 70, in do_reading
    for byte in iter(lambda: self._pipe_reader.read(1), ""):
  File "c:\users\23663\.platformio\penv\lib\site-packages\platformio\proc.py", line 70, in <lambda>
    for byte in iter(lambda: self._pipe_reader.read(1), ""):
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 207: illegal multibyte sequence

Compiling .pio\build\nodemcuv2\lib28d\ESP8266WiFi\ESP8266WiFiGratuitous.cpp.o
Compiling .pio\build\nodemcuv2\lib28d\ESP8266WiFi\ESP8266WiFiMulti.cpp.o
Compiling .pio\build\nodemcuv2\lib28d\ESP8266WiFi\ESP8266WiFiSTA-WPS.cpp.o
Compiling .pio\build\nodemcuv2\lib28d\ESP8266WiFi\ESP8266WiFiSTA.cpp.o
Compiling .pio\build\nodemcuv2\lib28d\ESP8266WiFi\ESP8266WiFiScan.cpp.o
Compiling .pio\build\nodemcuv2\lib28d\ESP8266WiFi\WiFiClient.cpp.o
Compiling .pio\build\nodemcuv2\lib28d\ESP8266WiFi\WiFiClientSecureAxTLS.cpp.o
Compiling .pio\build\nodemcuv2\lib28d\ESP8266WiFi\WiFiClientSecureBearSSL.cpp.o
Compiling .pio\build\nodemcuv2\lib28d\ESP8266WiFi\WiFiServer.cpp.o
Compiling .pio\build\nodemcuv2\lib28d\ESP8266WiFi\WiFiServerSecureAxTLS.cpp.o
Compiling .pio\build\nodemcuv2\lib28d\ESP8266WiFi\WiFiServerSecureBearSSL.cpp.o
Compiling .pio\build\nodemcuv2\lib28d\ESP8266WiFi\WiFiUdp.cpp.o
Compiling .pio\build\nodemcuv2\libe0c\DNSServer\DNSServer.cpp.o
Compiling .pio\build\nodemcuv2\libb0c\ESP8266mDNS\ESP8266mDNS.cpp.o
Archiving .pio\build\nodemcuv2\libe0c\libDNSServer.a
Compiling .pio\build\nodemcuv2\libb0c\ESP8266mDNS\ESP8266mDNS_Legacy.cpp.o
Archiving .pio\build\nodemcuv2\lib28d\libESP8266WiFi.a
Compiling .pio\build\nodemcuv2\libb0c\ESP8266mDNS\LEAmDNS.cpp.o
Compiling .pio\build\nodemcuv2\libb0c\ESP8266mDNS\LEAmDNS_Control.cpp.o
Compiling .pio\build\nodemcuv2\libb0c\ESP8266mDNS\LEAmDNS_Helpers.cpp.o
Compiling .pio\build\nodemcuv2\libb0c\ESP8266mDNS\LEAmDNS_Structs.cpp.o
Compiling .pio\build\nodemcuv2\libb0c\ESP8266mDNS\LEAmDNS_Transfer.cpp.o
Compiling .pio\build\nodemcuv2\lib58d\ESP8266WebServer\detail\mimetable.cpp.o
Archiving .pio\build\nodemcuv2\lib58d\libESP8266WebServer.a
Compiling .pio\build\nodemcuv2\libefb\WiFiManager\WiFiManager.cpp.o
Archiving .pio\build\nodemcuv2\lib8a8\libArduinoJson.a
Compiling .pio\build\nodemcuv2\lib5bf\NTPClient\NTPClient.cpp.o
Archiving .pio\build\nodemcuv2\libb0c\libESP8266mDNS.a
Compiling .pio\build\nodemcuv2\lib3fa\ESP8266HTTPClient\ESP8266HTTPClient.cpp.o
Archiving .pio\build\nodemcuv2\lib5bf\libNTPClient.a
Archiving .pio\build\nodemcuv2\libFrameworkArduinoVariant.a
Compiling .pio\build\nodemcuv2\FrameworkArduino\Crypto.cpp.o
Archiving .pio\build\nodemcuv2\lib3fa\libESP8266HTTPClient.a
Compiling .pio\build\nodemcuv2\FrameworkArduino\Esp-frag.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\Esp-version.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\Esp.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\FS.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\FSnoop.cpp.o
Archiving .pio\build\nodemcuv2\libefb\libWiFiManager.a
Compiling .pio\build\nodemcuv2\FrameworkArduino\FunctionalInterrupt.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\HardwareSerial.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\IPAddress.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\MD5Builder.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\Print.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\Schedule.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\StackThunk.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\Stream.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\StreamString.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\Tone.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\TypeConversion.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\Updater.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\WMath.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\WString.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\abi.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\base64.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\cbuf.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\cont.S.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\cont_util.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\core_esp8266_app_entry_noextra4k.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\core_esp8266_eboot_command.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\core_esp8266_features.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\core_esp8266_flash_quirks.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\core_esp8266_flash_utils.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\core_esp8266_i2s.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\core_esp8266_main.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\core_esp8266_noniso.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\core_esp8266_phy.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\core_esp8266_postmortem.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\core_esp8266_si2c.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\core_esp8266_sigma_delta.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\core_esp8266_spi_utils.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\core_esp8266_timer.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\core_esp8266_waveform.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\core_esp8266_wiring.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\core_esp8266_wiring_analog.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\core_esp8266_wiring_digital.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\core_esp8266_wiring_pulse.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\core_esp8266_wiring_pwm.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\core_esp8266_wiring_shift.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\crc32.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\debug.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\flash_hal.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\gdb_hooks.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\heap.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\libb64\cdecode.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\libb64\cencode.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\libc_replacements.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\sntp-lwip2.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\spiffs\spiffs_cache.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\spiffs\spiffs_check.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\spiffs\spiffs_gc.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\spiffs\spiffs_hydrogen.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\spiffs\spiffs_nucleus.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\spiffs_api.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\sqrt32.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\time.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\uart.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\umm_malloc\umm_info.c.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\umm_malloc\umm_integrity.c.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\umm_malloc\umm_local.c.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\umm_malloc\umm_malloc.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\umm_malloc\umm_poison.c.o
Archiving .pio\build\nodemcuv2\libFrameworkArduino.a
```
# pio system info
```
--------------------------  ------------------------------------------------------
PlatformIO Core             5.0.4
Python                      3.7.7-final.0
System Type                 windows_amd64
Platform                    Windows-10
File System Encoding        utf-8
Locale Encoding             cp936
PlatformIO Core Directory   C:\Users\23663\.platformio
PlatformIO Core Executable  C:\Users\23663\.platformio\penv\Scripts\platformio.exe
Python Executable           c:\users\23663\.platformio\penv\scripts\python.exe
Global Libraries            0
Development Platforms       5
Tools & Toolchains          19
--------------------------  ------------------------------------------------------
```

# note
If i create a new empty project, no libraries added,the compilation is successful

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-core/issues/3804

Please re-run `pio upgrade --dev`. Restart VSCode.
