### ISSUE TITLE
platformio platform list crashes

### ISSUE THREAD

**Issue by mozgwar** [platformio/platformio-core#3826]
### Configuration

**Operating system**: Linux

**PlatformIO Version** : PlatformIO Core, version 5.1.0

### Description of problem
 pio platform list                                                                                     mozgwar 
Error: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/platformio/__main__.py", line 109, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/platformio/commands/__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/platformio/commands/platform.py", line 226, in platform_list
    _get_installed_platform_data(pkg, with_boards=False, expose_packages=False)
  File "/usr/lib/python3.9/site-packages/platformio/commands/platform.py", line 77, in _get_installed_platform_data
    description=p.description,
  File "/usr/lib/python3.9/site-packages/platformio/platform/base.py", line 60, in description
    return self._manifest["description"]
KeyError: 'description'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
Please check `~/.platformio/platforms` folder and remove unofficial broken dev-platforms. See a list of official dev-platforms. https://platformio.org/platforms
