### ISSUE TITLE
Platformio Remote Agent Start crashes in Manjaro

### ISSUE THREAD

**Issue by mclane** [platformio/platformio-core#3880]
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [x ] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: Manjaro Linux Orion 5.4.101-1-MANJARO #1 SMP PREEMPT Fri Feb 26 11:18:55 UTC 2021 x86_64 GNU/Linux

**PlatformIO Version** (`platformio --version`): PlatformIO Core, version 5.1.0

### Description of problem
pio remote agent start crashes

#### Steps to Reproduce
[uli@Orion ~]$ pio remote agent start
Tool Manager: Installing platformio/contrib-pysite @ ~2.39.0
Unpacking  [####################################]  100%          
Tool Manager: contrib-pysite @ 2.39.201019 has been installed!
Collecting twisted==20.3.0
  Using cached Twisted-20.3.0.tar.bz2 (3.1 MB)
Collecting attrs>=19.2.0
  Using cached attrs-20.3.0.tar.gz (164 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting Automat>=0.3.0
  Using cached Automat-20.2.0.tar.gz (61 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8xwtkbhu/automat_57d902ad9c704efd8e3a9dd4df2b10b3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8xwtkbhu/automat_57d902ad9c704efd8e3a9dd4df2b10b3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-fujtaomd
         cwd: /tmp/pip-install-8xwtkbhu/automat_57d902ad9c704efd8e3a9dd4df2b10b3/
    Complete output (49 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-ou16j_27/m2r_3a4600d5c0a94d43b73bd09b6b0cec92/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-ou16j_27/m2r_3a4600d5c0a94d43b73bd09b6b0cec92/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-hnm4bax0
           cwd: /tmp/pip-wheel-ou16j_27/m2r_3a4600d5c0a94d43b73bd09b6b0cec92/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for m2r
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpa_kxpcva', '--quiet', 'm2r']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8xwtkbhu/automat_57d902ad9c704efd8e3a9dd4df2b10b3/setup.py", line 15, in <module>
        setup(
      File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 687, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 766, in resolve
        dist = best[req.key] = env.best_match(
      File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1063, in obtain
        return installer(requirement)
      File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 746, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpa_kxpcva', '--quiet', 'm2r']' returned non-zero exit status 1.
    
    
    !!! m2r not found, long_description is bad, don't upload this to PyPI !!!
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Error: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/platformio/package/manager/core.py", line 127, in inject_contrib_pysite
    from OpenSSL import SSL
  File "/home/uli/.platformio/packages/contrib-pysite/OpenSSL/__init__.py", line 8, in <module>
  File "/home/uli/.platformio/packages/contrib-pysite/OpenSSL/crypto.py", line 15, in <module>
  File "/home/uli/.platformio/packages/contrib-pysite/OpenSSL/_util.py", line 6, in <module>
  File "/home/uli/.platformio/packages/contrib-pysite/cryptography/hazmat/bindings/openssl/binding.py", line 15, in <module>
ImportError: libffi.so.6: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/platformio/__main__.py", line 109, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/platformio/commands/__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/platformio/commands/remote/command.py", line 42, in cli
    inject_contrib_pysite(verify_openssl=True)
  File "/usr/lib/python3.9/site-packages/platformio/package/manager/core.py", line 129, in inject_contrib_pysite
    build_contrib_pysite_package(contrib_pysite_dir)
  File "/usr/lib/python3.9/site-packages/platformio/package/manager/core.py", line 153, in build_contrib_pysite_package
    subprocess.check_call(args + [dep])
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'pip', 'install', '--no-compile', '-t', '/home/uli/.platformio/packages/contrib-pysite', '--no-binary', ':all:', 'twisted == 20.3.0']' returned non-zero exit status 1.

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by mclane** [comment]
Ok, I installed m2r and rust. After that, the process proceeded but then crashed again. I retried and this time it crashed due to a missing library: python-certifi. I installed this and then it worked.
