### ISSUE TITLE
PVS-Studio check does not work

### ISSUE THREAD

**Issue by Gizmodo** [platformio/platformio-core#3989]
What kind of issue is this?

- [ ] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.
------------------------------------------------------------------

### Configuration

**Operating system**:
Linux notebook 5.12.8-051208-generic #202105281232 SMP Fri May 28 12:35:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**PlatformIO Version** (`platformio --version`):
PlatformIO Core, version 5.1.1
#### Steps to Reproduce

1. Project Tasks - ESP8266 - Advanced - Check 

### Actual Results
> Executing task: platformio check --environment ESP8266 <

Checking ESP8266 > pvs-studio (platform: espressif8266; board: esp12e; framework: arduino)
----------------------------------------------------------------------------------------------
Error: Traceback (most recent call last):
  File "/home/user/.platformio/penv/lib/python3.9/site-packages/platformio/__main__.py", line 109, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/user/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/.platformio/penv/lib/python3.9/site-packages/platformio/commands/__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "/home/user/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.platformio/penv/lib/python3.9/site-packages/platformio/commands/check/command.py", line 134, in cli
    rc = ct.check(
  File "/home/user/.platformio/penv/lib/python3.9/site-packages/platformio/commands/check/tools/pvsstudio.py", line 243, in check
    self._process_defects(self.parse_defects(self._tmp_output_file))
  File "/home/user/.platformio/penv/lib/python3.9/site-packages/platformio/commands/check/tools/pvsstudio.py", line 136, in parse_defects
    DefectItem(
  File "/home/user/.platformio/penv/lib/python3.9/site-packages/platformio/commands/check/defect.py", line 54, in __init__
    if file.lower().startswith(get_project_dir().lower()):
AttributeError: 'NoneType' object has no attribute 'lower'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

The terminal process "platformio 'check', '--environment', 'ESP8266'" terminated with exit code: 1.

### Expected Results
I want to see check results

### Additional info
Quick Access - Updates - Update All 

pio update
Updating platformio/contrib-piohome           3.3.4 @ ~3.3.4                     [Up-to-date]
Updating platformio/tool-unity                1.20500.200612 @ ~1.20500.0        [Up-to-date]
Updating platformio/tool-scons                4.40100.2 @ ~4.40100.2             [Up-to-date]
Updating platformio/tool-pvs-studio           7.11.44138 @ ~7.11.0               **[Incompatible 7.12.46137]**

**Comment by ivankravets** [comment]
Please reopen if you still need help
