### ISSUE TITLE
ModuleNotFoundError for twisted.internet and pywin32_bootstrap modules

### ISSUE THREAD

**Issue by GeVanCo** [platformio/platformio-core#4017]
I'm using Visual Studio Code in combination with PlatformIO to debug my applications on an Arduino Uno board using the `avr-stub` plugin described [here](https://docs.platformio.org/en/latest//plus/debug-tools/avr-stub.html#debugging-tool-avr-stub).

### Configuration

**Operating system**: Windows 10 Home edition

**PlatformIO Version** (`platformio --version`): PlatformIO Core, version 5.1.1

### Description of problem
When starting the debugger in Visual Studio Code, the breakpoints are not hit.

#### Steps to Reproduce

1. Create a simple Android Uno `main.cpp` file with the following content:

```cpp
#include <Arduino.h>
#include "app_api.h"
#include "avr8-stub.h"
#include <SPI.h>

#define LATCH_PIN 4
#define SPI_CLOCK_PIN 13
#define SPI_MOSI_PIN 11         // DS pin of 74595
#define ISR_0_PIN 2

#define CLOCKSPEED 8000000

int j = 0;

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

void setup() {
    // Serial.begin(115200);
    // Serial.println("Start");

    debug_init();
    breakpoint();

    pinMode(SPI_CLOCK_PIN, OUTPUT); // SPI -> Clock, pin 13 of Arduino Uno to pin 11 (SH_CP) of 595
    pinMode(SPI_MOSI_PIN, OUTPUT); // SPI -> MOSI, pin 11 of Arduino Uno to pin 14 (DS) of 595
    pinMode(LATCH_PIN, OUTPUT);  // Latch, pin 4 of Arduino Uno to pin 
    pinMode(ISR_0_PIN, INPUT);   // Connected to ISR0.

    SPI.begin();
    SPI.beginTransaction(SPISettings(CLOCKSPEED, MSBFIRST, SPI_MODE0));
    SPI.transfer(0);
    SPI.transfer(255);
    digitalWrite(LATCH_PIN, HIGH);
    digitalWrite(LATCH_PIN, LOW);
}

void loop() {

    breakpoint();
    SPI.transfer(j);
    SPI.transfer(0);
    digitalWrite(4, HIGH);
    digitalWrite(4,LOW);
    delay(10);
    j++;    
}
```

2. Create a platform.io file with the following content:

```ini
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200

; Added for avr-debugger
build_type = debug
debug_tool = avr-stub
debug_port = COM3
debug_load_mode = manual

debug_build_flags =  
    -Og 
    -g2  
    -DDEBUG

lib_deps = 
    jdolinay/avr-debugger @ ~1.4
```

3. Place a BP in the code, e.g. on line 

```cpp
    SPI.transfer(j);
```

4. Press the Debug button in Visual Studio Code: the BP is not hit

5. Open the DEBUG CONSOLE window in Visual Studio Code: the following error is given:

```
undefinedError processing line 7 of C:\Users\Geert\.platformio\packages\contrib-pysite\pywin32.pth:

  Traceback (most recent call last):
    File "C:\Users\Geert\.platformio\python3\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named 'pywin32_bootstrap'

Remainder of file ignored
Error: Traceback (most recent call last):
  File "C:\Users\Geert\.platformio\penv\lib\site-packages\platformio\__main__.py", line 109, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "C:\Users\Geert\.platformio\penv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Geert\.platformio\penv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Geert\.platformio\penv\lib\site-packages\platformio\commands\__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "C:\Users\Geert\.platformio\penv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Geert\.platformio\penv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Geert\.platformio\penv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Geert\.platformio\penv\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Geert\.platformio\penv\lib\site-packages\platformio\commands\debug\command.py", line 167, in cli
    from platformio.commands.debug.process.client import GDBClient, reactor
  File "C:\Users\Geert\.platformio\penv\lib\site-packages\platformio\commands\debug\process\client.py", line 23, in <module>
    from twisted.internet import defer  # pylint: disable=import-error
ModuleNotFoundError: No module named 'twisted.internet'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

```

6. I (re)installed the `twisted` module using `pip install --ignore-installed twisted` and tried it out after installation running the command `pip -c "import twisted.internet;'`: that gave **no** issues. so the module **is** available.

7. I (re)installed the `pywin32` module using `pip install --ignore-installed pywin32` and tried it out after installation running the command `pip -c "import pywin32_bootstrap;'`: that gave **no** issues. so the module **is** available.
 
8. I restarted Visual Studio Code to be sure the new/updated python modules could be re-read

9. Unfortunately, issue remains the same

### Actual Results
Debugger doesn't stop @ breakpoint

### Expected Results
Debugger should stop @ breakpoint

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200

; Added for avr-debugger
build_type = debug
debug_tool = avr-stub
debug_port = COM3
debug_load_mode = manual

debug_build_flags =  
    -Og 
    -g2  
    -DDEBUG

lib_deps = 
    jdolinay/avr-debugger @ ~1.4
```

**Source file to reproduce issue:**
```cpp
#include <Arduino.h>
#include "app_api.h"
#include "avr8-stub.h"
#include <SPI.h>

#define LATCH_PIN 4
#define SPI_CLOCK_PIN 13
#define SPI_MOSI_PIN 11         // DS pin of 74595
#define ISR_0_PIN 2

#define CLOCKSPEED 8000000

int j = 0;

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

void setup() {
    // Serial.begin(115200);
    // Serial.println("Start");

    debug_init();
    breakpoint();

    pinMode(SPI_CLOCK_PIN, OUTPUT); // SPI -> Clock, pin 13 of Arduino Uno to pin 11 (SH_CP) of 595
    pinMode(SPI_MOSI_PIN, OUTPUT); // SPI -> MOSI, pin 11 of Arduino Uno to pin 14 (DS) of 595
    pinMode(LATCH_PIN, OUTPUT);  // Latch, pin 4 of Arduino Uno to pin 
    pinMode(ISR_0_PIN, INPUT);   // Connected to ISR0.

    SPI.begin();
    SPI.beginTransaction(SPISettings(CLOCKSPEED, MSBFIRST, SPI_MODE0));
    SPI.transfer(0);
    SPI.transfer(255);
    digitalWrite(LATCH_PIN, HIGH);
    digitalWrite(LATCH_PIN, LOW);
}

void loop() {

    breakpoint();
    SPI.transfer(j);
    SPI.transfer(0);
    digitalWrite(4, HIGH);
    digitalWrite(4,LOW);
    delay(10);
    j++;    
}
```

### Additional info
I also contacted the author of the `avr-stub` PlatformIO module on the CodeProject web site ([this](https://www.codeproject.com/Articles/5160447/Creating-and-Debugging-Arduino-Programs-in-Visua-2?msg=5823415#xx5823415xx) link) but the discussion is still ongoing...

**Comment by ivankravets** [comment]
Fixed in PlatformIO Core 5.2.
