### ISSUE TITLE
cli: pio ci 'target' for the run is None with click 8.0.2

### ISSUE THREAD

**Issue by mcspr** [platformio/platformio-core#4078]
### Configuration

**Operating system**:

Debian GNU/Linux 11 (bullseye)

**PlatformIO Version** (`platformio --version`):

PlatformIO Core, version 5.2.1rc1
PlatformIO Core, version 5.2.0

### Description of problem

After pulling [today's Click 8.0.2](https://click.palletsprojects.com/en/8.0.x/changes/#version-8-0-2), there is an issue with the implicit `default` for the '--target' 

https://github.com/platformio/platformio-core/blob/fe62b810dba1fec1c3ae2463a4dbc0930741b21b/platformio/commands/run/command.py#L42

```python
Error: Traceback (most recent call last):
  File "/home/runner/pio-test/lib/python3.9/site-packages/platformio/__main__.py", line 130, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/runner/pio-test/lib/python3.9/site-packages/click/core.py", line 1126, in __call__
    return self.main(*args, **kwargs)


  File "/home/runner/pio-test/lib/python3.9/site-packages/click/core.py", line 1051, in main


    rv = self.invoke(ctx)
  File "/home/runner/pio-test/lib/python3.9/site-packages/platformio/commands/__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "/home/runner/pio-test/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/runner/pio-test/lib/python3.9/site-packages/click/core.py", line 1393, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/pio-test/lib/python3.9/site-packages/click/core.py", line 752, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/pio-test/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/runner/pio-test/lib/python3.9/site-packages/platformio/commands/ci.py", line 119, in cli
    ctx.invoke(cmd_run, project_dir=build_dir, verbose=verbose)
  File "/home/runner/pio-test/lib/python3.9/site-packages/click/core.py", line 752, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/pio-test/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/runner/pio-test/lib/python3.9/site-packages/platformio/commands/run/command.py", line 135, in cli
    process_env(
  File "/home/runner/pio-test/lib/python3.9/site-packages/platformio/commands/run/command.py", line 174, in process_env
    ep = EnvironmentProcessor(
  File "/home/runner/pio-test/lib/python3.9/site-packages/platformio/commands/run/processor.py", line 29, in __init__
    self.targets = [str(t) for t in targets]
TypeError: 'NoneType' object is not iterable
```

Tracing both `ci` and `run`, `target` is set to `()` when `run` is called normally as `run()`. But, when used through `ctx.invoke(cmd_run)` it is set to `None` which breaks the rest of the logic in the command.

But, not yet sure whether this was an intended change from the Click 8 release, or something broken in the context generation. Or, whether the `default=()` should be set explicitly in the PIO.

#### Steps to Reproduce

```
$ pip install click==8.0.2
$ pio ci <anything> --board nodemcuv2
```

**Comment by TheNitek** [comment]
Is there an easy work around for GitHub Actions (like forcing a older click version)? Spent half a day debugging yesterday until I found this issue and realized I wasn't doing anything wrong.

**Comment by ivankravets** [comment]
I've just tried to apply quick workarounds for Click 8.0.2 but it seems that Click 8.0.2 is totally broken. A lot of commands do not work, Click claims that Path does not exist but that is not true. We will skip 8.0.2 from installation and wait for 8.0.3 with reverted changes.

![Screen Shot 2021-10-10 at 14 05 13](https://user-images.githubusercontent.com/1760209/136692995-cd02e512-2bc9-41a3-b78b-31726f97711e.png)
