### ISSUE TITLE
An unexpected error occurred, log said to report here.

### ISSUE THREAD

**Issue by tbvink** [platformio/platformio-core#4189]
When I try to debug I get the info in the debugger tab:

I had been using the tool successfully for a month or so and this just happened.  At first I the debugger just would not start but I did not think to look in the debugger tab.  There was a message in the build about not finding UART.CPP somewhere down in the espressive tool directories.  I deleted my packages directory and ran again and platformIO auto downloaded all the stuff I removed but that did not fix.  I uninstalled the PlatformIO extension from VSC and reinstalled.  No luck.  I uninstalled all the Python on my pc and reinstalled.  Still the same.

I am on an up to date Windows 10PC and my target is a NODEMCU-32s

Tony

==================================================================
undefinedError: Traceback (most recent call last):
  File "C:\Users\tbvin\.platformio\penv\lib\site-packages\platformio\__main__.py", line 121, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "C:\Users\tbvin\.platformio\penv\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\tbvin\.platformio\penv\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\tbvin\.platformio\penv\lib\site-packages\platformio\commands\__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "C:\Users\tbvin\.platformio\penv\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\tbvin\.platformio\penv\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\tbvin\.platformio\penv\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\tbvin\.platformio\penv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\tbvin\.platformio\penv\lib\site-packages\platformio\debug\command.py", line 98, in debug_cmd
    debug_config = DebugConfigFactory.new(
  File "C:\Users\tbvin\.platformio\penv\lib\site-packages\platformio\debug\config\factory.py", line 48, in new
    return config_cls(platform, project_config, env_name)
  File "C:\Users\tbvin\.platformio\penv\lib\site-packages\platformio\debug\config\generic.py", line 37, in __init__
    super(GenericDebugConfig, self).__init__(*args, **kwargs)
  File "C:\Users\tbvin\.platformio\penv\lib\site-packages\platformio\debug\config\base.py", line 52, in __init__
    self.server = self._configure_server()
  File "C:\Users\tbvin\.platformio\penv\lib\site-packages\platformio\debug\config\base.py", line 189, in _configure_server
    self.platform.install_packages(
TypeError: install_packages() got an unexpected keyword argument 'silent'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

My platformio.ini file
;

[env:esp32dev]
debug_build_flags = -Og -ggdb -g3 -D ESP32_Board
platform = espressif32
board = nodemcu-32s
build_type = debug
debug_tool = esp-prog
debug_init_break = tbreak setup
framework = arduino
monitor_speed = 115200
upload_port = COM5

**Comment by ivankravets** [comment]
Thanks for the report.

Please open PlatformIO CLI (Core) and type `pio upgrade --dev`. 

Does it work now?

**Comment by tbvink** [comment]
Thanks, I am up and running.
