### ISSUE TITLE
"The terminal process "C:\Users\Admin\.platformio\penv\Scripts\platformio.exe 'device', 'monitor'" terminated with exit code: 1"

### ISSUE THREAD

**Issue by acautomacaoecontrole** [platformio/platformio-core#4227]
-----------------------------------------------------------------

### Configuration

**Operating system**: 
Win7

**PlatformIO Version** (`platformio --version`):
Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 6.1.7601

### Description of problem
When activating monitor, the following messages were thrown:
"
> Executing task in folder InterpretadorDeSinalDeRodaFonica: C:\Users\Admin\.platformio\penv\Scripts\platformio.exe device monitor <

Error: Traceback (most recent call last):
  File "C:\Users\Admin\.platformio\penv\lib\site-packages\platformio\__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "C:\Users\Admin\.platformio\penv\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Admin\.platformio\penv\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\Admin\.platformio\penv\lib\site-packages\platformio\commands\__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "C:\Users\Admin\.platformio\penv\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Admin\.platformio\penv\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Admin\.platformio\penv\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Admin\.platformio\penv\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Admin\.platformio\penv\lib\site-packages\platformio\commands\device\command.py", line 189, in device_monitor
    device_helpers.register_filters(platform=platform, options=kwargs)
  File "C:\Users\Admin\.platformio\penv\lib\site-packages\platformio\commands\device\helpers.py", line 120, in register_filters
    options=options,
  File "C:\Users\Admin\.platformio\penv\lib\site-packages\platformio\commands\device\helpers.py", line 105, in load_monitor_filters
    load_monitor_filter(path, options)
  File "C:\Users\Admin\.platformio\penv\lib\site-packages\platformio\commands\device\helpers.py", line 83, in load_monitor_filter
    module = load_python_module("platformio.commands.device.filters.%s" % name, path)
  File "C:\Users\Admin\.platformio\penv\lib\site-packages\platformio\compat.py", line 62, in load_python_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Admin\.platformio\platforms\espressif32\monitor\filter_exception_decoder.py", line 20, in <module>
    from platformio.compat import path_to_unicode, WINDOWS, PY2
ImportError: cannot import name 'PY2' from 'platformio.compat' (C:\Users\Admin\.platformio\penv\lib\site-packages\platformio\compat.py)

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

The terminal process "C:\Users\Admin\.platformio\penv\Scripts\platformio.exe 'device', 'monitor'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
"

I do not know what happened since previous monitor utilization a couple of days ago. Not sure if some PlatformIO update has occurred.

**Comment by ivankravets** [comment]
VSCode > Left Activity Bar -> PlatformIO > Upgrade PlatformIO Core
