### ISSUE TITLE
Invalid simple block 'v0.1.0'

### ISSUE THREAD

**Issue by RodrigoDornelles** [platformio/platformio-core#4327]
What kind of issue is this?

- [X] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [X] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [X] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:

```Darwin mac.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Apr 18 21:50:40 PDT 2022; root:xnu-6153.141.62~1/RELEASE_X86_64 x86_64```

**PlatformIO Version** (`platformio --version`):

```
PlatformIO Core, version 6.0.2
```

### Description of problem

Error when require deps

#### Steps to Reproduce

1. put deps on plataformio.ini
```
lib_deps =
    https://github.com/rodrigodornelles/3bc-lang
```

2. click on build

### Actual Results

```
Removing unused dependencies...
Error: Traceback (most recent call last):
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/cli.py", line 71, in invoke
    return super().invoke(ctx)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/run/cli.py", line 142, in cli
    process_env(
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/run/cli.py", line 197, in process_env
    result = {"env": name, "duration": time(), "succeeded": ep.process()}
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/run/processor.py", line 83, in process
    install_project_env_dependencies(
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/package/commands/install.py", line 132, in install_project_env_dependencies
    _install_project_env_libraries(project_env, options),
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/package/commands/install.py", line 204, in _install_project_env_libraries
    _uninstall_project_unused_libdeps(project_env, options)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/package/commands/install.py", line 264, in _uninstall_project_unused_libdeps
    lm.uninstall(spec)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/package/manager/_uninstall.py", line 29, in uninstall
    return self._uninstall(spec, skip_dependencies)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/package/manager/_uninstall.py", line 34, in _uninstall
    pkg = self.get_package(spec)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/package/manager/base.py", line 262, in get_package
    spec = self.ensure_spec(spec)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/package/manager/base.py", line 132, in ensure_spec
    return spec if isinstance(spec, PackageSpec) else PackageSpec(spec)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/package/meta.py", line 143, in __init__
    self._parse(self.raw)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/package/meta.py", line 250, in _parse
    raw = parser(raw)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/package/meta.py", line 275, in _parse_requirements
    self.requirements = tokens[1].strip()
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/package/meta.py", line 190, in requirements
    else semantic_version.SimpleSpec(str(value))
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/semantic_version/base.py", line 647, in __init__
    self.clause = self._parse_to_clause(expression)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/semantic_version/base.py", line 1043, in _parse_to_clause
    return cls.Parser.parse(expression)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/semantic_version/base.py", line 1063, in parse
    raise ValueError("Invalid simple block %r" % block)
ValueError: Invalid simple block 'v0.1.0'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

The terminal process "platformio 'run', '--environment', 'uno'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

> Executing task: platformio run --environment uno <

Processing uno (platform: atmelavr; board: uno; framework: arduino)
-------------------------------------------------------------------------------------------------------------------------
Removing unused dependencies...
Error: Traceback (most recent call last):
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/cli.py", line 71, in invoke
    return super().invoke(ctx)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/run/cli.py", line 142, in cli
    process_env(
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/run/cli.py", line 197, in process_env
    result = {"env": name, "duration": time(), "succeeded": ep.process()}
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/run/processor.py", line 83, in process
    install_project_env_dependencies(
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/package/commands/install.py", line 132, in install_project_env_dependencies
    _install_project_env_libraries(project_env, options),
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/package/commands/install.py", line 204, in _install_project_env_libraries
    _uninstall_project_unused_libdeps(project_env, options)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/package/commands/install.py", line 264, in _uninstall_project_unused_libdeps
    lm.uninstall(spec)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/package/manager/_uninstall.py", line 29, in uninstall
    return self._uninstall(spec, skip_dependencies)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/package/manager/_uninstall.py", line 34, in _uninstall
    pkg = self.get_package(spec)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/package/manager/base.py", line 262, in get_package
    spec = self.ensure_spec(spec)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/package/manager/base.py", line 132, in ensure_spec
    return spec if isinstance(spec, PackageSpec) else PackageSpec(spec)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/package/meta.py", line 143, in __init__
    self._parse(self.raw)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/package/meta.py", line 250, in _parse
    raw = parser(raw)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/package/meta.py", line 275, in _parse_requirements
    self.requirements = tokens[1].strip()
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/platformio/package/meta.py", line 190, in requirements
    else semantic_version.SimpleSpec(str(value))
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/semantic_version/base.py", line 647, in __init__
    self.clause = self._parse_to_clause(expression)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/semantic_version/base.py", line 1043, in _parse_to_clause
    return cls.Parser.parse(expression)
  File "/Users/rodrigo/.platformio/penv/lib/python3.9/site-packages/semantic_version/base.py", line 1063, in parse
    raise ValueError("Invalid simple block %r" % block)
ValueError: Invalid simple block 'v0.1.0'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues
```

### Expected Results

compile code succefull

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps =
    https://github.com/rodrigodornelles/3bc-lang
```

**Source file to reproduce issue:**
```cpp
#include <Arduino.h>
#include <3bc.h>

void setup() {
  // put your setup code here, to run once:
}

void loop() {
  // put your main code here, to run repeatedly:
}
```

### Additional info

I'm the maintainer of the library I'm trying to include.

**Comment by ivankravets** [comment]
> ValueError: Invalid simple block 'v0.1.0'

Please remove broken dependencies that do not conform to https://semver.org/

**Comment by RodrigoDornelles** [comment]
> Could you try to remove `.pio` folder from the project and build again?

It worked
