### ISSUE TITLE
trojan detected: Trojan:Script/Wacatac.H!ml

### ISSUE THREAD

**Issue by elgirsab** [platformio/platformio-core#4397]
hello Im trying to compile Marlin and using the auto build marlin add on.
windows reports me a trojan in the download file:  file: D:\Users\Admin\.platformio\.cache\downloads\e0a84d6cc648760d8ef551fd735eaadac23c1439
the name of the trojan is:   Trojan:Script/Wacatac.H!ml

in the Terminal I got following errors:

Error: Traceback (most recent call last):
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 37, in 
unpack
    with FileUnpacker(src) as fu:
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\unpack.py", line 138, in __enter__
    self._archiver = self.new_archiver(self.path)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\unpack.py", line 153, in new_archiver
    with open(path, "rb") as fp:
OSError: [Errno 22] Invalid argument: 'D:\\Users\\Admin\\.platformio\\.cache\\downloads\\e0a84d6cc648760d8ef551fd735eaadac23c1439'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\cli.py", line 71, in invoke
    return super().invoke(ctx)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\run\cli.py", line 144, in cli
    process_env(
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\run\cli.py", line 201, in process_env     
    result = {"env": name, "duration": time(), "succeeded": ep.process()}
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\run\processor.py", line 83, in process    
    install_project_env_dependencies(
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\commands\install.py", line 131, in install_project_env_dependencies
    _install_project_env_platform(project_env, options),
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\commands\install.py", line 148, in _install_project_env_platform
    PlatformPackageManager().install(
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\manager\platform.py", line 62, in 
install
    p.install_required_packages(force=force)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\platform\_packages.py", line 76, in install_required_packages
    self.install_package(name, force=force)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\platform\_packages.py", line 70, in install_package
    return self.pm.install(spec or self.get_package_spec(name), force=force)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 48, in 
install
    pkg = self._install(spec, skip_dependencies=skip_dependencies, force=force)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 98, in 
_install
    pkg = self.install_from_uri(spec.uri, spec)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 188, in install_from_uri
    self.unpack(dl_path, tmp_dir)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 42, in 
unpack
    with FileUnpacker(src) as fu:
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\unpack.py", line 138, in __enter__
    self._archiver = self.new_archiver(self.path)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\unpack.py", line 153, in new_archiver
    with open(path, "rb") as fp:
OSError: [Errno 22] Invalid argument: 'D:\\Users\\Admin\\.platformio\\.cache\\downloads\\e0a84d6cc648760d8ef551fd735eaadac23c1439'

============================================================

An unexpected error occurred. Further steps:
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

PS C:\Marlin-2.1.1> echo "done" >"D:\Users\Admin\AppData\Local\Temp\ipc"
PS C:\Marlin-2.1.1> platformio run -e STM32G0B1RE_btt
Processing STM32G0B1RE_btt (platform: ststm32@~14.1.0; board: marlin_STM32G0B1RE; framework: arduino)
---------------------------------------------------------------------------------------------------------------
Tool Manager: Installing https://github.com/stm32duino/Arduino_Core_STM32/archive/main.zip
Downloading  [####################################]  100%
Error: Traceback (most recent call last):
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 37, in 
unpack
    with FileUnpacker(src) as fu:
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\unpack.py", line 138, in __enter__
    self._archiver = self.new_archiver(self.path)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\unpack.py", line 153, in new_archiver
    with open(path, "rb") as fp:
OSError: [Errno 22] Invalid argument: 'D:\\Users\\Admin\\.platformio\\.cache\\downloads\\e0a84d6cc648760d8ef551fd735eaadac23c1439'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\cli.py", line 71, in invoke
    return super().invoke(ctx)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\run\cli.py", line 144, in cli
    process_env(
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\run\cli.py", line 201, in process_env     
    result = {"env": name, "duration": time(), "succeeded": ep.process()}
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\run\processor.py", line 83, in process    
    install_project_env_dependencies(
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\commands\install.py", line 131, in install_project_env_dependencies
    _install_project_env_platform(project_env, options),
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\commands\install.py", line 148, in _install_project_env_platform
    PlatformPackageManager().install(
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\manager\platform.py", line 62, in 
install
    p.install_required_packages(force=force)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\platform\_packages.py", line 76, in install_required_packages
    self.install_package(name, force=force)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\platform\_packages.py", line 70, in install_package
    return self.pm.install(spec or self.get_package_spec(name), force=force)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 48, in 
install
    pkg = self._install(spec, skip_dependencies=skip_dependencies, force=force)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 98, in 
_install
    pkg = self.install_from_uri(spec.uri, spec)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 188, in install_from_uri
    self.unpack(dl_path, tmp_dir)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 42, in 
unpack
    with FileUnpacker(src) as fu:
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\unpack.py", line 138, in __enter__
    self._archiver = self.new_archiver(self.path)
  File "D:\Users\Admin\.platformio\penv\lib\site-packages\platformio\package\unpack.py", line 153, in new_archiver
    with open(path, "rb") as fp:
OSError: [Errno 22] Invalid argument: 'D:\\Users\\Admin\\.platformio\\.cache\\downloads\\e0a84d6cc648760d8ef551fd735eaadac23c1439'

============================================================

I hope you can help me or suggest a forum that will help me to solve this issue
thank you!
Elgir

**Comment by ivankravets** [comment]
Please uninstall any espionage software (russian antiviruses, dr.web, Kaspersky, etc) that claims that PlatformIO is a trojan-type app.
