### ISSUE TITLE
Missing dependency zope.interface when running `pio remote agent start` on Fedora 36.

### ISSUE THREAD

**Issue by ramadhanafif** [platformio/platformio-core#4421]
What kind of issue is this?
### Configuration

**Operating system**:
Fedora 36

**PlatformIO Version**:
PlatformIO Core, version 6.1.4

### Description of problem
Missing dependency zope.interface when running `pio remote agent start`. The issue happens despite zope was listed as one of the installed dependencies (log below).
I have tried to install zope from pip3 but nothing changes. 
```
❯ pio remote agent start
Collecting twisted[tls]==22.1.0
  Using cached Twisted-22.1.0.tar.gz (3.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Automat>=0.8.0
  Using cached Automat-20.2.0.tar.gz (61 kB)
  Preparing metadata (setup.py) ... done
Collecting constantly>=15.1
  Using cached constantly-15.1.0.tar.gz (21 kB)
  Preparing metadata (setup.py) ... done
Collecting typing-extensions>=3.6.5
  Using cached typing_extensions-4.3.0.tar.gz (47 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting attrs>=19.2.0
  Using cached attrs-22.1.0.tar.gz (201 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting incremental>=21.3.0
  Using cached incremental-21.3.0.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting hyperlink>=17.1.1
  Using cached hyperlink-21.0.0.tar.gz (140 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting zope.interface>=4.4.2
  Using cached zope.interface-5.4.0.tar.gz (249 kB)
  Preparing metadata (setup.py) ... done
Collecting idna>=2.4
  Downloading idna-3.4.tar.gz (183 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.1/183.1 kB 2.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyopenssl>=16.0.0
  Using cached pyOpenSSL-22.0.0.tar.gz (178 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting service-identity>=18.1.0
  Using cached service-identity-21.1.0.tar.gz (40 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting six
  Using cached six-1.16.0.tar.gz (34 kB)
  Preparing metadata (setup.py) ... done
Collecting cryptography>=35.0
  Using cached cryptography-38.0.1.tar.gz (599 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyasn1
  Using cached pyasn1-0.4.8.tar.gz (146 kB)
  Preparing metadata (setup.py) ... done
Collecting pyasn1-modules
  Using cached pyasn1-modules-0.2.8.tar.gz (242 kB)
  Preparing metadata (setup.py) ... done
Collecting setuptools
  Using cached setuptools-65.3.0.tar.gz (2.6 MB)
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cffi>=1.12
  Using cached cffi-1.15.1.tar.gz (508 kB)
  Preparing metadata (setup.py) ... done
Collecting pycparser
  Using cached pycparser-2.21.tar.gz (170 kB)
  Preparing metadata (setup.py) ... done
Skipping wheel build for Automat, due to binaries being disabled for it.
Skipping wheel build for constantly, due to binaries being disabled for it.
Skipping wheel build for incremental, due to binaries being disabled for it.
Skipping wheel build for zope.interface, due to binaries being disabled for it.
Skipping wheel build for pyasn1, due to binaries being disabled for it.
Skipping wheel build for pyasn1-modules, due to binaries being disabled for it.
Skipping wheel build for six, due to binaries being disabled for it.
Skipping wheel build for cffi, due to binaries being disabled for it.
Skipping wheel build for pycparser, due to binaries being disabled for it.
Building wheels for collected packages: attrs, hyperlink, idna, pyopenssl, service-identity, typing-extensions, twisted, cryptography, setuptools
  Building wheel for attrs (pyproject.toml) ... done
  Created wheel for attrs: filename=attrs-22.1.0-py2.py3-none-any.whl size=58795 sha256=109cb40732ff4a219f460a4e9581821cf43ba1eada3ebb1f2a03b73337af5a56
  Stored in directory: /home/ramad/.cache/pip/wheels/00/7a/be/93f65a2acf9fd7865b67f3de1b1d2d43218723f6d1f6a6f31a
  Building wheel for hyperlink (pyproject.toml) ... done
  Created wheel for hyperlink: filename=hyperlink-21.0.0-py2.py3-none-any.whl size=74652 sha256=aa203645825679e4d3ac63ea44681c42b44effd0b3da491f0e47cfbe5b069756
  Stored in directory: /home/ramad/.cache/pip/wheels/27/99/ad/522464658bf1ac739aecc4e70e8a25ad963a973e9d6fb23c0a
  Building wheel for idna (pyproject.toml) ... done
  Created wheel for idna: filename=idna-3.4-py3-none-any.whl size=61538 sha256=0c58b616440aa15ef025051f5eab38dd94138aef4de25e7725251ad0e43ccdcb
  Stored in directory: /home/ramad/.cache/pip/wheels/31/13/f5/2443163e4579f82666cc4b171851ffd69b70066eb6c2ac94e5
  Building wheel for pyopenssl (pyproject.toml) ... done
  Created wheel for pyopenssl: filename=pyOpenSSL-22.0.0-py2.py3-none-any.whl size=55814 sha256=221ba978e4abccdc04f881b46972764b506b50f9e03a209bf5a42c24ada8f0d6
  Stored in directory: /home/ramad/.cache/pip/wheels/0f/cb/49/46fd89b835a0faf7514a859608cff316a1f8711b3f990a15a1
  Building wheel for service-identity (pyproject.toml) ... done
  Created wheel for service-identity: filename=service_identity-21.1.0-py2.py3-none-any.whl size=12592 sha256=9fa4005384fbee98bafe717a6237f5a92fb3eb4aac42d0392154dcb532c22e89
  Stored in directory: /home/ramad/.cache/pip/wheels/1f/71/30/334e6562bde8d538eefdf37ee5a0dd12f8976fd2fc348b66b3
  Building wheel for typing-extensions (pyproject.toml) ... done
  Created wheel for typing-extensions: filename=typing_extensions-4.3.0-py3-none-any.whl size=25596 sha256=804454722564b33d850b74f628871f3a928399e0c71b17fc8c5d073aa34d3753
  Stored in directory: /home/ramad/.cache/pip/wheels/ab/61/d0/d33395dde624d30e31bece18cd878b6915561a05eb18b70b63
  Building wheel for twisted (pyproject.toml) ... done
  Created wheel for twisted: filename=Twisted-22.1.0-py3-none-any.whl size=3082934 sha256=457fb7b6340e6988f0b3c0c8ef05d854aef7e11fb630b2091bc705b6c1e024b1
  Stored in directory: /home/ramad/.cache/pip/wheels/70/c8/c5/a00a93a57880601b911e520004d66d078f56b500f39b349417
  Building wheel for cryptography (pyproject.toml) ... done
  Created wheel for cryptography: filename=cryptography-38.0.1-cp310-cp310-linux_x86_64.whl size=2263423 sha256=21d8540253b4ca8af1541b0c7e7b4b281dbcebd5f9e47b2586cedd77415852e3
  Stored in directory: /home/ramad/.cache/pip/wheels/38/85/c2/e0e9a4846393723fc82538d119665e1c8cd78d919c9f9001e8
  Building wheel for setuptools (pyproject.toml) ... done
  Created wheel for setuptools: filename=setuptools-65.3.0-py3-none-any.whl size=1232493 sha256=7f79df468e7e3d471ad0173dc188939d1ea0327fada78e0f1782f811438f51d1
  Stored in directory: /home/ramad/.cache/pip/wheels/3a/88/3f/144cbe6ad6b46573f48d2c5b18fb3d27036e6506c9429c31ae
Successfully built attrs hyperlink idna pyopenssl service-identity typing-extensions twisted cryptography setuptools
Installing collected packages: pyasn1, incremental, constantly, typing-extensions, six, setuptools, pycparser, pyasn1-modules, idna, attrs, zope.interface, hyperlink, cffi, Automat, twisted, cryptography, service-identity, pyopenssl
  Running setup.py install for pyasn1 ... done
  Running setup.py install for incremental ... done
  Running setup.py install for constantly ... done
  Running setup.py install for six ... done
  Running setup.py install for pycparser ... done
  Running setup.py install for pyasn1-modules ... done
  Running setup.py install for zope.interface ... done
  Running setup.py install for cffi ... done
  Running setup.py install for Automat ... done
Successfully installed Automat-20.2.0 attrs-22.1.0 cffi constantly-15.1.0 cryptography-38.0.1 hyperlink-21.0.0 idna-3.4 incremental-21.3.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycparser-2.21 pyopenssl-22.0.0 service-identity-21.1.0 setuptools-65.3.0 six-1.16.0 twisted-22.1.0 typing-extensions-4.3.0 zope.interface
Error: Traceback (most recent call last):
  File "/home/ramad/.platformio/penv/lib64/python3.10/site-packages/platformio/__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/ramad/.platformio/penv/lib64/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ramad/.platformio/penv/lib64/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ramad/.platformio/penv/lib64/python3.10/site-packages/platformio/cli.py", line 71, in invoke
    return super().invoke(ctx)
  File "/home/ramad/.platformio/penv/lib64/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ramad/.platformio/penv/lib64/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ramad/.platformio/penv/lib64/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ramad/.platformio/penv/lib64/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ramad/.platformio/penv/lib64/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ramad/.platformio/penv/lib64/python3.10/site-packages/platformio/remote/cli.py", line 62, in remote_agent_start
    from platformio.remote.client.agent_service import RemoteAgentService
  File "/home/ramad/.platformio/penv/lib64/python3.10/site-packages/platformio/remote/client/agent_service.py", line 17, in <module>
    from twisted.logger import LogLevel  # pylint: disable=import-error
  File "/home/ramad/.platformio/packages/contrib-pysite/twisted/logger/__init__.py", line 93, in <module>
    from ._flatten import extractField
  File "/home/ramad/.platformio/packages/contrib-pysite/twisted/logger/_flatten.py", line 15, in <module>
    from ._interfaces import LogEvent
  File "/home/ramad/.platformio/packages/contrib-pysite/twisted/logger/_interfaces.py", line 10, in <module>
    from zope.interface import Interface
ModuleNotFoundError: No module named 'zope.interface'

```

#### Steps to Reproduce

1. `pio remote agent start`

**Comment by ramadhanafif** [comment]
Solved, turns out I was missing a python dependency. Solved by updating pio through pip, and it just installs some dependency that I didn't know about.

Update command: `pip install -U platformio`
