### ISSUE TITLE
Adafruit Libraries failing Installation

### ISSUE THREAD

**Issue by EkiciLP** [platformio/platformio-core#4466]
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:

**PlatformIO Version** (`6.1.5`):

### Description of problem
Issue when trying to add a library.
Also happens when using the Library manager.

#### Steps to Reproduce

1. Install an Adafruit Library (ex. Adafruit-MCP23017-Arduino-Library, https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library/) 

### Actual Results
```
Error: Traceback (most recent call last):
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\platformio\__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\platformio\cli.py", line 71, in invoke
    return super().invoke(ctx)
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\platformio\run\cli.py", line 144, in cli
    process_env(
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\platformio\run\cli.py", line 201, in process_env
    result = {"env": name, "duration": time(), "succeeded": ep.process()}
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\platformio\run\processor.py", line 83, in process
    install_project_env_dependencies(
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\platformio\package\commands\install.py", line 132, in install_project_env_dependencies
    _install_project_env_libraries(project_env, options),
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\platformio\package\commands\install.py", line 247, in _install_project_env_libraries
    env_lm.install(
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 48, in install
    pkg = self._install(spec, skip_dependencies=skip_dependencies, force=force)
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 92, in _install
    self.install_dependencies(pkg, print_header=False)
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 140, in install_dependencies
    self.install_dependency(dependency)
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\platformio\package\manager\library.py", line 89, in install_dependency
    not_builtin_conds.append(not self.is_builtin_lib(spec.name))
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\platformio\package\manager\library.py", line 120, in is_builtin_lib
    for storage in cls.get_builtin_libs():
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\platformio\util.py", line 56, in wrapper
    self.cache[key] = (time.time(), func(*args, **kwargs))
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\platformio\package\manager\library.py", line 105, in get_builtin_libs
    for storage in p.get_lib_storages():
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\platformio\platform\base.py", line 216, in get_lib_storages
    pkg = self.get_package(opts["package"])
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\platformio\platform\_packages.py", line 29, in get_package
    return self.pm.get_package(spec or self.get_package_spec(name))
  File "C:\Users\ekici\.platformio\penv\lib\site-packages\platformio\platform\_packages.py", line 21, in get_package_spec
    owner=self.packages[name].get("owner"),
KeyError: 'framework-stm32cube'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================
```
### Expected Results

Successful installation of the Library
### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico]
platform = raspberrypi
board = pico
framework = arduino
lib_deps = 
    ellsclytn/Rotary@0.0.0-alpha+sha.d1fef10209
    C:\Users\ekici\Documents\PlatformIO\Projects\grandMA3 Wing\lib\encoder-mcp23017.zip
    C:\Users\ekici\Documents\PlatformIO\Projects\grandMA3 Wing\lib\mcp23017.zip

```

**Source file to reproduce issue:**
```cpp
#include <Arduino.h>

void setup(){

}


void loop() {
}
```

**Comment by ivankravets** [comment]
> KeyError: 'framework-stm32cube'
> ....
> platform = raspberrypi


That is impossible. Did you modify dev-platform files? If yes, please remove the `C:\Users\ekici\.platformio\platforms` folder and build the project again. If it does not work, please forward it to https://community.platformio.org/ and our awesome community will help you.
