### ISSUE TITLE
Python errors?

### ISSUE THREAD

**Issue by shardin39** [platformio/platformio-core#4514]
What kind of issue is this?
While working on a program that was compiling correctly the following issues began.
Reinstalled current version PIO;
Installed pre-release version 3+ PIO;
Reinstalled/updated Python;

Same errors

Processing d1_mini_pro (platform: espressif8266; board: d1_mini_pro; framework: arduino)
---------------------------------------------------------------------------------------------------------------Removing unused dependencies...
Error: Traceback (most recent call last):
  File "C:\Users\steve\.platformio\penv\lib\site-packages\platformio\__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "C:\Users\steve\.platformio\penv\lib\site-packages\click\core.py", line 1130, in __call__    
    return self.main(*args, **kwargs)
  File "C:\Users\steve\.platformio\penv\lib\site-packages\click\core.py", line 1055, in main        
    rv = self.invoke(ctx)
  File "C:\Users\steve\.platformio\penv\lib\site-packages\platformio\cli.py", line 71, in invoke    
    return super().invoke(ctx)
  File "C:\Users\steve\.platformio\penv\lib\site-packages\click\core.py", line 1657, in invoke      
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\steve\.platformio\penv\lib\site-packages\click\core.py", line 1404, in invoke      
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\steve\.platformio\penv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\steve\.platformio\penv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\steve\.platformio\penv\lib\site-packages\platformio\run\cli.py", line 144, in cli
    process_env(
  File "C:\Users\steve\.platformio\penv\lib\site-packages\platformio\run\cli.py", line 201, in process_env     
    result = {"env": name, "duration": time(), "succeeded": ep.process()}
  File "C:\Users\steve\.platformio\penv\lib\site-packages\platformio\run\processor.py", line 83, in process    
    install_project_env_dependencies(
  File "C:\Users\steve\.platformio\penv\lib\site-packages\platformio\package\commands\install.py", line 132, in install_project_env_dependencies
    _install_project_env_libraries(project_env, options),
  File "C:\Users\steve\.platformio\penv\lib\site-packages\platformio\package\commands\install.py", line 204, in _install_project_env_libraries
    _uninstall_project_unused_libdeps(project_env, options)
  File "C:\Users\steve\.platformio\penv\lib\site-packages\platformio\package\commands\install.py", line 280, in _uninstall_project_unused_libdeps
    lm.uninstall(spec)
  File "C:\Users\steve\.platformio\penv\lib\site-packages\platformio\package\manager\_uninstall.py", line 29, in uninstall
    return self._uninstall(spec, skip_dependencies)
  File "C:\Users\steve\.platformio\penv\lib\site-packages\platformio\package\manager\_uninstall.py", line 34, in _uninstall
    pkg = self.get_package(spec)
  File "C:\Users\steve\.platformio\penv\lib\site-packages\platformio\package\manager\base.py", line 263, in get_package
    spec = self.ensure_spec(spec)
  File "C:\Users\steve\.platformio\penv\lib\site-packages\platformio\package\manager\base.py", line 133, in ensure_spec
    return spec if isinstance(spec, PackageSpec) else PackageSpec(spec)
  File "C:\Users\steve\.platformio\penv\lib\site-packages\platformio\package\meta.py", line 184, in __init__   
    self._parse(self.raw)
  File "C:\Users\steve\.platformio\penv\lib\site-packages\platformio\package\meta.py", line 291, in _parse     
    raw = parser(raw)
  File "C:\Users\steve\.platformio\penv\lib\site-packages\platformio\package\meta.py", line 316, in _parse_requirements
    self.requirements = tokens[1].strip()
  File "C:\Users\steve\.platformio\penv\lib\site-packages\platformio\package\meta.py", line 231, in requirements
    else semantic_version.SimpleSpec(str(value))
  File "C:\Users\steve\.platformio\penv\lib\site-packages\semantic_version\base.py", line 647, in __init__     
    self.clause = self._parse_to_clause(expression)
  File "C:\Users\steve\.platformio\penv\lib\site-packages\semantic_version\base.py", line 1043, in _parse_to_clause
    return cls.Parser.parse(expression)
  File "C:\Users\steve\.platformio\penv\lib\site-packages\semantic_version\base.py", line 1063, in parse       
    raise ValueError("Invalid simple block %r" % block)
ValueError: Invalid simple block ''

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

 *  The terminal process "C:\Users\steve\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**

[env:d1_mini_pro]
platform = espressif8266
board = d1_mini_pro
framework = arduino

**Source file to reproduce issue:**
/ main.cpp SALT II.  
// measure salt level in softener tank ~ every 24hrs, if at minimum, send e-mail

#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <ESP_Mail_Client.h>
#include "BlockNot.h"

#include <creditials.h>
#include <global.h>

// Set up objects
BlockNot Daily(86400,SECONDS);      // timer object set to 24 hours
SMTPSession smtp;                   // The SMTP Session object used for Email sending
ESP_Mail_Session session;           // Declare the session config data
SMTP_Message message;               // Declare the message class 

// Foward declare
bool  start_WiFi();
float Measure();
int   send_Email(String Emsg);
bool  discon_Wifi();
void  smtpCallback(SMTP_Status status);    // Callback function to get the Email sending status 

float duration, Level;

void setup() 
{
  //Set the callback function to get the sending results 
  smtp.callback(smtpCallback);
  // Setup serial port
  Serial.begin(115200);
  Serial.println();
  pinMode(Glo::trigPin, OUTPUT);
  pinMode(Glo::echoPin, INPUT);
}
void loop() 
{
  // put your main code here, to run repeatedly:
  if(Daily.triggered())   // it has been 24 hours, check the salt level
  {
    bool OK = false;
    int tries = 0;
    while(!OK and tries < 10 )
    {
      OK = start_WiFi();
      tries++;
    }
    Daily.reset();        // reset 24 hour timer
    if (OK)               // If OK WiFi has connected
    {
      Level = Measure();    // read the salt level
      // if Level <= 100Cm  level OK
      // if Level >= 200Cm  level OK but getting low
      // if Level >= 300Cm  Level is low, GET SALT
      if (Level <= 200)     // level OK
      {
          OK = send_Email(String(Glo::Email[0]) + String(Level,0));   // for testing only
      }
      else if(Level >= 201 and OK) // level OK but getting low send a message
      {
          OK = send_Email(String(Glo::Email[1]) + String(Level,0));
      }
      else if(Level > 300 and OK)  // Level is low, GET SALT
      {
          OK = send_Email(String(Glo::Email[2])+ String(Level,0));
      }
      else if (OK)
      { // the reading is not in the proper range!!
          OK = send_Email(String(Glo::Email[3]) + String(Level,0));
      }
    }
    if(!OK){Serial.println("Email not sent");}
    OK = discon_Wifi();
  }
}

/**************************************
   Sign on to Wifi
   Returns true for success 
***************************************/
bool start_WiFi()
// Begin WiFi
{
  int tries = 0;
  WiFi.begin(cred::WIFI_SSID, cred::WIFI_PASS); 
  // Connecting to WiFi...
  Serial.print("Connecting to " + cred::WIFI_SSID);
  // Loop continuously while WiFi is not connected
  while (WiFi.status() != WL_CONNECTED and tries < 50)
  {
    tries++;
    delay(100);
    Serial.print(".");
    if (tries > 50)
    {
      return false;
    }
  }
  return true;
}
/**************************************
   HC-SR04 ultrasonic measuring 
   returns the distance in Cm 
***************************************/
float Measure()
{
  digitalWrite(Glo::trigPin, LOW);            // Write timed pulses to the HC-SR04 Trigger Pin
  delayMicroseconds(2);
  digitalWrite(Glo::trigPin, HIGH);
  delayMicroseconds(10);
  digitalWrite(Glo::trigPin, LOW);

  duration = pulseIn(Glo::echoPin, HIGH);     // Measure the response from the HC-SR04 Echo Pin
  return (duration / 2) * 0.0343;             // Determine distance from duration
}                                             // Use 343 metres per second as speed of sound

/**************************************
  Disconnectes WiFi connection after
  sending e-mail.  Returns true for success
***************************************/
bool discon_Wifi()
{
  return true;
}

/**************************************
   Format and send e-mail to Gmail.com
   Returns true for success
***************************************/
int send_Email(String Emsg)
{
  // Set the session config 
  session.server.host_name = cred::SMPT_Ser;
  session.server.port = cred::SMPT_Port;
  session.login.email = cred::Gmail_User;
  session.login.password = cred::Gmail_pass;
  session.login.user_domain = "";
  //Set the message headers 
  message.sender.name = "Salt II";
  message.sender.email = cred::Gmail_User;
  message.subject = "Salt II Level Report";
  message.addRecipient("Steve", cred::RECIPIENT_EMAIL);
  //Send raw text message
  message.text.content = Emsg.c_str();
  message.text.charSet = "us-ascii";
  message.text.transfer_encoding = Content_Transfer_Encoding::enc_7bit;
  
  message.priority = esp_mail_smtp_priority::esp_mail_smtp_priority_low;
  message.response.notify = (esp_mail_smtp_notify_success) | (esp_mail_smtp_notify_failure) | (esp_mail_smtp_notify_delay);

  
  /* Set the custom message header */
  message.addHeader("Message-ID: <abcde.fghij@gmail.com>");

 // Connect to server with the session config 
  if (!smtp.connect(&session)){return 9;}

  // Start sending Email and close the session 
  if (!MailClient.sendMail(&smtp, &message))
  {  
    Serial.println("Error sending Email, " + smtp.errorReason());
    return 99;
  }
  return 1;
}

**Comment by ivankravets** [comment]
Do you have a broken dependency declared in platformio.ini?

**Comment by shardin39** [comment]
Hi Ivan; 

Worked on this most of the day without results. Then, it started working. No idea why... 

Thanks for the reply. 

Steve

**Comment by ivankravets** [comment]
Please remove `.pio` folder in the project root. The problem should be fixed.

**Comment by shardin39** [comment]
Hi Ivan; 

I will keep that in mind should things go south again. 

Thanks! 

Steve
