### ISSUE TITLE
not compiling

### ISSUE THREAD

**Issue by PhoenixLegen** [platformio/platformio-core#4552]
Processing esp32doit-devkit-v1 (platform: espressif32; board: esp32doit-devkit-v1; framework: arduino)
--------------------------------------------------------------------------------------------------------------
Error: Traceback (most recent call last):
  File "C:\Users\Sudhir\.platformio\penv\lib\site-packages\platformio\__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "C:\Users\Sudhir\.platformio\penv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Sudhir\.platformio\penv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Sudhir\.platformio\penv\lib\site-packages\platformio\cli.py", line 71, in invoke
    return super().invoke(ctx)
  File "C:\Users\Sudhir\.platformio\penv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Sudhir\.platformio\penv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Sudhir\.platformio\penv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Sudhir\.platformio\penv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Sudhir\.platformio\penv\lib\site-packages\platformio\run\cli.py", line 147, in cli
    process_env(
  File "C:\Users\Sudhir\.platformio\penv\lib\site-packages\platformio\run\cli.py", line 204, in process_env   
    result = {"env": name, "duration": time(), "succeeded": ep.process()}
  File "C:\Users\Sudhir\.platformio\penv\lib\site-packages\platformio\run\processor.py", line 83, in process  
    install_project_env_dependencies(
  File "C:\Users\Sudhir\.platformio\penv\lib\site-packages\platformio\package\commands\install.py", line 132, in install_project_env_dependencies
    _install_project_env_libraries(project_env, options),
  File "C:\Users\Sudhir\.platformio\penv\lib\site-packages\platformio\package\commands\install.py", line 241, in _install_project_env_libraries
    spec = PackageSpec(library)
  File "C:\Users\Sudhir\.platformio\penv\lib\site-packages\platformio\package\meta.py", line 184, in __init__ 
    self._parse(self.raw)
  File "C:\Users\Sudhir\.platformio\penv\lib\site-packages\platformio\package\meta.py", line 291, in _parse   
    raw = parser(raw)
  File "C:\Users\Sudhir\.platformio\penv\lib\site-packages\platformio\package\meta.py", line 316, in _parse_requirements
    self.requirements = tokens[1].strip()
  File "C:\Users\Sudhir\.platformio\penv\lib\site-packages\platformio\package\meta.py", line 231, in requirements
    else semantic_version.SimpleSpec(str(value))
  File "C:\Users\Sudhir\.platformio\penv\lib\site-packages\semantic_version\base.py", line 647, in __init__   
    self.clause = self._parse_to_clause(expression)
  File "C:\Users\Sudhir\.platformio\penv\lib\site-packages\semantic_version\base.py", line 1043, in _parse_to_clause
    return cls.Parser.parse(expression)
  File "C:\Users\Sudhir\.platformio\penv\lib\site-packages\semantic_version\base.py", line 1063, in parse     
    raise ValueError("Invalid simple block %r" % block)
ValueError: Invalid simple block '^1.1.6yyy'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
> ValueError: Invalid simple block '^1.1.6yyy'

Please remove `^` before the version name.
