### ISSUE TITLE
pio remote agent throw's exception on raspberry pi's (pio core version 6.1.7b2)

### ISSUE THREAD

**Issue by mrcamilletti** [platformio/platformio-core#4607]
I'm having a similar issue as this one (https://github.com/platformio/platformio-core/issues/3652#issue-693508852) using the new version (core version 6.1.7b2). Remote agent was working fine before, and after some days (an update I suppose) this happened.

### Configuration
```
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

$ pio system info
--------------------------  -----------------------------------------
PlatformIO Core             6.1.7b2
Python                      3.7.3-final.0
System Type                 linux_armv7l
Platform                    Linux-5.10.103-v7l+-armv7l-with-glibc2.28
File System Encoding        utf-8
Locale Encoding             UTF-8
PlatformIO Core Directory   /home/pi/.platformio
PlatformIO Core Executable  /home/pi/.platformio/penv/bin/platformio
Python Executable           /home/pi/.platformio/penv/bin/python
Global Libraries            0
Development Platforms       0
Tools & Toolchains          1
--------------------------  -----------------------------------------
```

### Description
After running `pio remote agent start` the process tries to install libraries and fails running `Collecting attrs>=19.2.0 (from twisted==22.1.0)`. 

### Steps to reproduce
- Install required libraries: $ sudo apt install python3-dev libffi-dev libssl-dev
- Clean install of platformio core using installer-script [Super-Quick (macOS / Linux)](https://docs.platformio.org/en/latest/core/installation/methods/installer-script.html#id1)
- pio upgrade --dev
- pio account login
- pio remote agent start

### Result
```
Please wait while upgrading PlatformIO...
PlatformIO has been successfully upgraded to 6.1.7b2!

**********************************************************************************************************************************************************************************************************************************************
If you like PlatformIO, please:
- follow us on Twitter to stay up-to-date on the latest project news > https://twitter.com/PlatformIO_Org
- star it on GitHub > https://github.com/platformio/platformio
- try PlatformIO IDE for embedded development > https://platformio.org/platformio-ide
**********************************************************************************************************************************************************************************************************************************************

Tool Manager: Installing platformio/contrib-pysite @ ~2.37.0
Unpacking  [####################################]  100%          
Tool Manager: contrib-pysite@2.37.191020 has been installed!
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting twisted==22.1.0
  Using cached Twisted-22.1.0-py3-none-any.whl
Collecting cryptography<35.0.0,>=3.3
  Using cached cryptography-3.4.8-cp37-cp37m-linux_armv7l.whl
Collecting pyopenssl<=21.0.0,>=16.0.0
  Using cached pyOpenSSL-21.0.0-py2.py3-none-any.whl
Collecting service_identity<=21.1.0,>=18.1.0
  Using cached service_identity-21.1.0-py2.py3-none-any.whl
Collecting zope.interface>=4.4.2 (from twisted==22.1.0)
  Using cached zope.interface-6.0.tar.gz (246 kB)
  Preparing metadata (setup.py) ... done
Collecting constantly>=15.1 (from twisted==22.1.0)
  Using cached constantly-15.1.0.tar.gz (21 kB)
  Preparing metadata (setup.py) ... done
Collecting incremental>=21.3.0 (from twisted==22.1.0)
  Using cached incremental-22.10.0-py2.py3-none-any.whl
Collecting Automat>=0.8.0 (from twisted==22.1.0)
  Using cached Automat-22.10.0.tar.gz (59 kB)
  Preparing metadata (setup.py) ... done
Collecting hyperlink>=17.1.1 (from twisted==22.1.0)
  Using cached hyperlink-21.0.0-py2.py3-none-any.whl
Collecting attrs>=19.2.0 (from twisted==22.1.0)
  Using cached attrs-23.1.0.tar.gz (212 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [203 lines of output]
      Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple, https://www.piwheels.org/simple
      Collecting hatchling
        Using cached hatchling-1.14.1.tar.gz (55 kB)
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: still running...
        Installing backend dependencies: finished with status 'error'
        error: subprocess-exited-with-error
      
        × pip subprocess to install backend dependencies did not run successfully.
        │ exit code: 1
        ╰─> [180 lines of output]
            Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple, https://www.piwheels.org/simple, https://www.piwheels.org/simple
            Collecting tomli>=1.2.2
              Using cached tomli-2.0.1.tar.gz (15 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting trove-classifiers
              Using cached trove-classifiers-2023.4.22.tar.gz (15 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Installing backend dependencies: started
              Installing backend dependencies: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting editables>=0.3
              Using cached editables-0.3.tar.gz (4.7 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Installing backend dependencies: started
              Installing backend dependencies: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting pathspec>=0.10.1
              Using cached pathspec-0.11.1.tar.gz (45 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting pluggy>=1.0.0
              Using cached pluggy-1.0.0.tar.gz (51 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'error'
              error: subprocess-exited-with-error
      
              × pip subprocess to install build dependencies did not run successfully.
              │ exit code: 1
              ╰─> [124 lines of output]
                  Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple, https://www.piwheels.org/simple, https://www.piwheels.org/simple, https://www.piwheels.org/simple
                  Collecting setuptools
                    Using cached setuptools-67.7.2-py3-none-any.whl
                  Collecting setuptools-scm
                    Using cached setuptools_scm-7.1.0.tar.gz (71 kB)
                    Installing build dependencies: started
                    Installing build dependencies: finished with status 'done'
                    Getting requirements to build wheel: started
                    Getting requirements to build wheel: finished with status 'done'
                    Installing backend dependencies: started
                    Installing backend dependencies: finished with status 'done'
                    Preparing metadata (pyproject.toml): started
                    Preparing metadata (pyproject.toml): finished with status 'done'
                  Collecting wheel
                    Using cached wheel-0.40.0-py3-none-any.whl
                  Collecting packaging>=20.0 (from setuptools-scm)
                    Using cached packaging-23.1-py3-none-any.whl
                  Collecting typing-extensions (from setuptools-scm)
                    Using cached typing_extensions-4.5.0-py3-none-any.whl
                  Collecting tomli>=1.0.0 (from setuptools-scm)
                    Using cached tomli-2.0.1.tar.gz (15 kB)
                    Installing build dependencies: started
                    Installing build dependencies: finished with status 'done'
                    Getting requirements to build wheel: started
                    Getting requirements to build wheel: finished with status 'done'
                    Preparing metadata (pyproject.toml): started
                    Preparing metadata (pyproject.toml): finished with status 'done'
                  Collecting importlib-metadata (from setuptools-scm)
                    Using cached importlib_metadata-6.6.0.tar.gz (53 kB)
                    Installing build dependencies: started
                    Installing build dependencies: finished with status 'error'
                    error: subprocess-exited-with-error
      
                    × pip subprocess to install build dependencies did not run successfully.
                    │ exit code: 2
                    ╰─> [78 lines of output]
                        Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple, https://www.piwheels.org/simple, https://www.piwheels.org/simple, https://www.piwheels.org/simple, https://www.piwheels.org/simple
                        Collecting setuptools>=56
                          Using cached setuptools-67.7.2-py3-none-any.whl
                        Collecting setuptools_scm[toml]>=3.4.1
                          Using cached setuptools_scm-7.1.0.tar.gz (71 kB)
                          Installing build dependencies: started
                          Installing build dependencies: finished with status 'done'
                          Getting requirements to build wheel: started
                          Getting requirements to build wheel: finished with status 'done'
                          Installing backend dependencies: started
                          Installing backend dependencies: finished with status 'done'
                          Preparing metadata (pyproject.toml): started
                          Preparing metadata (pyproject.toml): finished with status 'done'
                        Collecting packaging>=20.0 (from setuptools_scm[toml]>=3.4.1)
                          Using cached packaging-23.1-py3-none-any.whl
                        Collecting typing-extensions (from setuptools_scm[toml]>=3.4.1)
                          Using cached typing_extensions-4.5.0-py3-none-any.whl
                        Collecting tomli>=1.0.0 (from setuptools_scm[toml]>=3.4.1)
                          Using cached tomli-2.0.1.tar.gz (15 kB)
                          Installing build dependencies: started
                          Installing build dependencies: finished with status 'done'
                          Getting requirements to build wheel: started
                          Getting requirements to build wheel: finished with status 'done'
                          Preparing metadata (pyproject.toml): started
                          Preparing metadata (pyproject.toml): finished with status 'done'
                        Collecting importlib-metadata (from setuptools_scm[toml]>=3.4.1)
                          Using cached importlib_metadata-6.6.0.tar.gz (53 kB)
                        ERROR: Exception:
                        Traceback (most recent call last):
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
                            status = run_func(*args)
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
                            return func(self, options, args)
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 378, in run
                            reqs, check_supported_wheels=not options.target_dir
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 93, in resolve
                            collected.requirements, max_rounds=limit_how_complex_resolution_can_be
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
                            state = resolution.resolve(requirements, max_rounds=max_rounds)
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 427, in resolve
                            failure_causes = self._attempt_to_pin_criterion(name)
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 239, in _attempt_to_pin_criterion
                            criteria = self._get_updated_criteria(candidate)
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 230, in _get_updated_criteria
                            self._add_to_criteria(criteria, requirement, parent=candidate)
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
                            if not criterion.candidates:
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
                            return bool(self._sequence)
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
                            return any(self)
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
                            return (c for c in iterator if id(c) not in self._incompatible_ids)
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
                            candidate = func()
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 211, in _make_candidate_from_link
                            version=version,
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 299, in __init__
                            version=version,
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
                            self.dist = self._prepare()
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
                            dist = self._prepare_distribution()
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
                            return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
                            return self._prepare_linked_requirement(req, parallel_builds)
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 636, in _prepare_linked_requirement
                            self.check_build_deps,
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 68, in _get_prepared_distribution
                            with build_tracker.track(req):
                          File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
                            return next(self.gen)
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_internal/operations/build/build_tracker.py", line 122, in track
                            self.add(req)
                          File "/home/pi/.platformio/penv/lib/python3.7/site-packages/pip/_internal/operations/build/build_tracker.py", line 92, in add
                            raise LookupError(message)
                        LookupError: https://files.pythonhosted.org/packages/0b/1f/9de392c2b939384e08812ef93adf37684ec170b5b6e7ea302d9f163c2ea0/importlib_metadata-6.6.0.tar.gz (from https://pypi.org/simple/importlib-metadata/) (requires-python:>=3.7) is already being built: importlib-metadata from https://files.pythonhosted.org/packages/0b/1f/9de392c2b939384e08812ef93adf37684ec170b5b6e7ea302d9f163c2ea0/importlib_metadata-6.6.0.tar.gz (from setuptools-scm)
                        [end of output]
      
                    note: This error originates from a subprocess, and is likely not a problem with pip.
                  error: subprocess-exited-with-error
      
                  × pip subprocess to install build dependencies did not run successfully.
                  │ exit code: 2
                  ╰─> See above for output.
      
                  note: This error originates from a subprocess, and is likely not a problem with pip.
                  [end of output]
      
              note: This error originates from a subprocess, and is likely not a problem with pip.
            error: subprocess-exited-with-error
      
            × pip subprocess to install build dependencies did not run successfully.
            │ exit code: 1
            ╰─> See above for output.
      
            note: This error originates from a subprocess, and is likely not a problem with pip.
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error
      
      × pip subprocess to install backend dependencies did not run successfully.
      │ exit code: 1
      ╰─> See above for output.
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Error: 

Please ensure that the next packages are installed:

sudo apt install python3-dev libffi-dev libssl-dev
```

**Comment by maxgerhardt** [comment]
May be related: https://github.com/pypa/pip/issues/5739 and https://github.com/pypa/pip/issues/11363

**Comment by ivankravets** [comment]
Now dependencies will be built on the target side. Please re-test with `pio upgrade --dev`. Does it work now?

**Comment by mrcamilletti** [comment]
> Now dependencies will be built on the target side. Please re-test with `pio upgrade --dev`. Does it work now?

Yes! it works now, thanks!
