### ISSUE TITLE
Cannot add dependency through `platformio.ini`

### ISSUE THREAD

**Issue by Bolderaysky** [platformio/platformio-core#4675]
What kind of issue is this?

- [x] **PlatformIO Core**.

------------------------------------------------------------------

### Configuration

**Operating system**: `Arch Linux 6.3.8-arch1-1`

**PlatformIO Version** (`platformio --version`): `PlatformIO Core, version 6.1.7`

### Description of problem

When adding `roseleblood/mini Thread @ ^2.28.8906.7` as dependency in `platformio.ini`, platformio cannot handle it and throw

```
Error: Traceback (most recent call last):
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/platformio/__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
    ^^^^^
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/platformio/cli.py", line 70, in invoke
    return super().invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/platformio/project/commands/init.py", line 104, in project_init_cmd
    install_project_dependencies(
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/platformio/package/commands/install.py", line 106, in install_project_dependencies
    already_up_to_date = not install_project_env_dependencies(env, options)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/platformio/package/commands/install.py", line 132, in install_project_env_dependencies
    _install_project_env_libraries(project_env, options),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/platformio/package/commands/install.py", line 204, in _install_project_env_libraries
    _uninstall_project_unused_libdeps(project_env, options)
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/platformio/package/commands/install.py", line 280, in _uninstall_project_unused_libdeps
    lm.uninstall(spec)
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/platformio/package/manager/_uninstall.py", line 29, in uninstall
    return self._uninstall(spec, skip_dependencies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/platformio/package/manager/_uninstall.py", line 34, in _uninstall
    pkg = self.get_package(spec)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/platformio/package/manager/base.py", line 263, in get_package
    spec = self.ensure_spec(spec)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/platformio/package/manager/base.py", line 133, in ensure_spec
    return spec if isinstance(spec, PackageSpec) else PackageSpec(spec)
                                                      ^^^^^^^^^^^^^^^^^
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/platformio/package/meta.py", line 183, in __init__
    self._parse(self.raw)
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/platformio/package/meta.py", line 290, in _parse
    raw = parser(raw)
          ^^^^^^^^^^^
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/platformio/package/meta.py", line 315, in _parse_requirements
    self.requirements = tokens[1].strip()
    ^^^^^^^^^^^^^^^^^
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/platformio/package/meta.py", line 230, in requirements
    else semantic_version.SimpleSpec(str(value))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/semantic_version/base.py", line 647, in __init__
    self.clause = self._parse_to_clause(expression)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/semantic_version/base.py", line 1043, in _parse_to_clause
    return cls.Parser.parse(expression)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yourdeath/.platformio/penv/lib/python3.11/site-packages/semantic_version/base.py", line 1063, in parse
    raise ValueError("Invalid simple block %r" % block)
ValueError: Invalid simple block '^2.28.8906.7'
```

#### Steps to Reproduce

1. Create new project for `esp32dev` board with `esp-idf` framework
2. Add `roseleblood/mini Thread @ ^2.28.8906.7` into platformio 

### Actual Results
Error from above is thrown.

### Expected Results
Library is downloaded, unpacked and can be used.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
board_build.partitions = part.csv
lib_deps =
    roseleblood/mini Thread @ ^2.28.8906.7
```

**Comment by ivankravets** [comment]
Please visit https://registry.platformio.org/libraries/roseleblood/mini%20Thread/installation for updated installation instructions. We have fixed it. Please don't forget to press Ctrl+R on the web page.

It should be 
```ini
lib_deps =
    roseleblood/mini Thread @ ^2.28.8906
```
