### ISSUE TITLE
Chinese Windows environment extra_scripts call npm failed

### ISSUE THREAD

**Issue by yunyizhi** [platformio/platformio-core#4736]
What kind of issue is this?

- [ ] **PlatformIO Core**.
     Chinese Windows environment. Create a new Vue project in the web folder under the platformio project. Using the Python script specified in extra_scripts to call the npm build .The following exception occurs:
 ```tex
C:\Users\immor\.platformio\penv\Scripts\pio run -t buildWeb
Warning! Ignore unknown configuration option `npm` in section [env:nodemcu-32s]
Processing nodemcu-32s (platform: espressif32; board: nodemcu-32s; framework: arduino)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/nodemcu-32s.html
PLATFORM: Espressif 32 (6.3.2) > NodeMCU-32S
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.20009.0 (2.0.9) 
 - tool-esptoolpy @ 1.40501.0 (4.5.1) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 35 compatible libraries
Scanning dependencies...
Dependency Graph
|-- FS @ 2.0.0
|-- SPIFFS @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- WebServer @ 2.0.0
|-- WiFi @ 2.0.0
Building in release mode
run_npm(["buildWeb"], [])
build web
Active code page: 65001

up to date, audited 26 packages in 1s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> web@0.0.0 build
> vite build

vite v4.4.9 building for production...
transforming...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\immor\.platformio\penv\lib\site-packages\platformio\proc.py", line 48, in run
    self.do_reading()
  File "C:\Users\immor\.platformio\penv\lib\site-packages\platformio\proc.py", line 103, in do_reading
    self.line_callback(line)
  File "C:\Users\immor\.platformio\penv\lib\site-packages\platformio\platform\_run.py", line 138, in _on_stdout_line
    self._echo_line(line, level=1)
  File "C:\Users\immor\.platformio\penv\lib\site-packages\platformio\platform\_run.py", line 159, in _echo_line
    click.secho(line, fg=fg, err=level > 1, nl=False)
  File "C:\Users\immor\.platformio\penv\lib\site-packages\platformio\__main__.py", line 90, in <lambda>
    click.secho = lambda *args, **kwargs: _safe_echo(1, *args, **kwargs)
  File "C:\Users\immor\.platformio\penv\lib\site-packages\platformio\__main__.py", line 83, in _safe_echo
    click_echo_origin[origin](*args, **kwargs)
  File "C:\Users\immor\.platformio\penv\lib\site-packages\click\termui.py", line 634, in secho
    return echo(message, file=file, nl=nl, err=err, color=color)
  File "C:\Users\immor\.platformio\penv\lib\site-packages\click\utils.py", line 318, in echo
    file.write(out)  # type: ignore
UnicodeEncodeError: 'gbk' codec can't encode character '\u2713' in position 0: illegal multibyte sequence
========================= [SUCCESS] Took 6.63 seconds =========================
 ```
* platfromio.ini
 ```ini
[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
upload_speed = 921600
monitor_speed = 115200
build_flags =
    -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
extra_scripts = build_web/build.py
npm = npm
 ```
* build.py
```python
import os
Import("env")
npm = env.GetProjectOption("npm")

def run_npm(*args, **kwargs):
    print("build web")
    os.system("chcp 65001 && cd web && {npm} install && {npm} run build".format(npm=npm))


env.AddCustomTarget(
    name="buildWeb",
    dependencies=None,
    actions=run_npm,
    title="Build vue",
    description="build web"
)
```

Using other Python projects on the same PC can successfully run the following
`os.system("chcp 65001 && cd web && {npm} install && {npm} run build".format(npm=npm))`

**Comment by yunyizhi** [comment]
Some of the characters are shown below
![image](https://github.com/platformio/platformio-core/assets/64545732/512d07c0-4959-41de-94ad-ba8c97de714a)
Some characters are not in the GBK character set. I used various ways to set the character set for the 'extra_scripts' of Platformio in the Chinese Windows environment, including command output and default character set, but none of this solved this problem. Finally, in my command to direct the output to a file, this problem is solved.
`os.system("cd web && {npm} install strip-ansi && {npm} run build >build.log".format(npm=npm))`
