### ISSUE TITLE
Install on ubuntu: Failed to open the app

### ISSUE THREAD

**Issue by mshenouda** [platformio/platformio-core#4764]
AFTER INSTALLING THE APP with sudo apt install platformio
I tried to build some program, yet when entering platformio [command], I received that error

Traceback (most recent call last):
  File "/usr/bin/platformio", line 33, in <module>
    sys.exit(load_entry_point('platformio==4.3.4', 'console_scripts', 'platformio')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/platformio", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/platformio/__main__.py", line 66, in <module>
    @cli.resultcallback()
     ^^^^^^^^^^^^^^^^^^
AttributeError: 'PlatformioCLI' object has no attribute 'resultcallback'. Did you mean: 'result_callback'?

**Comment by SakuraPuare** [comment]
do not use `sudo apt install platformio` to install platformio

using 
```bash
curl -fsSL -o get-platformio.py https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py
python3 get-platformio.py
```

according https://docs.platformio.org/en/latest/core/installation/methods/installer-script.html

**Comment by ivankravets** [comment]
@SakuraPuare , thanks for the solution!

**Comment by NathanLibutan** [comment]
> do not use `sudo apt install platformio` to install platformio
> 
> using
> 
> ```shell
> curl -fsSL -o get-platformio.py https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py
> python3 get-platformio.py
> ```
> 
> according https://docs.platformio.org/en/latest/core/installation/methods/installer-script.html

I'm running into this same problem but I'm using curl... Not sure if anyone else has had the same issue?

**Comment by ivankravets** [comment]
See https://github.com/platformio/platformio-core-installer/issues/85

**Comment by Fasrad** [comment]
I'm having this problem now on Linux Mint. A year ago I was able to compile programs fine (marlin firmware for 3d printers), now I can't. Is there any resolution? 

`Traceback (most recent call last):
  File "/home/chaz/.local/bin/platformio", line 5, in <module>
    from platformio.__main__ import main
  File "/usr/lib/python3/dist-packages/platformio/__main__.py", line 66, in <module>
    @cli.resultcallback()
     ^^^^^^^^^^^^^^^^^^
AttributeError: 'PlatformioCLI' object has no attribute 'resultcallback'. Did you mean: 'result_callback'?`

**Comment by shekhov** [comment]
Please reopen the issue, I having the same problem. Installed the core via script, and then any command throws me an error

```log

PlatformIO Core has been successfully installed into an isolated environment `/home/anton/.platformio/penv`!   

> pio
Traceback (most recent call last):
  File "/usr/bin/pio", line 33, in <module>
    sys.exit(load_entry_point('platformio==4.3.4', 'console_scripts', 'pio')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/pio", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/platformio/__main__.py", line 66, in <module>
    @cli.resultcallback()
     ^^^^^^^^^^^^^^^^^^
AttributeError: 'PlatformioCLI' object has no attribute 'resultcallback'. Did you mean: 'result_callback'?
```

**Comment by ivankravets** [comment]
> platformio==4.3.4

It seems you have multiple PIO Core in the system. 4.3.4 was released almost 10 years ago. 6.1 is the latest stable version. Please uninstall legacy conflicted versions

**Comment by shekhov** [comment]
> > platformio==4.3.4
> 
> It seems you have multiple PIO Core in the system. 4.3.4 was released almost 10 years ago. 6.1 is the latest stable version. Please uninstall legacy conflicted versions

Oh my.. thanks a lot for catching this :)

**Comment by jl2035** [comment]
I fixed this by not using the script:

```
virutalenv venv
source venv/bin/activate
pip install platformio
```
