### ISSUE TITLE
platformio.exe boards > nul throws an exception

### ISSUE THREAD

**Issue by dgnuff** [platformio/platformio-core#4775]
### Configuration

**Operating system**:   Windows 10 22H2

**PlatformIO Version** (`platformio --version`): PlatformIO Core, version 6.1.11

**Python version**: Windows 3.12 amd64

#### Steps to Reproduce

1. Perform a fresh install of Python 3.12 from https://www.python.org/downloads/
2. Perform a fresh install of PlatformIO
3. Open a CMD.EXE prompt and execute the following command: c:\Users\[Redacted]\.platformio\penv\Scripts\platformio.exe boards > nul

### Actual Results

The following exception is thrown:

UnicodeEncodeError: Traceback (most recent call last):
  File "C:\Users\[Redacted]\.platformio\penv\Lib\site-packages\platformio\__main__.py", line 103, in main
    cli()  # pylint: disable=no-value-for-parameter
    ^^^^^
  File "C:\Users\[Redacted]\.platformio\penv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[Redacted]\.platformio\penv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\[Redacted]\.platformio\penv\Lib\site-packages\platformio\cli.py", line 85, in invoke
    return super().invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[Redacted]\.platformio\penv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[Redacted]\.platformio\penv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[Redacted]\.platformio\penv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[Redacted]\.platformio\penv\Lib\site-packages\platformio\commands\boards.py", line 50, in cli
    print_boards(boards)
  File "C:\Users\[Redacted]\.platformio\penv\Lib\site-packages\platformio\commands\boards.py", line 55, in print_boards
    click.echo(
  File "C:\Users\[Redacted]\.platformio\penv\Lib\site-packages\platformio\__main__.py", line 89, in <lambda>
    click.echo = lambda *args, **kwargs: _safe_echo(0, *args, **kwargs)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[Redacted]\.platformio\penv\Lib\site-packages\platformio\__main__.py", line 83, in _safe_echo
    click_echo_origin[origin](*args, **kwargs)
  File "C:\Users\[Redacted]\.platformio\penv\Lib\site-packages\click\utils.py", line 318, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
  File "C:\Users\[Redacted]\.platformio\penv\Lib\site-packages\click\_compat.py", line 542, in _safe_write
    return _write(s)
           ^^^^^^^^^
  File "C:\Users\[Redacted]\.platformio\penv\Lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "C:\Users\[Redacted]\.platformio\penv\Lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "C:\Users\[Redacted]\.platformio\penv\Lib\site-packages\colorama\ansitowin32.py", line 205, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Users\[Redacted]\.platformio\penv\Lib\site-packages\colorama\ansitowin32.py", line 210, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Etc\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2011' in position 58: character maps to <undefined>

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `python -m pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

### Expected Results

The command runs silently with no errors.

### Additional notes:

Adding the --no-ansi flag to the command executed shortens up the exception, but one still gets thrown.
The weird thing is that despite the exception, the board list is produced.  If the command is changed to
"... > boards.txt" then boards.txt is created holding the board list.  And the exception is still thrown.

**Comment by ivankravets** [comment]
It seems you have broken dev-platform. Please remove unofficial dev-platforms from `C:\Users[Redacted].platformio\platforms` or remove `platforms` folder and start building project.
