### ISSUE TITLE
PIO debugger wont start, ESP32-S3

### ISSUE THREAD

**Issue by kma1006** [platformio/platformio-core#4973]
### Configuration

**Operating system**:  Windows 10

**PlatformIO Version** (`platformio --version`):  6.1.15

### Description of problem
I am new to installing PIO and using it with ESP32-S3.  I tried this on 2 computers and got the same errors.  There are no problems compiling, linking, or flashing the ESP32 board.  The problem only occurs when trying to 'debug' using the internal JTAG adapter on the ESP32-S3.  I have configured the USB ports on the computer as follows using Zadig.exe:
1. USB interface 0 -> USB Serial (CDC)
2. USB interface 2 -> libusbK

Below is the DEBUG_CONSOLE output:

undefinedOpen On-Chip Debugger  v0.11.0-esp32-20220706 (2022-07-06-15:48)

Licensed under GNU GPL v2

For bug reports, read

	http://openocd.org/doc/doxygen/bugs.html

Info : only one transport option; autoselect 'jtag'

Info : esp_usb_jtag: VID set to 0x303a and PID to 0x1001

Info : esp_usb_jtag: capabilities descriptor set to 0x2000

adapter speed: 40000 kHz

Warn : Transport "jtag" was already selected

adapter speed: 5000 kHz

Info : Listening on port 6666 for tcl connections

Info : Listening on port 4444 for telnet connections

Error: libusb_open() failed with LIBUSB_ERROR_NOT_SUPPORTED

Info : esp_usb_jtag: serial (DC:DA:0C:3C:B7:FC)

Info : esp_usb_jtag: Device found. Base speed 40000KHz, div range 1 to 255

Info : clock speed 5000 kHz

Info : JTAG tap: esp32s3.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)

Info : JTAG tap: esp32s3.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)

Info : [esp32s3.cpu0] Debug controller was reset.

Info : [esp32s3.cpu0] Core was reset.

Info : [esp32s3.cpu1] Debug controller was reset.

Info : [esp32s3.cpu1] Core was reset.

Info : starting gdb server for esp32s3.cpu0 on 3333

Info : Listening on port 3333 for gdb connections

FileNotFoundError: Traceback (most recent call last):
  File "C:\Users\km\.platformio\penv\Lib\site-packages\platformio\__main__.py", line 103, in main
 cli()  # pylint: disable=no-value-for-parameter
    ^^^^^
  File "C:\Users\km\.platformio\penv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\km\.platformio\penv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\km\.platformio\penv\Lib\site-packages\platformio\cli.py", line 85, in invoke
    return super().invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\km\.platformio\penv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\km\.platformio\penv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\km\.platformio\penv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\km\.platformio\penv\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\km\.platformio\penv\Lib\site-packages\platformio\debug\cli.py", line 109, in cli
    _run(project_dir, debug_config, client_extra_args)
  File "C:\Users\km\.platformio\penv\Lib\site-packages\platformio\debug\cli.py", line 175, in _run
    loop.run_until_complete(coro)
 File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\km\.platformio\penv\Lib\site-packages\platformio\debug\process\gdb.py", line 57, in run
    await self.spawn(*args, cwd=self.project_dir, wait_until_exit=True)
  File "C:\Users\km\.platformio\penv\Lib\site-packages\platformio\debug\process\base.py", line 76, in spawn
    await loop.subprocess_exec(
  File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1743, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 400, in _make_subprocess_transport
    transp = _WindowsSubprocessTransport(self, protocol, args, shell,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 878, in _start
    self._proc = windows_utils.Popen(
                 ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_utils.py", line 153, in __init__
    super().__init__(args, stdin=stdin_rfd, stdout=stdout_wfd,
  File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `python -m pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000142C17C4040>
Traceback (most recent call last):
  File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
                               ^^^^^^^^
  File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
 File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000142C17C4040>
Traceback (most recent call last):
  File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
                               ^^^^^^^^
  File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000142C17C4040>
Traceback (most recent call last):
  File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
                               ^^^^^^^^
  File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x00000142C17967A0>
Traceback (most recent call last):
  File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_subprocess.py", line 125, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
                               ^^^^^^^^
  File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_subprocess.py", line 70, in __repr__
    info.append(f'stdin={stdin.pipe}')
                        ^^^^^^^^^^^^
  File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function Popen.__del__ at 0x00000142C1662020>
Traceback (most recent call last):
  File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1130, in __del__
    self._internal_poll(_deadstate=_maxsize)
  File "C:\Users\km\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1575, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid

I tried re-installing python, I tried running 'python -m pip install -U platformio', I tried deleting the .pio folder and rebuilding, and I tried 'pio upgrade --dev'.  None of these changed this behavior.  I see this on 2 machines (Win10 and Win11) that I installed the PIO environment on.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
debug_tool = esp-builtin
debug_init_break = tbreak setup
platform_packages =
    platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#master
    platformio/framework-arduinoespressif32-libs @ https://github.com/espressif/esp32-arduino-libs.git#idf-release/v5.1

upload_port = COM[5]
debug_port = COM[5]
upload_speed = 2000000     ;ESP32S3 USB-Serial Converter maximum 2000000bps
monitor_speed = 115200
monitor_port = COM[6]
build_type = debug

Any help on this would be appreciated.  If I'm not in the right forum for this problem, please advise where I should post these errors.  Thank you!

**Comment by valeros** [comment]
There is not support for the latest Arduino core, so you're probably using a fork, please forward your issue there.
