### ISSUE TITLE
NameError: name 'includes' is not defined while updating metadata 

### ISSUE THREAD

**Issue by mnabilam13** [platformio/platformio-core#4978]
What kind of issue is this?

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to the
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues) repository

- [ ] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:
WIN 11

**PlatformIO Version** (`platformio --version`):
6.1.15

### Description of problem
I opened the project folder that I will continue. then the output came out like this

Resolving black_f407ve dependencies...
Already up-to-date.
Updating metadata for the vscode IDE...
NameError: Traceback (most recent call last):
  File "C:\Users\LENOVO\.platformio\penv\Lib\site-packages\platformio\__main__.py", line 103, in main
    cli()  # pylint: disable=no-value-for-parameter
    ^^^^^
  File "C:\Users\LENOVO\.platformio\penv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\.platformio\penv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\.platformio\penv\Lib\site-packages\platformio\cli.py", line 85, in invoke
    return super().invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\.platformio\penv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\.platformio\penv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\.platformio\penv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\.platformio\penv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\.platformio\penv\Lib\site-packages\platformio\project\commands\init.py", line 122, in project_init_cmd
    generator.generate()
  File "C:\Users\LENOVO\.platformio\penv\Lib\site-packages\platformio\project\integration\generator.py", line 165, in generate
    contents = self._render_tpl(tpl_path, tpl_vars)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\.platformio\penv\Lib\site-packages\platformio\project\integration\generator.py", line 171, in _render_tpl
    return bottle.template(fp.read(), **tpl_vars)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\.platformio\penv\Lib\site-packages\bottle.py", line 3668, in template
    return TEMPLATES[tplid].render(kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\.platformio\penv\Lib\site-packages\bottle.py", line 3457, in render
    self.execute(stdout, env)
  File "C:\Users\LENOVO\.platformio\penv\Lib\site-packages\bottle.py", line 3444, in execute
    eval(self.co, env)
  File "<string>", line 75, in <module>
NameError: name 'includes' is not defined

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `python -m pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

#### Steps to Reproduce

1.
2.
3.

### Actual Results
as above

### Expected Results
no errors

### Additional info
I restarted vscode, reinstalled platformio but it didn't resolve the issue.

**Comment by ivankravets** [comment]
Could you provide a simple PlatformIO project to reproduce this issue? You can attach it here as ZIP.

**Comment by ivankravets** [comment]
Please reopen if you still need help
