### ISSUE TITLE
pio remote has just stopped working

### ISSUE THREAD

**Issue by mikesowter** [platformio/platformio-core#4994]
What kind of issue is this?

- [ ] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

### Configuration

PIO running on VSC, talking to PIO on RPi

**Operating system**:

**PlatformIO Version** 6.1.16 on PC, 6.1.16 on RPi, python 3.9.1 and python 3.9.2

### Description of problem

have been remote debugging target with 2 USB interfaces, one to ESP8266 and another to arduino nano. Has been working reliably for weeks, just stopped with:

**pio remote device monitor -b 115200 -p /dev/ttyUSB0**
ImportError: Traceback (most recent call last):
  File "C:\Users\Mike\.platformio\penv\Lib\site-packages\platformio\__main__.py", line 103, in main
    cli()  # pylint: disable=no-value-for-parameter
    ^^^^^
  File "C:\Users\Mike\.platformio\penv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mike\.platformio\penv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Mike\.platformio\penv\Lib\site-packages\platformio\cli.py", line 85, in invoke
    return super().invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mike\.platformio\penv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mike\.platformio\penv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mike\.platformio\penv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mike\.platformio\penv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mike\.platformio\penv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mike\.platformio\penv\Lib\site-packages\click\decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mike\.platformio\penv\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mike\.platformio\penv\Lib\site-packages\platformio\remote\cli.py", line 353, in device_monitor
    from platformio.remote.client.device_monitor import DeviceMonitorClient
  File "C:\Users\Mike\.platformio\penv\Lib\site-packages\platformio\remote\client\device_monitor.py", line 22, in <module>   
    from platformio.remote.client.base import RemoteClientBase
  File "C:\Users\Mike\.platformio\penv\Lib\site-packages\platformio\remote\client\base.py", line 30, in <module>
    from platformio.remote.factory.ssl import SSLContextFactory
  File "C:\Users\Mike\.platformio\penv\Lib\site-packages\platformio\remote\factory\ssl.py", line 16, in <module>
    from OpenSSL import SSL  # pylint: disable=import-error
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mike\.platformio\packages\contrib-pioremote\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "C:\Users\Mike\.platformio\packages\contrib-pioremote\OpenSSL\SSL.py", line 11, in <module>
    from OpenSSL._util import (
  File "C:\Users\Mike\.platformio\packages\contrib-pioremote\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "C:\Users\Mike\.platformio\packages\contrib-pioremote\cryptography\hazmat\bindings\openssl\binding.py", line 15, in <module>
    from cryptography.exceptions import InternalError
  File "C:\Users\Mike\.platformio\packages\contrib-pioremote\cryptography\exceptions.py", line 9, in <module>
ImportError: PyO3 modules compiled for CPython 3.8 or older may only be initialized once per interpreter process

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `python -m pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

#### Steps to Reproduce

1. start agent on RPi
2. attempt to start remote monitor: pio remote device monitor -b 115200 -p /dev/ttyUSB0
3. meltdown as above
4. no changes on either platform since last working successfully

### Actual Results

frustration

**Comment by ivankravets** [comment]
Please remove `C:\Users\Mike.platformio\penv` folder and restart VSCode.
