### ISSUE TITLE
Error when trying to run serial monitor

### ISSUE THREAD

**Issue by buteomont** [platformio/platformio-core#5054]
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to the
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues) repository

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: Linux Mint Wilma w/Cinnamon

**PlatformIO Version** (`platformio --version`):Core 6.1.16·Home 3.4.4

### Description of problem
Error occurs when I start Serial Monitor. Was working fine yesterday, no updates afaik.  Error message is below.

#### Steps to Reproduce

1.Click the little plug icon at the bottom of the window
2.That's it.
3.

### Actual Results
 ```
*  Executing task: platformio device monitor 

OSError: Traceback (most recent call last):
  File "/home/david/.platformio/penv/lib/python3.12/site-packages/platformio/__main__.py", line 103, in main
    cli()  # pylint: disable=no-value-for-parameter
    ^^^^^
  File "/home/david/.platformio/penv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/.platformio/penv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/david/.platformio/penv/lib/python3.12/site-packages/platformio/cli.py", line 85, in invoke
    return super().invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/david/.platformio/penv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/.platformio/penv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/.platformio/penv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/.platformio/penv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/.platformio/penv/lib/python3.12/site-packages/platformio/device/monitor/command.py", line 154, in device_monitor_cmd
    start_terminal(options)
  File "/home/david/.platformio/penv/lib/python3.12/site-packages/platformio/device/monitor/terminal.py", line 54, in start_terminal
    term = new_terminal(options)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/.platformio/penv/lib/python3.12/site-packages/platformio/device/monitor/terminal.py", line 103, in new_terminal
    new_serial_instance(options),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/.platformio/penv/lib/python3.12/site-packages/platformio/device/monitor/terminal.py", line 190, in new_serial_instance
    serial_instance.open()
  File "/home/david/.platformio/penv/lib/python3.12/site-packages/serial/serialposix.py", line 336, in open
    self._update_dtr_state()
  File "/home/david/.platformio/penv/lib/python3.12/site-packages/serial/serialposix.py", line 713, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `python -m pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================


 *  The terminal process "platformio 'device', 'monitor'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

```

### Expected Results
Serial data from ESP8266

**Comment by ivankravets** [comment]
It looks like a system issue. Please restart your machine.
