### ISSUE TITLE
Using older GIT version for PlatformIO doesn't check out branches directly

### ISSUE THREAD

**Issue by zxpower** [platformio/platformio-core#885]
------------------------------------------------------------------

### Configuration

**Operating system**: Ubuntu Linux 12.04 LTS

**PlatformIO Version** (`platformio --version`): 3.2.1

### Description of problem

Using PlatformIO with older version of GIT (I have 1.7.9.5) and trying to install platform from specific branch from Github repository using `https://github.com/username/repository.git#branchname` fails.

#### Steps to Reproduce

1. `platformio platform install https://github.com/RystaHub/platform-espressif8266.git#feature/rysta`

### Actual Results

```
PlatformManager: Installing platform-espressif8266
git version 1.7.9.5
Cloning into '/home/user/.platformio/platforms/installing-Jl9bjK-package'...
fatal: https://github.com/RystaHub/platform-espressif8266.git#feature/rysta/info/refs not valid: is this a git repository?
Error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/platformio/__main__.py", line 106, in main
    cli(None, None, None)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/platformio/commands/platform.py", line 85, in platform_install
    skip_default_package=skip_default_package):
  File "/usr/local/lib/python2.7/dist-packages/platformio/managers/platform.py", line 54, in install
    platform_dir = BasePkgManager.install(self, name, requirements)
  File "/usr/local/lib/python2.7/dist-packages/platformio/managers/package.py", line 468, in install
    pkg_dir = self._install_from_url(name, url, requirements)
  File "/usr/local/lib/python2.7/dist-packages/platformio/managers/package.py", line 201, in _install_from_url
    assert vcs.export()
  File "/usr/local/lib/python2.7/dist-packages/platformio/vcsclient.py", line 131, in export
    assert self.run_cmd(args)
  File "/usr/local/lib/python2.7/dist-packages/platformio/vcsclient.py", line 88, in run_cmd
    return check_call(args, **kwargs) == 0
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['git', 'clone', '--recursive', '--depth', '1', 'https://github.com/RystaHub/platform-espressif8266.git#feature/rysta', '/home/user/.platformio/platforms/installing-Jl9bjK-package']' returned non-zero exit status 128

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================
```

### Expected Results

```
git version 2.5.4 (Apple Git-61)
Cloning into '/Users/user/.platformio/platforms/installing-nzARYu-package'...
remote: Counting objects: 92, done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 92 (delta 46), reused 54 (delta 24), pack-reused 0
Unpacking objects: 100% (92/92), done.
Checking connectivity... done.
espressif8266_rysta @ 1.2.1 has been successfully installed!
PackageManager: Installing toolchain-xtensa @ ~1.40802.0
toolchain-xtensa @ 1.40802.0 is already installed
PackageManager: Installing tool-esptool @ ~1.409.0
tool-esptool @ 1.409.0 is already installed
The platform 'https://github.com/RystaHub/platform-espressif8266.git#feature/rysta' has been successfully installed!
The rest of packages will be installed automatically depending on your build environment.
```

**Comment by ivankravets** [comment]
Please re-test with http://docs.platformio.org/en/latest/installation.html#development-version
