### ISSUE TITLE
espressif8266_stage update fails on 3.3.0a8

### ISSUE THREAD

**Issue by rwalli** [platformio/platformio-core#892]
------------------------------------------------------------------

### Configuration

**Operating system**: macOS 10.12.3

**PlatformIO Version** (`platformio --version`): PlatformIO, version 3.3.0a8

### Description of problem

"pio platform update" fails on espressif8266_stage

#### Steps to Reproduce

1. pio platform update

### Actual Results

Updating espressif8266_stage             @ 1.4.0          Error: Traceback (most recent call last):
  File "/Users/xxx/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/platformio/__main__.py", line 106, in main
    cli(None, None, None)
  File "/Users/xxx/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xxx/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/xxx/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xxx/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xxx/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xxx/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/xxx/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/platformio/commands/platform.py", line 151, in platform_update
    platform, only_packages=only_packages, only_check=only_check)
  File "/Users/xxx/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/platformio/managers/platform.py", line 89, in update
    BasePkgManager.update(self, name, requirements, only_check)
  File "/Users/xxx/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 624, in update
    latest = self.outdated(name, requirements, url)
  File "/Users/xxx/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/platformio/managers/platform.py", line 96, in outdated
    latest = BasePkgManager.outdated(self, name, requirements, url)
  File "/Users/xxx/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 497, in outdated
    package_dir, manifest['url'], silent=True)
  File "/Users/xxx/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/platformio/vcsclient.py", line 42, in newClient
    obj = getattr(modules[__name__], "%sClient" % type_.title())(
AttributeError: 'module' object has no attribute 'HttpsClient'

**Comment by ivankravets** [comment]
Thank you! Please `pio upgrade`
