### ISSUE TITLE
Libraries from git repos with a version indicator are treated as entire URLs and cannot be resolved

### ISSUE THREAD

**Issue by jasiek** [platformio/platformio-core#902]
### Configuration

**Operating system**: MacOS X 

**PlatformIO Version** (`platformio --version`): PlatformIO, version 3.2.1

#### Steps to Reproduce

1. Clone this repo: https://github.com/jasiek/ESP8266-Weather/ at revision 47efdea90445c5d631554ba26072e51a0105aa9b
2. Run `pio run`
3. FAIL

### Actual Results

```
fatal: unable to access 'https://github.com/jasiek/Adafruit_HTU21DF_Library.git@master/': The requested URL returned error: 400
Error: Traceback (most recent call last):
  File "/Users/jps/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/platformio/__main__.py", line 106, in main
    cli(None, None, None)
  File "/Users/jps/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jps/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/jps/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jps/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jps/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/jps/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jps/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/platformio/commands/run.py", line 109, in cli
    results.append((envname, ep.process()))
  File "/Users/jps/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/platformio/commands/run.py", line 172, in process
    result = self._run()
  File "/Users/jps/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/platformio/commands/run.py", line 255, in _run
    ], self.verbose)
  File "/Users/jps/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/platformio/commands/run.py", line 276, in _autoinstall_libdeps
    ctx.invoke(cmd_lib_install, libraries=[lib], silent=not verbose)
  File "/Users/jps/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/jps/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/jps/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/platformio/commands/lib.py", line 91, in lib_install
    lm.install(library, silent=silent, interactive=interactive)
  File "/Users/jps/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/platformio/managers/lib.py", line 233, in install
    if not _url else name, _requirements, silent, trigger_event)
  File "/Users/jps/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 468, in install
    pkg_dir = self._install_from_url(name, url, requirements)
  File "/Users/jps/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 201, in _install_from_url
    assert vcs.export()
  File "/Users/jps/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/platformio/vcsclient.py", line 131, in export
    assert self.run_cmd(args)
  File "/Users/jps/.atom/packages/platformio-ide/penv/lib/python2.7/site-packages/platformio/vcsclient.py", line 88, in run_cmd
    return check_call(args, **kwargs) == 0
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['git', 'clone', '--recursive', '--depth', '1', 'https://github.com/jasiek/Adafruit_HTU21DF_Library.git@master', '/Users/jps/github/ESP8266-Weather/.piolibdeps/installing-SFpI16-package']' returned non-zero exit status 128
```

### Expected Results

Project compiles.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
#
# Project Configuration File
#
# A detailed documentation with the EXAMPLES is located here:
# http://docs.platformio.org/en/latest/projectconf.html
#

# A sign `#` at the beginning of the line indicates a comment
# Comment lines are ignored.

# Simple and base environment
# [env:mybaseenv]
# platform = %INSTALLED_PLATFORM_NAME_HERE%
# framework =
# board =
#
# Automatic targets - enable auto-uploading
# targets = upload

[env:nodemcuv2]
platform = espressif8266
framework = arduino
board = nodemcuv2
lib_deps =
  DHT sensor library
  Adafruit Unified Sensor
  Adafruit BMP085 Library
  https://github.com/jasiek/Adafruit_HTU21DF_Library.git@master
  https://github.com/jasiek/metering.git@master
build_flags = !echo "-DLOGGING=1 -DGIT_REVISION='\"$(git rev-parse HEAD)\"' -DMQTT_MAX_PACKET_SIZE=1024 -Wl,-Tesp8266.flash.1m64.ld -DMQTT_BUFFER_SIZE=1024"

```

There's an example here: http://docs.platformio.org/en/latest/projectconf.html that uses this syntax.

**Comment by ivankravets** [comment]
Thanks! I've just fixed a docs. Please replace `@` with `#` for URLs. See 
* http://docs.platformio.org/en/latest/userguide/lib/cmd_install.html
