### ISSUE TITLE
Uncaught error: Failed to get boards

### ISSUE THREAD

**Issue by stevstrong** [platformio/platformio-core#940]
- [x ] PlatformIO IDE:

------------------------------------------------------------------

### Configuration

**Operating system**: Win10 x64

**PlatformIO Version** (`platformio --version`): 2.0.0-beta 2, Core 3.4.0a4

#### Steps to Reproduce

1. Import Arduino IDE project
2. Close ATOM
3. restore project folder and INO folder: delete all newly added folders from the Arduino project folder
4. Reopen ATOM
5. import Arduino project ...

### Actual Results
Error message: Uncaught error: Failed to get boards

### Expected Results
- import project

### Additional info

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.0.0-beta.2

### Stack Trace

Uncaught Error: Failed to get boards

```
At C:\Users\[user]\.atom\packages\platformio-ide\node_modules\react-dom\lib\ReactErrorUtils.js:51

Error: Failed to get boards
    at getBoards (/packages/platformio-ide/lib/utils.js:277:13)
    at ImportArduinoProjectView.initializeBoardsSelect (/packages/platformio-ide/lib/import-arduino-project/view.js:88:20)
    at ImportArduinoProjectView.initialize (/packages/platformio-ide/lib/import-arduino-project/view.js:84:10)
    at ImportArduinoProjectView.BaseView (/packages/platformio-ide/lib/base-view.js:16:20)
    at /packages/platformio-ide/lib/import-arduino-project/view.js:19:38)
    at command (/packages/platformio-ide/lib/import-arduino-project/command.js:22:14)
    at /packages/platformio-ide/lib/main.js:88:58)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at Object.runAtomCommand (/packages/platformio-ide/lib/utils.js:250:24)
    at callback (/packages/platformio-ide/lib/home/containers/welcome-page.js:31:31)
    at Object.invokeGuardedCallback (/packages/platformio-ide/node_modules/react-dom/lib/ReactErrorUtils.js:26:5)
    at executeDispatch (/packages/platformio-ide/node_modules/react-dom/lib/EventPluginUtils.js:85:21)
    at Object.executeDispatchesInOrder (/packages/platformio-ide/node_modules/react-dom/lib/EventPluginUtils.js:108:5)
    at executeDispatchesAndRelease (/packages/platformio-ide/node_modules/react-dom/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (/packages/platformio-ide/node_modules/react-dom/lib/EventPluginHub.js:54:10)
    at Array.forEach (native)
    at forEachAccumulated (/packages/platformio-ide/node_modules/react-dom/lib/forEachAccumulated.js:24:9)
    at Object.processEventQueue (/packages/platformio-ide/node_modules/react-dom/lib/EventPluginHub.js:257:7)
    at runEventQueueInBatch (/packages/platformio-ide/node_modules/react-dom/lib/ReactEventEmitterMixin.js:17:18)
    at /packages/platformio-ide/node_modules/react-dom/lib/ReactEventEmitterMixin.js:28:5)
    at handleTopLevelImpl (/packages/platformio-ide/node_modules/react-dom/lib/ReactEventListener.js:72:24)
    at ReactDefaultBatchingStrategyTransaction.perform (/packages/platformio-ide/node_modules/react-dom/lib/Transaction.js:140:20)
    at Object.batchedUpdates (/packages/platformio-ide/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.batchedUpdates (/packages/platformio-ide/node_modules/react-dom/lib/ReactUpdates.js:97:27)
    at dispatchEvent (/packages/platformio-ide/node_modules/react-dom/lib/ReactEventListener.js:147:20)
```

### Commands

```
     -4:31.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:15.9.0 platformio-ide:import-arduino-ide-project (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -2:52.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:35.6.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -2:35.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:41.5.0 platformio-ide:import-arduino-ide-project (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-clang 0.10.1 
build 0.67.0 
busy 0.7.0 
busy-signal 1.3.0 
file-icons 2.1.3 
intentions 1.1.2 
language-ini 1.19.0 
linter 2.1.2 
linter-gcc 0.7.1 
linter-ui-default 1.2.2 
minimap 4.27.1 
platformio-ide 2.0.0-beta.2 
platformio-ide-terminal 2.5.0 
tool-bar 1.1.0 
```

**Comment by stevstrong** [comment]
Sorry, issue solved, it was an error in a JSON file.
