### ISSUE TITLE
PlaftormIO: Unable to get a list of serial ports.

### ISSUE THREAD

**Issue by wataruland** [platformio/platformio-core#975]
------------------------------------------------------------------

### Configuration

**Operating system**:
Windows 7 64 bits

**PlatformIO Version** (`platformio --version`):
PlatformIO, version 3.4.0b10

### Description of problem
When I press the button "Serial Monitor",  get error message in popup. "PlaftormIO: Unable to get a list of serial ports."

#### Steps to Reproduce

1.Try to open Serial Monitor
2.
3.

### Expected Results
Get list of ports.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
Insert here...
```

**Source file to reproduce issue:**
```cpp
Insert here...
```

### Additional info
Tested with arduino nano, uno, nodemcu and Wemos D1 Mini Pro

Ignoring the error, if I press the Start button, the terminal screen shows this result.

 PS C: \ Users \ path \ pio device monitor --port
Traceback (most recent call last):
  File "C: \ Users \ Wataru \ .platformio \ penv \ Scripts \ pio-script.py", line 6, in <module>
    From pkg_resources import load_entry_point
  File "c: \ users \ wataru \ .platform \ penv \ lib \ site-packages \ pkg_resources \ __ init__.py", line 3036, in <module>
    @_call_aside
  File "c: \ users \ wataru \ .platformio \ penv \ lib \ site-packages \ pkg_resources \ __ init__.py", line 3020, in _call_aside    F (* args, ** kwargs)
  File "c: \ users \ wataru \ .platform \ penv \ lib \ site-packages \ pkg_resources \ __ init__.py", line 3049, in _initialize_master_working_set    Working_set = WorkingSet._build_master ()
  File "c: \ users \ wataru \ .platformio \ penv \ lib \ site-packages \ pkg_resources \ __ init__.py", line 656, in _build_master    return cls._build_from_requirements (__ requires__)
  File "c: \ users \ wataru \ .platformio \ penv \ lib \ site-packages \ pkg_resources \ __ init__.py", line 669, in _build_from_requirements    Dists = ws.resolve (reqs, Environment ())
  File "c: \ users \ wataru \ .platformio \ penv \ lib \ site-packages \ pkg_resources \ __ init__.py", line 854, in resolves    Raise DistributionNotFound (req, requirers)
Pkg_resources.DistributionNotFound: The 'platformio == 3.4.0b9' distribution was not found and required by the application

Also if on the terminal I write platformio device monitor works correctly

**Comment by ivankravets** [comment]
Please remove `c: \ users \ wataru \ .platformio` and start again
