### ISSUE TITLE
error creating new account

### ISSUE THREAD

**Issue by Davey3D** [platformio/platformio-core#987]
When promoted by platformio to create account, entered email, clicked Register, and got:

Error: Traceback (most recent call last):
  File "c:\users\davey\.platformio\penv\lib\site-packages\platformio\__main__.py", line 104, in main
    cli(None, None, None)
  File "c:\users\davey\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\davey\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\davey\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\davey\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\davey\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\davey\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\davey\.platformio\penv\lib\site-packages\platformio\commands\account.py", line 32, in account_register
    pioplus_call(sys.argv[1:])
  File "c:\users\davey\.platformio\penv\lib\site-packages\platformio\managers\core.py", line 70, in pioplus_call
    code = subprocess.call([pioplus_path] + args, **kwargs)
  File "C:\Python27\Lib\subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\Lib\subprocess.py", line 679, in __init__
    errread, errwrite)
  File "C:\Python27\Lib\subprocess.py", line 893, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
Try to remove `c:\users\davey\.platformio\packages` and start again
